package com.np.tele.crm.service.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.np.tele.crm.client.util.CrmClientUtil;
import com.np.tele.crm.constants.IAppConstants;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AlertsServiceService", targetNamespace = "http://service.alerts.crm.tele.np.com/")
public class AlertsServiceService
    extends Service
{
    private final static URL    ALERTSSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger( com.np.tele.crm.service.client.AlertsServiceService.class
                                               .getName() );
    static
    {
        URL url = null;
        try
        {
            URL baseUrl;
            baseUrl = com.np.tele.crm.service.client.AlertsServiceService.class.getResource( "." );
            url = new URL( baseUrl, IAppConstants.CRM_ALERTS_WSDL );
        }
        catch ( MalformedURLException e )
        {
            logger.warning( "Failed to create URL for the wsdl Location: " + IAppConstants.CRM_ALERTS_WSDL
                    + ", retrying as a local file" );
            logger.warning( e.getMessage() );
        }
        ALERTSSERVICESERVICE_WSDL_LOCATION = url;
    }

    public AlertsServiceService( URL wsdlLocation, QName serviceName )
    {
        super( wsdlLocation, serviceName );
    }

    public AlertsServiceService()
    {
        super( ALERTSSERVICESERVICE_WSDL_LOCATION, new QName( "http://service.alerts.crm.tele.np.com/",
                                                              "AlertsServiceService" ) );
    }

    /**
     * 
     * @return
     *     returns CRMAlertsService
     */
    @WebEndpoint(name = "AlertsServicePort")
    public CRMAlertsService getAlertsServicePort()
    {
        /*return super.getPort( new QName( "http://service.alerts.crm.tele.np.com/", "AlertsServicePort" ),
                              CRMAlertsService.class );*/
        return CrmClientUtil.setEndPoint( super.getPort( new QName( "http://service.alerts.crm.tele.np.com/",
                                                                    "AlertsServicePort" ), CRMAlertsService.class ),
                                          IAppConstants.CRM_ALERTS_END_POINT );
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CRMAlertsService
     */
    @WebEndpoint(name = "AlertsServicePort")
    public CRMAlertsService getAlertsServicePort( WebServiceFeature... features )
    {
        return super.getPort( new QName( "http://service.alerts.crm.tele.np.com/", "AlertsServicePort" ),
                              CRMAlertsService.class, features );
    }
}
