
package com.np.tele.crm.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CRMGISService", targetNamespace = "http://service.gis.crm.tele.np.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CRMGISService {


    /**
     * 
     * @param serviceParam
     * @param operationParam
     * @param gisDto
     * @return
     *     returns com.np.tele.crm.service.client.GisDto
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "gisOperation", targetNamespace = "http://service.gis.crm.tele.np.com/", className = "com.np.tele.crm.service.client.GisOperation")
    @ResponseWrapper(localName = "gisOperationResponse", targetNamespace = "http://service.gis.crm.tele.np.com/", className = "com.np.tele.crm.service.client.GisOperationResponse")
    public GisDto gisOperation(
        @WebParam(name = "ServiceParam", targetNamespace = "")
        String serviceParam,
        @WebParam(name = "operationParam", targetNamespace = "")
        String operationParam,
        @WebParam(name = "GISDto", targetNamespace = "")
        GisDto gisDto)
        throws SOAPException_Exception
    ;

}
