
package com.np.tele.crm.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CRMLMSService", targetNamespace = "http://service.lms.crm.tele.np.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CRMLMSService {


    /**
     * 
     * @param lmsDto
     * @param operationParam
     * @return
     *     returns com.np.tele.crm.service.client.LmsDto
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lmsOperation", targetNamespace = "http://service.lms.crm.tele.np.com/", className = "com.np.tele.crm.service.client.LmsOperation")
    @ResponseWrapper(localName = "lmsOperationResponse", targetNamespace = "http://service.lms.crm.tele.np.com/", className = "com.np.tele.crm.service.client.LmsOperationResponse")
    public LmsDto lmsOperation(
        @WebParam(name = "operationParam", targetNamespace = "")
        String operationParam,
        @WebParam(name = "LMSDto", targetNamespace = "")
        LmsDto lmsDto)
        throws SOAPException_Exception
    ;

}
