package com.np.tele.crm.service.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.np.tele.crm.client.util.CrmClientUtil;
import com.np.tele.crm.constants.IAppConstants;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CrmQrcServiceService", targetNamespace = "http://service.qrc.crm.tele.np.com/")
public class CrmQrcServiceService
    extends Service
{
    private final static URL    CRMQRCSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger( com.np.tele.crm.service.client.CrmQrcServiceService.class
                                               .getName() );
    static
    {
        URL url = null;
        try
        {
            URL baseUrl;
            baseUrl = com.np.tele.crm.service.client.CrmQrcServiceService.class.getResource( "." );
            url = new URL( baseUrl, IAppConstants.CRM_QRC_WSDL );
        }
        catch ( MalformedURLException e )
        {
            logger.warning( "Failed to create URL for the wsdl Location: " + IAppConstants.CRM_QRC_WSDL
                    + ", retrying as a local file" );
            logger.warning( e.getMessage() );
        }
        CRMQRCSERVICESERVICE_WSDL_LOCATION = url;
    }

    public CrmQrcServiceService( URL wsdlLocation, QName serviceName )
    {
        super( wsdlLocation, serviceName );
    }

    public CrmQrcServiceService()
    {
        super( CRMQRCSERVICESERVICE_WSDL_LOCATION, new QName( "http://service.qrc.crm.tele.np.com/",
                                                              "CrmQrcServiceService" ) );
    }

    /**
     * 
     * @return
     *     returns CrmQrcService
     */
    @WebEndpoint(name = "CrmQrcServicePort")
    public CrmQrcService getCrmQrcServicePort()
    {
        /* return super.getPort( new QName( "http://service.qrc.crm.tele.np.com/", "CrmQrcServicePort" ),
                               CrmQrcService.class );*/
        return CrmClientUtil.setEndPoint( super.getPort( new QName( "http://service.qrc.crm.tele.np.com/",
                                                                    "CrmQrcServicePort" ), CrmQrcService.class ),
                                          IAppConstants.CRM_QRC_END_POINT );
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CrmQrcService
     */
    @WebEndpoint(name = "CrmQrcServicePort")
    public CrmQrcService getCrmQrcServicePort( WebServiceFeature... features )
    {
        return super.getPort( new QName( "http://service.qrc.crm.tele.np.com/", "CrmQrcServicePort" ),
                              CrmQrcService.class, features );
    }
}
