
package com.np.tele.crm.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CRMReportService", targetNamespace = "http://service.report.crm.tele.np.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CRMReportService {


    /**
     * 
     * @param operationParam
     * @param reportDto
     * @return
     *     returns com.np.tele.crm.service.client.ReportDto
     * @throws SOAPException_Exception
     */
    @WebMethod(operationName = "QRCReportsOperation")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "QRCReportsOperation", targetNamespace = "http://service.report.crm.tele.np.com/", className = "com.np.tele.crm.service.client.QRCReportsOperation")
    @ResponseWrapper(localName = "QRCReportsOperationResponse", targetNamespace = "http://service.report.crm.tele.np.com/", className = "com.np.tele.crm.service.client.QRCReportsOperationResponse")
    public ReportDto qrcReportsOperation(
        @WebParam(name = "operationParam", targetNamespace = "")
        String operationParam,
        @WebParam(name = "ReportDto", targetNamespace = "")
        ReportDto reportDto)
        throws SOAPException_Exception
    ;

    /**
     * 
     * @param serviceParam
     * @param reportDto
     * @param crmParam
     * @return
     *     returns com.np.tele.crm.service.client.ReportDto
     * @throws SOAPException_Exception
     */
    @WebMethod(operationName = "SLAOperations")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SLAOperations", targetNamespace = "http://service.report.crm.tele.np.com/", className = "com.np.tele.crm.service.client.SLAOperations")
    @ResponseWrapper(localName = "SLAOperationsResponse", targetNamespace = "http://service.report.crm.tele.np.com/", className = "com.np.tele.crm.service.client.SLAOperationsResponse")
    public ReportDto slaOperations(
        @WebParam(name = "ServiceParam", targetNamespace = "")
        String serviceParam,
        @WebParam(name = "CrmParam", targetNamespace = "")
        String crmParam,
        @WebParam(name = "ReportDto", targetNamespace = "")
        ReportDto reportDto)
        throws SOAPException_Exception
    ;

    /**
     * 
     * @param operationParam
     * @param reportDto
     * @return
     *     returns com.np.tele.crm.service.client.ReportDto
     * @throws SOAPException_Exception
     */
    @WebMethod(operationName = "INAReportsOperation")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "INAReportsOperation", targetNamespace = "http://service.report.crm.tele.np.com/", className = "com.np.tele.crm.service.client.INAReportsOperation")
    @ResponseWrapper(localName = "INAReportsOperationResponse", targetNamespace = "http://service.report.crm.tele.np.com/", className = "com.np.tele.crm.service.client.INAReportsOperationResponse")
    public ReportDto inaReportsOperation(
        @WebParam(name = "operationParam", targetNamespace = "")
        String operationParam,
        @WebParam(name = "ReportDto", targetNamespace = "")
        ReportDto reportDto)
        throws SOAPException_Exception
    ;

}
