package com.np.tele.crm.service.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.np.tele.crm.client.util.CrmClientUtil;
import com.np.tele.crm.constants.IAppConstants;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "GISServiceService", targetNamespace = "http://service.gis.crm.tele.np.com/")
public class GISServiceService
    extends Service
{
    private final static URL    GISSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger( com.np.tele.crm.service.client.GISServiceService.class
                                               .getName() );
    static
    {
        URL url = null;
        try
        {
            URL baseUrl;
            baseUrl = com.np.tele.crm.service.client.GISServiceService.class.getResource( "." );
            url = new URL( baseUrl, IAppConstants.CRM_GIS_WSDL );
        }
        catch ( MalformedURLException e )
        {
            logger.warning( "Failed to create URL for the wsdl Location: " + IAppConstants.CRM_GIS_WSDL
                    + ", retrying as a local file" );
            logger.warning( e.getMessage() );
        }
        GISSERVICESERVICE_WSDL_LOCATION = url;
    }

    public GISServiceService( URL wsdlLocation, QName serviceName )
    {
        super( wsdlLocation, serviceName );
    }

    public GISServiceService()
    {
        super( GISSERVICESERVICE_WSDL_LOCATION, new QName( "http://service.gis.crm.tele.np.com/", "GISServiceService" ) );
    }

    /**
     * 
     * @return
     *     returns CRMGISService
     */
    @WebEndpoint(name = "GISServicePort")
    public CRMGISService getGISServicePort()
    {
        /*return super.getPort(new QName("http://service.gis.crm.tele.np.com/", "GISServicePort"), CRMGISService.class);*/
        return CrmClientUtil.setEndPoint( super.getPort( new QName( "http://service.gis.crm.tele.np.com/",
                                                                    "GISServicePort" ), CRMGISService.class ),
                                          IAppConstants.CRM_GIS_END_POINT );
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CRMGISService
     */
    @WebEndpoint(name = "GISServicePort")
    public CRMGISService getGISServicePort( WebServiceFeature... features )
    {
        return super.getPort( new QName( "http://service.gis.crm.tele.np.com/", "GISServicePort" ),
                              CRMGISService.class, features );
    }
}
