package com.np.upload.pojo;

// Generated Sep 30, 2015 10:32:56 PM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

/**
 * NpUploads generated by hbm2java
 */
public class NpUploads
    implements java.io.Serializable
{
    private static final long serialVersionUID = -5063169354511880324L;
    private Integer           docId;
    private Integer           version;
    private String            moduleName;
    private String            mappingId;
    private String            docType;
    private String            docName;
    private String            docPath;
    private Date              createdTime;
    private Date              modifiedTime;

    public NpUploads()
    {
    }

    public NpUploads( String moduleName, String mappingId )
    {
        this.moduleName = moduleName;
        this.mappingId = mappingId;
    }

    public NpUploads( String moduleName, String mappingId, String docType )
    {
        this.moduleName = moduleName;
        this.mappingId = mappingId;
        this.docType = docType;
    }

    public NpUploads( String moduleName, String mappingId, String docType, String docName, String docPath )
    {
        this.moduleName = moduleName;
        this.mappingId = mappingId;
        this.docType = docType;
        this.docName = docName;
        this.docPath = docPath;
    }

    public Integer getDocId()
    {
        return docId;
    }

    public void setDocId( Integer docId )
    {
        this.docId = docId;
    }

    public Integer getVersion()
    {
        return version;
    }

    public void setVersion( Integer version )
    {
        this.version = version;
    }

    public String getModuleName()
    {
        return moduleName;
    }

    public void setModuleName( String moduleName )
    {
        this.moduleName = moduleName;
    }

    public String getMappingId()
    {
        return mappingId;
    }

    public void setMappingId( String mappingId )
    {
        this.mappingId = mappingId;
    }

    public String getDocType()
    {
        return docType;
    }

    public void setDocType( String docType )
    {
        this.docType = docType;
    }

    public String getDocName()
    {
        return docName;
    }

    public void setDocName( String docName )
    {
        this.docName = docName;
    }

    public String getDocPath()
    {
        return docPath;
    }

    public void setDocPath( String docPath )
    {
        this.docPath = docPath;
    }

    public Date getCreatedTime()
    {
        return createdTime;
    }

    public void setCreatedTime( Date createdTime )
    {
        this.createdTime = createdTime;
    }

    public Date getModifiedTime()
    {
        return modifiedTime;
    }

    public void setModifiedTime( Date modifiedTime )
    {
        this.modifiedTime = modifiedTime;
    }

    @Override
    public String toString()
    {
        StringBuilder builder = new StringBuilder();
        builder.append( "NpUploads [docId=" ).append( docId ).append( ", version=" ).append( version )
                .append( ", moduleName=" ).append( moduleName ).append( ", mappingId=" ).append( mappingId )
                .append( ", docType=" ).append( docType ).append( ", docName=" ).append( docName )
                .append( ", docPath=" ).append( docPath ).append( "]" );
        return builder.toString();
    }
}
