package com.np.tele.crm.pojos;

// Generated 5 Jul, 2013 11:15:37 AM by Hibernate Tools 3.4.0.CR1
import javax.xml.bind.annotation.XmlTransient;

/**
 * AccessGroup generated by hbm2java
 */
public class AccessGroupPojo
    implements java.io.Serializable
{
    private long             recordId;
    private CrmRolesPojo     crmRoles;
    private GroupsPojo       groups;
    private CrmParameterPojo crmParameter;
    private String           parameterValue;
    private boolean          createAccess;
    private boolean          readAccess;
    private boolean          updateAccess;
    private boolean          deleteAccess;
    private boolean          recoverAccess;
    private boolean          editable;
    private String           status;

    public AccessGroupPojo()
    {
    }

    public AccessGroupPojo( Long recordId )
    {
        this.recordId = recordId;
    }

    public AccessGroupPojo( Long recordId,
                            CrmRolesPojo crmRoles,
                            GroupsPojo groups,
                            CrmParameterPojo crmParameter,
                            String parameterValue,
                            boolean createAccess,
                            boolean readAccess,
                            boolean updateAccess,
                            boolean deleteAccess,
                            String status )
    {
        this.recordId = recordId;
        this.crmRoles = crmRoles;
        this.groups = groups;
        this.crmParameter = crmParameter;
        this.parameterValue = parameterValue;
        this.createAccess = createAccess;
        this.readAccess = readAccess;
        this.updateAccess = updateAccess;
        this.deleteAccess = deleteAccess;
        this.status = status;
    }

    public Long getRecordId()
    {
        return recordId;
    }

    public void setRecordId( Long recordId )
    {
        this.recordId = recordId;
    }

    public CrmRolesPojo getCrmRoles()
    {
        return this.crmRoles;
    }

    public void setCrmRoles( CrmRolesPojo crmRoles )
    {
        this.crmRoles = crmRoles;
    }

    @XmlTransient
    public GroupsPojo getGroups()
    {
        return this.groups;
    }

    public void setGroups( GroupsPojo groups )
    {
        this.groups = groups;
    }

    public CrmParameterPojo getCrmParameter()
    {
        return this.crmParameter;
    }

    public void setCrmParameter( CrmParameterPojo crmParameter )
    {
        this.crmParameter = crmParameter;
    }

    public String getParameterValue()
    {
        return this.parameterValue;
    }

    public void setParameterValue( String parameterValue )
    {
        this.parameterValue = parameterValue;
    }

    public String getStatus()
    {
        return this.status;
    }

    public void setStatus( String status )
    {
        this.status = status;
    }

    public boolean getEditable()
    {
        return editable;
    }

    public void setEditable( boolean editable )
    {
        this.editable = editable;
    }

    public boolean isCreateAccess()
    {
        return createAccess;
    }

    public void setCreateAccess( boolean createAccess )
    {
        this.createAccess = createAccess;
    }

    public boolean isReadAccess()
    {
        return readAccess;
    }

    public void setReadAccess( boolean readAccess )
    {
        this.readAccess = readAccess;
    }

    public boolean isUpdateAccess()
    {
        return updateAccess;
    }

    public void setUpdateAccess( boolean updateAccess )
    {
        this.updateAccess = updateAccess;
    }

    public boolean isDeleteAccess()
    {
        return deleteAccess;
    }

    public void setDeleteAccess( boolean deleteAccess )
    {
        this.deleteAccess = deleteAccess;
    }

    public boolean isRecoverAccess()
    {
        return recoverAccess;
    }

    public void setRecoverAccess( boolean recoverAccess )
    {
        this.recoverAccess = recoverAccess;
    }

    @Override
    public String toString()
    {
        StringBuilder builder = new StringBuilder();
        builder.append( "AccessGroupPojo [recordId=" ).append( recordId ).append( ", crmRoles=" ).append( crmRoles )
                .append( ", crmParameter=" ).append( crmParameter ).append( ", parameterValue=" )
                .append( parameterValue ).append( ", status=" ).append( status ).append( "]" );
        return builder.toString();
    }

    @Override
    public int hashCode()
    {
        final int prime = 31;
        int result = 1;
        result = prime * result + ( ( crmParameter == null ) ? 0 : crmParameter.hashCode() );
        result = prime * result + ( ( crmRoles == null ) ? 0 : crmRoles.hashCode() );
        result = prime * result + ( ( parameterValue == null ) ? 0 : parameterValue.hashCode() );
        result = prime * result + (int) ( recordId ^ ( recordId >>> 32 ) );
        return result;
    }

    @Override
    public boolean equals( Object obj )
    {
        if ( this == obj )
            return true;
        if ( obj == null )
            return false;
        if ( getClass() != obj.getClass() )
            return false;
        AccessGroupPojo other = (AccessGroupPojo) obj;
        if ( crmParameter == null )
        {
            if ( other.crmParameter != null )
                return false;
        }
        else if ( !crmParameter.equals( other.crmParameter ) )
            return false;
        if ( crmRoles == null )
        {
            if ( other.crmRoles != null )
                return false;
        }
        else if ( !crmRoles.equals( other.crmRoles ) )
            return false;
        if ( parameterValue == null )
        {
            if ( other.parameterValue != null )
                return false;
        }
        else if ( !parameterValue.equals( other.parameterValue ) )
            return false;
        if ( recordId != other.recordId )
            return false;
        return true;
    }
}
