package com.np.tele.crm.pojos;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.np.tele.crm.constants.IDateConstants;
import com.np.tele.crm.utils.StringUtils;

/**
 * Area generated by hbm2java
 */
public class AreaPojo
    implements java.io.Serializable
{
    private long             areaId;
    private String           area;
    private String           areaAlias;
    private String           createdBy;
    private Date             createdTime;
    private String           lastModifiedBy;
    private Date             lastModifiedTime;
    private String           status;
    //    private Set<LocalityPojo> localities = new HashSet<LocalityPojo>( 0 );
    private Set<SocietyPojo> societies = new HashSet<SocietyPojo>( 0 );
    private long             cityId;
    private boolean          editable;
    private String           displayCreatedTime;
    private String           displayLastModifiedTime;
    private String           displayCityId;
    private String           displaystateId;
    private String           displayareaId;
    private String           displaysocietyId;

    public AreaPojo()
    {
    }

    public AreaPojo( long areaId, String area, String createdBy )
    {
        this.areaId = areaId;
        this.area = area;
        this.createdBy = createdBy;
    }

    public AreaPojo( long areaId,
                     CityPojo city,
                     String area,
                     String areaAlias,
                     String createdBy,
                     Date createdTime,
                     String lastModifiedBy,
                     Date lastModifiedTime,
                     String status,
                     Set<LocalityPojo> localities )
    {
        this.areaId = areaId;
        this.area = area;
        this.areaAlias = areaAlias;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
        this.status = status;
    }

    public long getAreaId()
    {
        return areaId;
    }

    public void setAreaId( long areaId )
    {
        this.areaId = areaId;
    }

    public long getCityId()
    {
        return cityId;
    }

    public void setCityId( long inCityId )
    {
        cityId = inCityId;
    }

    public String getArea()
    {
        return this.area;
    }

    public void setArea( String area )
    {
        this.area = StringUtils.upperCase( area );
    }

    public String getAreaAlias()
    {
        return this.areaAlias;
    }

    public void setAreaAlias( String areaAlias )
    {
        this.areaAlias = areaAlias;
    }

    public Set<SocietyPojo> getSocieties()
    {
        return societies;
    }

    public void setSocieties( Set<SocietyPojo> societies )
    {
        this.societies = societies;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date inCreatedTime )
    {
        createdTime = inCreatedTime;
        /*if ( StringUtils.isEmpty( displayCreatedTime ) && StringUtils.isValidObj( createdTime ) )
        {
            displayCreatedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( createdTime );
        }*/
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date inLastModifiedTime )
    {
        lastModifiedTime = inLastModifiedTime;
       /* if ( StringUtils.isEmpty( displayLastModifiedTime ) && StringUtils.isValidObj( lastModifiedTime ) )
        {
            displayLastModifiedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( lastModifiedTime );
        }*/
    }

    public String getStatus()
    {
        return this.status;
    }

    public void setStatus( String status )
    {
        this.status = status;
    }

    //    public Set<LocalityPojo> getLocalities()
    //    {
    //        return this.localities;
    //    }
    //
    //    public void setLocalities( Set<LocalityPojo> localities )
    //    {
    //        this.localities = localities;
    //    }
    public boolean isEditable()
    {
        return editable;
    }

    public void setEditable( boolean inEditable )
    {
        editable = inEditable;
    }

    public String getDisplayCreatedTime()
    {
        return displayCreatedTime;
    }

    public void setDisplayCreatedTime( String inDisplayCreatedTime )
    {
        displayCreatedTime = inDisplayCreatedTime;
    }

    public String getDisplayLastModifiedTime()
    {
        return displayLastModifiedTime;
    }

    public void setDisplayLastModifiedTime( String inDisplayLastModifiedTime )
    {
        displayLastModifiedTime = inDisplayLastModifiedTime;
    }

    public String getDisplayCityId()
    {
        return displayCityId;
    }

    public void setDisplayCityId( String displayCityId )
    {
        this.displayCityId = displayCityId;
    }

    public String getDisplaystateId()
    {
        return displaystateId;
    }

    public void setDisplaystateId( String displaystateId )
    {
        this.displaystateId = displaystateId;
    }

    public String getDisplayareaId()
    {
        return displayareaId;
    }

    public void setDisplayareaId( String displayareaId )
    {
        this.displayareaId = displayareaId;
    }

    public String getDisplaysocietyId()
    {
        return displaysocietyId;
    }

    public void setDisplaysocietyId( String displaysocietyId )
    {
        this.displaysocietyId = displaysocietyId;
    }
    
    
    

    @Override
    public String toString()
    {
        StringBuilder builder = new StringBuilder();
        builder.append( "AreaPojo [areaId=" ).append( areaId ).append( ", area=" ).append( area ).append( ", status=" )
                .append( status ).append( ", cityId=" ).append( cityId ).append( "]" );
        return builder.toString();
    }
}
