package com.np.tele.crm.pojos;

// default package
// Generated 3 Oct, 2013 4:08:05 PM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

/**
 * CrmAuditLogPojo generated by hbm2java
 */
public class CrmAuditLogPojo
    implements java.io.Serializable
{
    private long   auditLogId;
    private String oldValues;
    private String newValues;
    private String events;
    private String mappingId;
    private String module;
    private String remarks;
    private String createdBy;
    private Date   createdTime;
    private String displayCreatedTime;
    private String clientIp;
    private String serverIp;
    private String serviceIp;
    private String fromBin;
    private String toBin;

    public CrmAuditLogPojo()
    {
    }

    public CrmAuditLogPojo( long auditLogId,
                            String events,
                            String mappingId,
                            String module,
                            String remarks,
                            String createdBy )
    {
        this.auditLogId = auditLogId;
        this.events = events;
        this.mappingId = mappingId;
        this.module = module;
        this.remarks = remarks;
        this.createdBy = createdBy;
    }

    public CrmAuditLogPojo( long auditLogId,
                            String oldValues,
                            String newValues,
                            String events,
                            String mappingId,
                            String module,
                            String remarks,
                            String createdBy,
                            Date createdTime )
    {
        this.auditLogId = auditLogId;
        this.oldValues = oldValues;
        this.newValues = newValues;
        this.events = events;
        this.mappingId = mappingId;
        this.module = module;
        this.remarks = remarks;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
    }

    public String getFromBin()
    {
        return fromBin;
    }

    public void setFromBin( String inFromBin )
    {
        fromBin = inFromBin;
    }

    public String getToBin()
    {
        return toBin;
    }

    public void setToBin( String inToBin )
    {
        toBin = inToBin;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date inCreatedTime )
    {
        createdTime = inCreatedTime;
        /* if ( StringUtils.isEmpty( displayCreatedTime ) && StringUtils.isValidObj( createdTime ) )
         {
             displayCreatedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( createdTime );
         }*/
    }

    public String getDisplayCreatedTime()
    {
        return displayCreatedTime;
    }

    public void setDisplayCreatedTime( String inDisplayCreatedTime )
    {
        displayCreatedTime = inDisplayCreatedTime;
    }

    public long getAuditLogId()
    {
        return this.auditLogId;
    }

    public void setAuditLogId( long auditLogId )
    {
        this.auditLogId = auditLogId;
    }

    public String getOldValues()
    {
        return this.oldValues;
    }

    public void setOldValues( String oldValues )
    {
        this.oldValues = oldValues;
    }

    public String getNewValues()
    {
        return this.newValues;
    }

    public void setNewValues( String newValues )
    {
        this.newValues = newValues;
    }

    public String getEvents()
    {
        return this.events;
    }

    public void setEvents( String events )
    {
        this.events = events;
    }

    public String getMappingId()
    {
        return this.mappingId;
    }

    public void setMappingId( String mappingId )
    {
        this.mappingId = mappingId;
    }

    public String getModule()
    {
        return this.module;
    }

    public void setModule( String module )
    {
        this.module = module;
    }

    public String getRemarks()
    {
        return this.remarks;
    }

    public void setRemarks( String remarks )
    {
        this.remarks = remarks;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public String getClientIp()
    {
        return clientIp;
    }

    public void setClientIp( String inClientIp )
    {
        clientIp = inClientIp;
    }

    public String getServerIp()
    {
        return serverIp;
    }

    public void setServerIp( String inServerIp )
    {
        serverIp = inServerIp;
    }

    public String getServiceIp()
    {
        return serviceIp;
    }

    public void setServiceIp( String inServiceIp )
    {
        serviceIp = inServiceIp;
    }

    @Override
    public String toString()
    {
        StringBuilder builder = new StringBuilder();
        builder.append( "CrmAuditLogPojo [auditLogId=" ).append( auditLogId ).append( ", oldValues=" )
                .append( oldValues ).append( ", newValues=" ).append( newValues ).append( ", events=" ).append( events )
                .append( ", mappingId=" ).append( mappingId ).append( ", module=" ).append( module )
                .append( ", remarks=" ).append( remarks ).append( ", createdBy=" ).append( createdBy )
                .append( ", createdTime=" ).append( createdTime ).append( ", displayCreatedTime=" )
                .append( displayCreatedTime ).append( ", clientIp=" ).append( clientIp ).append( ", serverIp=" )
                .append( serverIp ).append( ", serviceIp=" ).append( serviceIp ).append( "]" );
        return builder.toString();
    }
}
