package com.np.tele.crm.pojos;

// default package
// Generated Oct 16, 2013 12:03:19 PM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

import javax.xml.bind.annotation.XmlTransient;

import com.np.tele.crm.constants.IDateConstants;
import com.np.tele.crm.utils.StringUtils;

/**
 * CrmAddressDetailsPojo generated by hbm2java
 */
public class CrmAddressDetailsPojo
    implements java.io.Serializable
{
    private long                   recordId;
    private CrmCustomerDetailsPojo crmCustomerDetails;
    private String                 addressType;
    private String                 addLine1;
    private String                 addLine2;
    private String                 addLine3;
    private String                 landmark;
    private long                   contactNo;
    private String                 propertyDetails;
    private int                    pincode;
    private long                   instSocietyId;
    private long                   instLocalityId;
    private long                   instAreaId;
    private String                 createdBy;
    private Date                   createdTime;
    private String                 lastModifiedBy;
    private Date                   lastModifiedTime;
    private String                 displayCreatedTime;
    private String                 displayLastModifiedTime;
    private String                 cityName;
    private String                 stateName;
    private long                   cityId;
    private long                   stateId;
    private boolean                sameAsInstAddr;
    private String                 areaName = null;

    public CrmAddressDetailsPojo()
    {
    }

    public CrmAddressDetailsPojo( Long recordId, String createdBy )
    {
        this.recordId = recordId;
        this.createdBy = createdBy;
    }

    public CrmAddressDetailsPojo( Long recordId,
                                  CrmCustomerDetailsPojo crmCustomerDetailsPojo,
                                  String addressType,
                                  String addLine1,
                                  String addLine2,
                                  String addLine3,
                                  String landmark,
                                  long contactNo,
                                  String propertyDetails,
                                  Integer pincode,
                                  Long instSocietyId,
                                  Long instLocalityId,
                                  Long instAreaId,
                                  String createdBy,
                                  Date createdTime,
                                  String lastModifiedBy,
                                  Date lastModifiedTime )
    {
        this.recordId = recordId;
        this.crmCustomerDetails = crmCustomerDetailsPojo;
        this.addressType = addressType;
        this.addLine1 = addLine1;
        this.addLine2 = addLine2;
        this.addLine3 = addLine3;
        this.landmark = landmark;
        this.contactNo = contactNo;
        this.propertyDetails = propertyDetails;
        this.pincode = pincode;
        this.instSocietyId = instSocietyId;
        this.instLocalityId = instLocalityId;
        this.instAreaId = instAreaId;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
    }

    public int getPincode()
    {
        return pincode;
    }

    public void setPincode( int pincode )
    {
        this.pincode = pincode;
    }

    public long getRecordId()
    {
        return recordId;
    }

    public void setRecordId( long recordId )
    {
        this.recordId = recordId;
    }

    public long getInstSocietyId()
    {
        return instSocietyId;
    }

    public void setInstSocietyId( long instSocietyId )
    {
        this.instSocietyId = instSocietyId;
    }

    public long getInstLocalityId()
    {
        return instLocalityId;
    }

    public void setInstLocalityId( long instLocalityId )
    {
        this.instLocalityId = instLocalityId;
    }

    public long getInstAreaId()
    {
        return instAreaId;
    }

    public void setInstAreaId( long instAreaId )
    {
        this.instAreaId = instAreaId;
    }

    @XmlTransient
    public CrmCustomerDetailsPojo getCrmCustomerDetails()
    {
        return this.crmCustomerDetails;
    }

    public void setCrmCustomerDetails( CrmCustomerDetailsPojo crmCustomerDetailsPojo )
    {
        this.crmCustomerDetails = crmCustomerDetailsPojo;
    }

    public String getAddressType()
    {
        return this.addressType;
    }

    public void setAddressType( String addressType )
    {
        this.addressType = addressType;
    }

    public String getAddLine1()
    {
        return this.addLine1;
    }

    public void setAddLine1( String addLine1 )
    {
        this.addLine1 = StringUtils.upperCase( addLine1 );
    }

    public String getAddLine2()
    {
        return this.addLine2;
    }

    public void setAddLine2( String addLine2 )
    {
        this.addLine2 = StringUtils.upperCase( addLine2 );
    }

    public String getAddLine3()
    {
        return this.addLine3;
    }

    public void setAddLine3( String addLine3 )
    {
        this.addLine3 = StringUtils.upperCase( addLine3 );
    }

    public String getLandmark()
    {
        return this.landmark;
    }

    public void setLandmark( String landmark )
    {
        this.landmark = StringUtils.upperCase( landmark );
    }

    public long getContactNo()
    {
        return this.contactNo;
    }

    public void setContactNo( long contactNo )
    {
        this.contactNo = contactNo;
    }

    public String getPropertyDetails()
    {
        return this.propertyDetails;
    }

    public void setPropertyDetails( String propertyDetails )
    {
        this.propertyDetails = propertyDetails;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date createdTime )
    {
        this.createdTime = createdTime;
       /* if ( StringUtils.isEmpty( displayCreatedTime ) && StringUtils.isValidObj( createdTime ) )
        {
            displayCreatedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( createdTime );
        }*/
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date lastModifiedTime )
    {
        this.lastModifiedTime = lastModifiedTime;
       /* if ( StringUtils.isEmpty( displayLastModifiedTime ) && StringUtils.isValidObj( lastModifiedTime ) )
        {
            displayLastModifiedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( lastModifiedTime );
        }*/
    }

    public String getDisplayCreatedTime()
    {
        return displayCreatedTime;
    }

    public void setDisplayCreatedTime( String displayCreatedTime )
    {
        this.displayCreatedTime = displayCreatedTime;
    }

    public String getDisplayLastModifiedTime()
    {
        return displayLastModifiedTime;
    }

    public void setDisplayLastModifiedTime( String displayLastModifiedTime )
    {
        this.displayLastModifiedTime = displayLastModifiedTime;
    }

    public String getCityName()
    {
        return cityName;
    }

    public void setCityName( String inCityName )
    {
        cityName = inCityName;
    }

    public String getStateName()
    {
        return stateName;
    }

    public void setStateName( String inStateName )
    {
        stateName = inStateName;
    }

    public long getCityId()
    {
        return cityId;
    }

    public void setCityId( long cityId )
    {
        this.cityId = cityId;
    }

    public long getStateId()
    {
        return stateId;
    }

    public void setStateId( long stateId )
    {
        this.stateId = stateId;
    }

    public boolean isSameAsInstAddr()
    {
        return sameAsInstAddr;
    }

    public void setSameAsInstAddr( boolean sameAsInstAddr )
    {
        this.sameAsInstAddr = sameAsInstAddr;
    }

    /**
     * Used for sending zone to billig
     * @return
     */
    @XmlTransient
    public String getAreaName()
    {
        return areaName;
    }

    public void setAreaName( String inAreaName )
    {
        areaName = inAreaName;
    }

    @Override
    public String toString()
    {
        StringBuilder builder = new StringBuilder();
        builder.append( "CrmAddressDetailsPojo [recordId=" ).append( recordId ).append( ", addressType=" )
                .append( addressType ).append( ", addLine1=" ).append( addLine1 ).append( ", addLine2=" )
                .append( addLine2 ).append( ", addLine3=" ).append( addLine3 ).append( ", landmark=" )
                .append( landmark ).append( ", contactNo=" ).append( contactNo ).append( ", pincode=" )
                .append( pincode ).append( ", instSocietyId=" ).append( instSocietyId ).append( ", instLocalityId=" )
                .append( instLocalityId ).append( ", instAreaId=" ).append( instAreaId ).append( ", cityName=" )
                .append( cityName ).append( ", stateName=" ).append( stateName ).append( ", cityId=" ).append( cityId )
                .append( ", stateId=" ).append( stateId ).append( "]" );
        return builder.toString();
    }
}
