package com.np.tele.crm.pojos;
// default package
// Generated Jun 1, 2015 6:07:06 PM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

/**
 * CrmBillingPlanRequestPojo generated by hbm2java
 */
public class CrmBillingPlanRequestPojo
    implements java.io.Serializable
{
    private long   recordId;
    private long   transId;
    private String customerId;
    private String basePlanCode;
    private String addOnPlanCode;
    private String createdBy;
    private Date   createdTime;
    private String lastModifiedBy;
    private Date   lastModifiedTime;
    private String status;

    public CrmBillingPlanRequestPojo()
    {
    }

    public CrmBillingPlanRequestPojo( long recordId, long transId, String createdBy )
    {
        this.recordId = recordId;
        this.transId = transId;
        this.createdBy = createdBy;
    }

    public CrmBillingPlanRequestPojo( long recordId,
                                  long transId,
                                  String customerId,
                                  String basePlanCode,
                                  String addOnPlanCode,
                                  String createdBy,
                                  Date createdTime,
                                  String lastModifiedBy,
                                  Date lastModifiedTime,
                                  String status )
    {
        this.recordId = recordId;
        this.transId = transId;
        this.customerId = customerId;
        this.basePlanCode = basePlanCode;
        this.addOnPlanCode = addOnPlanCode;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
        this.status = status;
    }

    public long getRecordId()
    {
        return this.recordId;
    }

    public void setRecordId( long recordId )
    {
        this.recordId = recordId;
    }

    public long getTransId()
    {
        return this.transId;
    }

    public void setTransId( long transId )
    {
        this.transId = transId;
    }

    public String getCustomerId()
    {
        return this.customerId;
    }

    public void setCustomerId( String customerId )
    {
        this.customerId = customerId;
    }

    public String getBasePlanCode()
    {
        return this.basePlanCode;
    }

    public void setBasePlanCode( String basePlanCode )
    {
        this.basePlanCode = basePlanCode;
    }

    public String getAddOnPlanCode()
    {
        return this.addOnPlanCode;
    }

    public void setAddOnPlanCode( String addOnPlanCode )
    {
        this.addOnPlanCode = addOnPlanCode;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date createdTime )
    {
        this.createdTime = createdTime;
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date lastModifiedTime )
    {
        this.lastModifiedTime = lastModifiedTime;
    }

    public String getStatus()
    {
        return this.status;
    }

    public void setStatus( String status )
    {
        this.status = status;
    }
}
