package com.np.tele.crm.pojos;

// default package
// Generated Oct 16, 2013 12:03:19 PM by Hibernate Tools 3.4.0.CR1
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlTransient;

import com.np.tele.crm.constants.CRMDisplayListConstants;
import com.np.tele.crm.constants.IDateConstants;
import com.np.tele.crm.utils.StringUtils;

/**
 * CrmCustomerDetailsPojo generated by hbm2java
 */
public class CrmCustomerDetailsPojo
    implements java.io.Serializable, Cloneable
{
    private long                       recordId;
    private String                     product;
    private String                     crfId;
    private String                     customerId;
    private Date                       crfDate;
    private String                     connectionType;
    private String                     custFname;
    private String                     custLname;
    private String                     authSignFname;
    private String                     authSignLname;
    private String                     authSignDesg;
    private String                     orgCordFname;
    private String                     orgCordLname;
    private String                     custEmailId;
    private long                       custMobileNo;
    private String                     fhFname;
    private String                     fhLname;
    private Date                       custDob;
    private String                     custGender;
    private String                     nationality;
    private String                     custPanGirNo;
    private long                       rmn;
    private long                       rtn;
    private String                     crfStage;
    private String                     createdBy;
    private Date                       createdTime;
    private String                     lastModifiedBy;
    private Date                       lastModifiedTime;
    private String                     status;
    private Set<CrmAddressDetailsPojo> crmAddressDetailses = new HashSet<CrmAddressDetailsPojo>( 0 );
    private Set<CrmPlanDetailsPojo>    crmPlanDetailses    = new HashSet<CrmPlanDetailsPojo>( 0 );
    private String                     displayCreatedTime;
    private String                     displayLastModifiedTime;
    private String                     displayCrfDate;
    private String                     displayCustDob;
    private String                     crfReferenceNo;
    private String                     crfPreviousStage;
    private Date                       dateOnIsr;
    private String                     isrReferenceNo;
    private CrmPaymentDetailsPojo      crmPaymentDetailsPojo;
    private String                     custMname;
    private String                     altEmailId;
    private String                     serviceType;
    private String                     emailValidationFlag;
    private Date                       ftSubmittionDate;
    private Date                       ftApprovalDate;
    private Date                       activationDate;
    private Date                       barringDate;
    private Date                       unBarringDate;
    private Date                       tempDisconnectDate;
    private Date                       permanentDisconnectDate;
    private long                       npId;
    private long                       spId;
    private long                       businessPartner;
    private String                     salesRepresentative;
    private CrmUserPojo                salesUser;
    private String                     custToken;
    private Date                       tokenDate;
    private String                     installationStatus;
    private boolean                    unRead;
    private long                       inboxId;
    private String                     serviceCode         = null;
    private String                     billDate;
    private Date                       safeCustodyDate;
    private String                     currentUser;
    private String                     linkedCRF;
    private String                     brand;
    private String                     aadharNo;
    private String                     oldNetworkPartner;
    private String                     newNetworkPartner;
    private String                     secondaryMacId;
    private String                     bussinessPartnerCode;

    public CrmCustomerDetailsPojo()
    {
    }

    public CrmCustomerDetailsPojo( Long recordId,
                                   Date crfDate,
                                   String connectionType,
                                   String custFname,
                                   String custLname,
                                   String createdBy )
    {
        this.recordId = recordId;
        this.crfDate = crfDate;
        this.connectionType = connectionType;
        this.custFname = custFname;
        this.custLname = custLname;
        this.createdBy = createdBy;
    }

    public CrmCustomerDetailsPojo( Long recordId,
                                   String product,
                                   String crfId,
                                   String customerId,
                                   Date crfDate,
                                   String connectionType,
                                   String custFname,
                                   String custLname,
                                   String authSignFname,
                                   String authSignLname,
                                   String authSignDesg,
                                   String orgCordFname,
                                   String orgCordLname,
                                   String custEmailId,
                                   long custMobileNo,
                                   String fhFname,
                                   String fhLname,
                                   Date custDob,
                                   String custGender,
                                   String nationality,
                                   String custPanGirNo,
                                   long rmn,
                                   long rtn,
                                   String crfStage,
                                   String createdBy,
                                   Date createdTime,
                                   String lastModifiedBy,
                                   Date lastModifiedTime,
                                   String status,
                                   Set<CrmAddressDetailsPojo> crmAddressDetailses,
                                   Set<CrmPlanDetailsPojo> crmPlanDetailses )
    {
        this.recordId = recordId;
        this.product = product;
        this.crfId = crfId;
        this.customerId = customerId;
        this.crfDate = crfDate;
        this.connectionType = connectionType;
        this.custFname = custFname;
        this.custLname = custLname;
        this.authSignFname = authSignFname;
        this.authSignLname = authSignLname;
        this.authSignDesg = authSignDesg;
        this.orgCordFname = orgCordFname;
        this.orgCordLname = orgCordLname;
        this.custEmailId = custEmailId;
        this.custMobileNo = custMobileNo;
        this.fhFname = fhFname;
        this.fhLname = fhLname;
        this.custDob = custDob;
        this.custGender = custGender;
        this.nationality = nationality;
        this.custPanGirNo = custPanGirNo;
        this.rmn = rmn;
        this.rtn = rtn;
        this.crfStage = crfStage;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
        this.status = status;
        this.crmAddressDetailses = crmAddressDetailses;
        this.crmPlanDetailses = crmPlanDetailses;
    }

    public String getBillDate()
    {
        return billDate;
    }

    public void setBillDate( String inBillDate )
    {
        billDate = inBillDate;
    }

    public CrmPaymentDetailsPojo getCrmPaymentDetailsPojo()
    {
        return crmPaymentDetailsPojo;
    }

    public void setCrmPaymentDetailsPojo( CrmPaymentDetailsPojo crmPaymentDetailsPojo )
    {
        this.crmPaymentDetailsPojo = crmPaymentDetailsPojo;
    }

    public String getProduct()
    {
        return this.product;
    }

    public void setProduct( String product )
    {
        this.product = product;
    }

    public String getCrfId()
    {
        return this.crfId;
    }

    public void setCrfId( String crfId )
    {
        this.crfId = crfId;
    }

    public String getCustomerId()
    {
        return this.customerId;
    }

    public void setCustomerId( String customerId )
    {
        this.customerId = customerId;
    }

    public Date getCrfDate()
    {
        return this.crfDate;
    }

    public void setCrfDate( Date crfDate )
    {
        this.crfDate = crfDate;
        if ( StringUtils.isEmpty( displayCrfDate ) && StringUtils.isValidObj( crfDate ) )
        {
            displayCrfDate = IDateConstants.SDF_DD_MMM_YYYY.format( crfDate );
        }
    }

    public String getConnectionType()
    {
        return this.connectionType;
    }

    public void setConnectionType( String connectionType )
    {
        this.connectionType = connectionType;
    }

    public String getCustFname()
    {
        return this.custFname;
    }

    public void setCustFname( String custFname )
    {
        this.custFname = StringUtils.upperCase( custFname );
    }

    public String getCustLname()
    {
        return this.custLname;
    }

    public void setCustLname( String custLname )
    {
        this.custLname = StringUtils.upperCase( custLname );
    }

    public String getAuthSignFname()
    {
        return this.authSignFname;
    }

    public void setAuthSignFname( String authSignFname )
    {
        this.authSignFname = StringUtils.upperCase( authSignFname );
    }

    public String getAuthSignLname()
    {
        return this.authSignLname;
    }

    public void setAuthSignLname( String authSignLname )
    {
        this.authSignLname = StringUtils.upperCase( authSignLname );
    }

    public String getAuthSignDesg()
    {
        return this.authSignDesg;
    }

    public void setAuthSignDesg( String authSignDesg )
    {
        this.authSignDesg = StringUtils.upperCase( authSignDesg );
    }

    public String getOrgCordFname()
    {
        return this.orgCordFname;
    }

    public void setOrgCordFname( String orgCordFname )
    {
        this.orgCordFname = StringUtils.upperCase( orgCordFname );
    }

    public String getOrgCordLname()
    {
        return this.orgCordLname;
    }

    public void setOrgCordLname( String orgCordLname )
    {
        this.orgCordLname = StringUtils.upperCase( orgCordLname );
    }

    public String getCustEmailId()
    {
        return this.custEmailId;
    }

    public void setCustEmailId( String custEmailId )
    {
        this.custEmailId = custEmailId;
    }

    public long getCustMobileNo()
    {
        return this.custMobileNo;
    }

    public void setCustMobileNo( long custMobileNo )
    {
        this.custMobileNo = custMobileNo;
    }

    public String getFhFname()
    {
        return this.fhFname;
    }

    public void setFhFname( String fhFname )
    {
        this.fhFname = StringUtils.upperCase( fhFname );
    }

    public String getFhLname()
    {
        return this.fhLname;
    }

    public void setFhLname( String fhLname )
    {
        this.fhLname = StringUtils.upperCase( fhLname );
    }

    public Date getCustDob()
    {
        return this.custDob;
    }

    public void setCustDob( Date custDob )
    {
        this.custDob = custDob;
        if ( StringUtils.isEmpty( displayCustDob ) && StringUtils.isValidObj( custDob ) )
        {
            displayCustDob = IDateConstants.SDF_DD_MMM_YYYY.format( custDob );
        }
    }

    public String getCustGender()
    {
        return this.custGender;
    }

    public void setCustGender( String custGender )
    {
        this.custGender = custGender;
    }

    public String getNationality()
    {
        return this.nationality;
    }

    public void setNationality( String nationality )
    {
        this.nationality = nationality;
    }

    public String getCustPanGirNo()
    {
        return this.custPanGirNo;
    }

    public void setCustPanGirNo( String custPanGirNo )
    {
        this.custPanGirNo = custPanGirNo;
    }

    public long getRmn()
    {
        return this.rmn;
    }

    public void setRmn( long rmn )
    {
        this.rmn = rmn;
    }

    public long getRtn()
    {
        return this.rtn;
    }

    public void setRtn( long rtn )
    {
        this.rtn = rtn;
    }

    public String getCrfStage()
    {
        return this.crfStage;
    }

    public void setCrfStage( String crfStage )
    {
        this.crfStage = crfStage;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date createdTime )
    {
        this.createdTime = createdTime;
        /*if ( StringUtils.isEmpty( displayCreatedTime ) && StringUtils.isValidObj( createdTime ) )
        {
            displayCreatedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( createdTime );
        }*/
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date lastModifiedTime )
    {
        this.lastModifiedTime = lastModifiedTime;
        /* if ( StringUtils.isEmpty( displayLastModifiedTime ) && StringUtils.isValidObj( lastModifiedTime ) )
         {
             displayLastModifiedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( lastModifiedTime );
         }*/
    }

    public String getStatus()
    {
        return this.status;
    }

    public void setStatus( String status )
    {
        this.status = status;
    }

    public Set<CrmAddressDetailsPojo> getCrmAddressDetailses()
    {
        return this.crmAddressDetailses;
    }

    public void setCrmAddressDetailses( Set<CrmAddressDetailsPojo> crmAddressDetailses )
    {
        this.crmAddressDetailses = crmAddressDetailses;
    }

    public Set<CrmPlanDetailsPojo> getCrmPlanDetailses()
    {
        return this.crmPlanDetailses;
    }

    public void setCrmPlanDetailses( Set<CrmPlanDetailsPojo> crmPlanDetailses )
    {
        this.crmPlanDetailses = crmPlanDetailses;
    }

    public String getDisplayCreatedTime()
    {
        return displayCreatedTime;
    }

    public void setDisplayCreatedTime( String displayCreatedTime )
    {
        this.displayCreatedTime = displayCreatedTime;
    }

    public String getDisplayLastModifiedTime()
    {
        return displayLastModifiedTime;
    }

    public void setDisplayLastModifiedTime( String displayLastModifiedTime )
    {
        this.displayLastModifiedTime = displayLastModifiedTime;
    }

    public String getDisplayCrfDate()
    {
        return displayCrfDate;
    }

    public void setDisplayCrfDate( String displayCrfDate )
    {
        this.displayCrfDate = displayCrfDate;
    }

    public String getDisplayCustDob()
    {
        return displayCustDob;
    }

    public void setDisplayCustDob( String displayCustDob )
    {
        this.displayCustDob = displayCustDob;
    }

    public String getCrfReferenceNo()
    {
        return crfReferenceNo;
    }

    public void setCrfReferenceNo( String inCrfReferenceNo )
    {
        crfReferenceNo = inCrfReferenceNo;
    }

    public String getCrfPreviousStage()
    {
        return crfPreviousStage;
    }

    public void setCrfPreviousStage( String crfPreviousStage )
    {
        this.crfPreviousStage = crfPreviousStage;
    }

    public Date getDateOnIsr()
    {
        return this.dateOnIsr;
    }

    public void setDateOnIsr( Date dateOnIsr )
    {
        this.dateOnIsr = dateOnIsr;
    }

    public String getIsrReferenceNo()
    {
        return isrReferenceNo;
    }

    public void setIsrReferenceNo( String isrReferenceNo )
    {
        this.isrReferenceNo = isrReferenceNo;
    }

    public String getCustMname()
    {
        return custMname;
    }

    public void setCustMname( String inCustMname )
    {
        custMname = inCustMname;
    }

    public String getAltEmailId()
    {
        return altEmailId;
    }

    public void setAltEmailId( String inAltEmailId )
    {
        altEmailId = inAltEmailId;
    }

    public String getServiceType()
    {
        return serviceType;
    }

    public void setServiceType( String inServiceType )
    {
        serviceType = inServiceType;
    }

    public String getEmailValidationFlag()
    {
        return emailValidationFlag;
    }

    public void setEmailValidationFlag( String inEmailValidationFlag )
    {
        emailValidationFlag = inEmailValidationFlag;
    }

    public Date getFtSubmittionDate()
    {
        return ftSubmittionDate;
    }

    public void setFtSubmittionDate( Date ftSubmittionDate )
    {
        this.ftSubmittionDate = ftSubmittionDate;
    }

    public Date getFtApprovalDate()
    {
        return ftApprovalDate;
    }

    public void setFtApprovalDate( Date ftApprovalDate )
    {
        this.ftApprovalDate = ftApprovalDate;
    }

    public Date getActivationDate()
    {
        return activationDate;
    }

    public void setActivationDate( Date activationDate )
    {
        this.activationDate = activationDate;
    }

    public Date getBarringDate()
    {
        return barringDate;
    }

    public void setBarringDate( Date barringDate )
    {
        this.barringDate = barringDate;
    }

    public Date getUnBarringDate()
    {
        return unBarringDate;
    }

    public void setUnBarringDate( Date unBarringDate )
    {
        this.unBarringDate = unBarringDate;
    }

    public Date getTempDisconnectDate()
    {
        return tempDisconnectDate;
    }

    public void setTempDisconnectDate( Date tempDisconnectDate )
    {
        this.tempDisconnectDate = tempDisconnectDate;
    }

    public Date getPermanentDisconnectDate()
    {
        return permanentDisconnectDate;
    }

    public void setPermanentDisconnectDate( Date permanentDisconnectDate )
    {
        this.permanentDisconnectDate = permanentDisconnectDate;
    }

    public long getRecordId()
    {
        return recordId;
    }

    public void setRecordId( long recordId )
    {
        this.recordId = recordId;
    }

    public long getNpId()
    {
        return npId;
    }

    public void setNpId( long npId )
    {
        this.npId = npId;
    }

    public long getSpId()
    {
        return spId;
    }

    public void setSpId( long spId )
    {
        this.spId = spId;
    }

    public long getBusinessPartner()
    {
        return businessPartner;
    }

    public void setBusinessPartner( long businessPartner )
    {
        this.businessPartner = businessPartner;
    }

    public String getSalesRepresentative()
    {
        return salesRepresentative;
    }

    public void setSalesRepresentative( String inSalesRepresentative )
    {
        salesRepresentative = inSalesRepresentative;
    }

    public CrmUserPojo getSalesUser()
    {
        return salesUser;
    }

    public void setSalesUser( CrmUserPojo inSalesUser )
    {
        salesUser = inSalesUser;
    }

    public String getCustToken()
    {
        return custToken;
    }

    public void setCustToken( String custToken )
    {
        this.custToken = custToken;
    }

    public Date getTokenDate()
    {
        return tokenDate;
    }

    public void setTokenDate( Date tokenDate )
    {
        this.tokenDate = tokenDate;
    }

    public String getInstallationStatus()
    {
        return installationStatus;
    }

    public void setInstallationStatus( String inInstallationStatus )
    {
        installationStatus = inInstallationStatus;
    }

    public boolean isUnRead()
    {
        return unRead;
    }

    public void setUnRead( boolean inUnRead )
    {
        unRead = inUnRead;
    }

    public long getInboxId()
    {
        return inboxId;
    }

    public void setInboxId( long inInboxId )
    {
        inboxId = inInboxId;
    }

    public Date getSafeCustodyDate()
    {
        return safeCustodyDate;
    }

    public void setSafeCustodyDate( Date safeCustodyDate )
    {
        this.safeCustodyDate = safeCustodyDate;
    }

    @XmlTransient
    public String getServiceCode()
    {
        if ( StringUtils.isBlank( serviceCode ) && StringUtils.isNotBlank( getProduct() )
                && StringUtils.isNotBlank( getServiceType() ) )
        {
            CRMDisplayListConstants constants = CRMDisplayListConstants.getConstantByFilter( "PlanService",
                                                                                             getProduct(),
                                                                                             getServiceType() );
            if ( StringUtils.isValidObj( constants ) )
            {
                serviceCode = constants.getCode();
            }
        }
        return serviceCode;
    }

    public void setServiceCode( String inServiceCode )
    {
        serviceCode = inServiceCode;
    }

    public String getCurrentUser()
    {
        return currentUser;
    }

    public void setCurrentUser( String currentUser )
    {
        this.currentUser = currentUser;
    }

    public String getLinkedCRF()
    {
        return linkedCRF;
    }

    public void setLinkedCRF( String linkedCRF )
    {
        this.linkedCRF = linkedCRF;
    }

    public String getBrand()
    {
        return brand;
    }

    public void setBrand( String inBrand )
    {
        brand = inBrand;
    }

    public String getAadharNo()
    {
        return aadharNo;
    }

    public void setAadharNo( String inAadharNo )
    {
        aadharNo = inAadharNo;
    }

    public String getOldNetworkPartner()
    {
        return oldNetworkPartner;
    }

    public void setOldNetworkPartner( String inOldNetworkPartner )
    {
        oldNetworkPartner = inOldNetworkPartner;
    }

    public String getNewNetworkPartner()
    {
        return newNetworkPartner;
    }

    public void setNewNetworkPartner( String inNewNetworkPartner )
    {
        newNetworkPartner = inNewNetworkPartner;
    }

    public String getSecondaryMacId()
    {
        return secondaryMacId;
    }

    public void setSecondaryMacId( String inSecondaryMacId )
    {
        secondaryMacId = inSecondaryMacId;
    }

    public String getBussinessPartnerCode()
    {
        return bussinessPartnerCode;
    }

    public void setBussinessPartnerCode( String inBussinessPartnerCode )
    {
        bussinessPartnerCode = inBussinessPartnerCode;
    }

    @Override
    public String toString()
    {
        StringBuilder builder = new StringBuilder();
        builder.append( "CrmCustomerDetailsPojo [recordId=" ).append( recordId ).append( ", crfId=" ).append( crfId )
                .append( ", customerId=" ).append( customerId ).append( ", custFname=" ).append( custFname )
                .append( ", custLname=" ).append( custLname ).append( ", crfStage=" ).append( crfStage )
                .append( ", status=" ).append( status ).append( "]" );
        return builder.toString();
    }

    @Override
    public int hashCode()
    {
        final int prime = 31;
        int result = 1;
        result = prime * result + ( ( customerId == null ) ? 0 : customerId.hashCode() );
        return result;
    }

    @Override
    public boolean equals( Object obj )
    {
        if ( this == obj )
            return true;
        if ( obj == null )
            return false;
        if ( getClass() != obj.getClass() )
            return false;
        CrmCustomerDetailsPojo other = (CrmCustomerDetailsPojo) obj;
        if ( customerId == null )
        {
            if ( other.customerId != null )
                return false;
        }
        else if ( !customerId.equals( other.customerId ) )
            return false;
        return true;
    }

    public Object clone()
        throws CloneNotSupportedException
    {
        return super.clone();
    }
}
