package com.np.tele.crm.pojos;

//default package
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.np.tele.crm.constants.IDateConstants;
import com.np.tele.crm.utils.StringUtils;

/**
 * CrmCrfDetails generated by hbm2java
 */
public class CrmCrfDetailsPojo
    extends CrmCustomerDetailsPojo
    implements java.io.Serializable
{
    private long                          recordId;
    private String                        product;
    private String                        serviceType;
    private String                        crfId;
    private String                        customerId;
    private Date                          crfDate;
    private String                        displayCrfDate;
    private String                        displayCustDob;
    private String                        connectionType;
    private String                        custFname;
    private String                        custMname;
    private String                        custLname;
    private String                        authSignFname;
    private String                        authSignLname;
    private String                        authSignDesg;
    private String                        orgCordFname;
    private String                        orgCordLname;
    private String                        custEmailId;
    private String                        altEmailId;
    private long                          custMobileNo;
    private String                        fhFname;
    private String                        fhLname;
    private String                        motherFname;
    private String                        motherLname;
    private Date                          custDob;
    private String                        custGender;
    private String                        nationality;
    private String                        custPanGirNo;
    private long                          rmn;
    private long                          rtn;
    private String                        crfStage;
    private String                        crfPreviousStage;
    private String                        crfReferenceNo;
    private String                        isrReferenceNo;
    private String                        salesRepresentative;
    private long                          businessPartner;
    private long                          npId;
    private long                          spId;
    private Date                          ftSubmittionDate;
    private Date                          ftApprovalDate;
    private Date                          dateOnIsr;
    private Date                          activationDate;
    private String                        billDate;
    private String                        createdBy;
    private Date                          createdTime;
    private String                        lastModifiedBy;
    private Date                          lastModifiedTime;
    private String                        status;
    private String                        displayCreatedTime;
    private String                        displayLastModifiedTime;
    private Set<CrmCrfAddressDetailsPojo> crmCrfAddressDetailses = new HashSet<CrmCrfAddressDetailsPojo>( 0 );
    private Set<CrmPlanDetailsPojo>       crmCrfPlanDetailses    = new HashSet<CrmPlanDetailsPojo>( 0 );
    private String                        brand;
    private String                        aadharNo;

    public CrmCrfDetailsPojo()
    {
    }

    public CrmCrfDetailsPojo( Long recordId, Date crfDate, String connectionType, String custFname, String createdBy )
    {
        this.recordId = recordId;
        this.crfDate = crfDate;
        this.connectionType = connectionType;
        this.custFname = custFname;
        this.createdBy = createdBy;
    }

    public CrmCrfDetailsPojo( Long recordId,
                              String product,
                              String serviceType,
                              String crfId,
                              String customerId,
                              Date crfDate,
                              String connectionType,
                              String custFname,
                              String custMname,
                              String custLname,
                              String authSignFname,
                              String authSignLname,
                              String authSignDesg,
                              String orgCordFname,
                              String orgCordLname,
                              String custEmailId,
                              String altEmailId,
                              long custMobileNo,
                              String fhFname,
                              String fhLname,
                              String motherFname,
                              String motherLname,
                              Date custDob,
                              String custGender,
                              String nationality,
                              String custPanGirNo,
                              long rmn,
                              long rtn,
                              String crfStage,
                              String crfPreviousStage,
                              String crfReferenceNo,
                              String isrReferenceNo,
                              String salesRepresentative,
                              Long bpId,
                              Long npId,
                              Long spId,
                              Date ftSubmittionDate,
                              Date ftApprovalDate,
                              Date dateOnIsr,
                              Date activationDate,
                              String billDate,
                              String createdBy,
                              Date createdTime,
                              String lastModifiedBy,
                              Date lastModifiedTime,
                              String status,
                              Set<CrmCrfAddressDetailsPojo> crmCrfAddressDetails,
                              Set<CrmPlanDetailsPojo> crmPlanDetailses )
    {
        this.recordId = recordId;
        this.product = product;
        this.serviceType = serviceType;
        this.crfId = crfId;
        this.customerId = customerId;
        this.crfDate = crfDate;
        this.connectionType = connectionType;
        this.custFname = custFname;
        this.custMname = custMname;
        this.custLname = custLname;
        this.authSignFname = authSignFname;
        this.authSignLname = authSignLname;
        this.authSignDesg = authSignDesg;
        this.orgCordFname = orgCordFname;
        this.orgCordLname = orgCordLname;
        this.custEmailId = custEmailId;
        this.altEmailId = altEmailId;
        this.custMobileNo = custMobileNo;
        this.fhFname = fhFname;
        this.fhLname = fhLname;
        this.motherFname = motherFname;
        this.motherLname = motherLname;
        this.custDob = custDob;
        this.custGender = custGender;
        this.nationality = nationality;
        this.custPanGirNo = custPanGirNo;
        this.rmn = rmn;
        this.rtn = rtn;
        this.crfStage = crfStage;
        this.crfPreviousStage = crfPreviousStage;
        this.crfReferenceNo = crfReferenceNo;
        this.isrReferenceNo = isrReferenceNo;
        this.salesRepresentative = salesRepresentative;
        this.businessPartner = bpId;
        this.npId = npId;
        this.spId = spId;
        this.ftSubmittionDate = ftSubmittionDate;
        this.ftApprovalDate = ftApprovalDate;
        this.dateOnIsr = dateOnIsr;
        this.activationDate = activationDate;
        this.billDate = billDate;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
        this.status = status;
        this.crmCrfPlanDetailses = crmPlanDetailses;
        this.crmCrfAddressDetailses = crmCrfAddressDetails;
    }

    public String getProduct()
    {
        return this.product;
    }

    public void setProduct( String product )
    {
        this.product = product;
    }

    public String getServiceType()
    {
        return this.serviceType;
    }

    public void setServiceType( String serviceType )
    {
        this.serviceType = serviceType;
    }

    public String getCrfId()
    {
        return this.crfId;
    }

    public void setCrfId( String crfId )
    {
        this.crfId = crfId;
    }

    public String getCustomerId()
    {
        return this.customerId;
    }

    public void setCustomerId( String customerId )
    {
        this.customerId = customerId;
    }

    public Date getCrfDate()
    {
        return this.crfDate;
    }

    public void setCrfDate( Date crfDate )
    {
        this.crfDate = crfDate;
       /* if ( StringUtils.isEmpty( displayCrfDate ) && StringUtils.isValidObj( crfDate ) )
        {
            displayCrfDate = IDateConstants.SDF_DD_MMM_YYYY.format( crfDate );
        }*/
    }

    public String getConnectionType()
    {
        return this.connectionType;
    }

    public void setConnectionType( String connectionType )
    {
        this.connectionType = connectionType;
    }

    public String getCustFname()
    {
        return this.custFname;
    }

    public void setCustFname( String custFname )
    {
        this.custFname = custFname;
    }

    public String getCustMname()
    {
        return this.custMname;
    }

    public void setCustMname( String custMname )
    {
        this.custMname = custMname;
    }

    public String getCustLname()
    {
        return this.custLname;
    }

    public void setCustLname( String custLname )
    {
        this.custLname = custLname;
    }

    public String getAuthSignFname()
    {
        return this.authSignFname;
    }

    public void setAuthSignFname( String authSignFname )
    {
        this.authSignFname = authSignFname;
    }

    public String getAuthSignLname()
    {
        return this.authSignLname;
    }

    public void setAuthSignLname( String authSignLname )
    {
        this.authSignLname = authSignLname;
    }

    public String getAuthSignDesg()
    {
        return this.authSignDesg;
    }

    public void setAuthSignDesg( String authSignDesg )
    {
        this.authSignDesg = authSignDesg;
    }

    public String getOrgCordFname()
    {
        return this.orgCordFname;
    }

    public void setOrgCordFname( String orgCordFname )
    {
        this.orgCordFname = orgCordFname;
    }

    public String getOrgCordLname()
    {
        return this.orgCordLname;
    }

    public void setOrgCordLname( String orgCordLname )
    {
        this.orgCordLname = orgCordLname;
    }

    public String getCustEmailId()
    {
        return this.custEmailId;
    }

    public void setCustEmailId( String custEmailId )
    {
        this.custEmailId = custEmailId;
    }

    public String getAltEmailId()
    {
        return this.altEmailId;
    }

    public void setAltEmailId( String altEmailId )
    {
        this.altEmailId = altEmailId;
    }

    public long getCustMobileNo()
    {
        return this.custMobileNo;
    }

    public void setCustMobileNo( long custMobileNo )
    {
        this.custMobileNo = custMobileNo;
    }

    public String getFhFname()
    {
        return this.fhFname;
    }

    public void setFhFname( String fhFname )
    {
        this.fhFname = fhFname;
    }

    public String getFhLname()
    {
        return this.fhLname;
    }

    public void setFhLname( String fhLname )
    {
        this.fhLname = fhLname;
    }

    public String getMotherFname()
    {
        return this.motherFname;
    }

    public void setMotherFname( String motherFname )
    {
        this.motherFname = motherFname;
    }

    public String getMotherLname()
    {
        return this.motherLname;
    }

    public void setMotherLname( String motherLname )
    {
        this.motherLname = motherLname;
    }

    public Date getCustDob()
    {
        return this.custDob;
    }

    public void setCustDob( Date custDob )
    {
        this.custDob = custDob;
       /* if ( StringUtils.isEmpty( displayCustDob ) && StringUtils.isValidObj( custDob ) )
        {
            displayCustDob = IDateConstants.SDF_DD_MMM_YYYY.format( custDob );
        }*/
    }

    public String getCustGender()
    {
        return this.custGender;
    }

    public void setCustGender( String custGender )
    {
        this.custGender = custGender;
    }

    public String getNationality()
    {
        return this.nationality;
    }

    public void setNationality( String nationality )
    {
        this.nationality = nationality;
    }

    public String getCustPanGirNo()
    {
        return this.custPanGirNo;
    }

    public void setCustPanGirNo( String custPanGirNo )
    {
        this.custPanGirNo = custPanGirNo;
    }

    public long getRmn()
    {
        return this.rmn;
    }

    public void setRmn( long rmn )
    {
        this.rmn = rmn;
    }

    public long getRtn()
    {
        return this.rtn;
    }

    public void setRtn( long rtn )
    {
        this.rtn = rtn;
    }

    public String getCrfStage()
    {
        return this.crfStage;
    }

    public void setCrfStage( String crfStage )
    {
        this.crfStage = crfStage;
    }

    public String getCrfPreviousStage()
    {
        return this.crfPreviousStage;
    }

    public void setCrfPreviousStage( String crfPreviousStage )
    {
        this.crfPreviousStage = crfPreviousStage;
    }

    public String getCrfReferenceNo()
    {
        return this.crfReferenceNo;
    }

    public void setCrfReferenceNo( String crfReferenceNo )
    {
        this.crfReferenceNo = crfReferenceNo;
    }

    public String getIsrReferenceNo()
    {
        return this.isrReferenceNo;
    }

    public void setIsrReferenceNo( String isrReferenceNo )
    {
        this.isrReferenceNo = isrReferenceNo;
    }

    public String getSalesRepresentative()
    {
        return this.salesRepresentative;
    }

    public void setSalesRepresentative( String salesRepresentative )
    {
        this.salesRepresentative = salesRepresentative;
    }

    public long getRecordId()
    {
        return recordId;
    }

    public void setRecordId( long recordId )
    {
        this.recordId = recordId;
    }

    public long getBusinessPartner()
    {
        return businessPartner;
    }

    public void setBusinessPartner( long businessPartner )
    {
        this.businessPartner = businessPartner;
    }

    public long getNpId()
    {
        return npId;
    }

    public void setNpId( long npId )
    {
        this.npId = npId;
    }

    public long getSpId()
    {
        return spId;
    }

    public void setSpId( long spId )
    {
        this.spId = spId;
    }

    public Date getFtSubmittionDate()
    {
        return this.ftSubmittionDate;
    }

    public void setFtSubmittionDate( Date ftSubmittionDate )
    {
        this.ftSubmittionDate = ftSubmittionDate;
    }

    public Date getFtApprovalDate()
    {
        return this.ftApprovalDate;
    }

    public void setFtApprovalDate( Date ftApprovalDate )
    {
        this.ftApprovalDate = ftApprovalDate;
    }

    public Date getDateOnIsr()
    {
        return this.dateOnIsr;
    }

    public void setDateOnIsr( Date dateOnIsr )
    {
        this.dateOnIsr = dateOnIsr;
    }

    public Date getActivationDate()
    {
        return this.activationDate;
    }

    public void setActivationDate( Date activationDate )
    {
        this.activationDate = activationDate;
    }

    public String getBillDate()
    {
        return this.billDate;
    }

    public void setBillDate( String billDate )
    {
        this.billDate = billDate;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date createdTime )
    {
        this.createdTime = createdTime;
        /*if ( StringUtils.isEmpty( displayCreatedTime ) && StringUtils.isValidObj( createdTime ) )
        {
            displayCreatedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( createdTime );
        }*/
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date lastModifiedTime )
    {
        this.lastModifiedTime = lastModifiedTime;
        /*if ( StringUtils.isEmpty( displayLastModifiedTime ) && StringUtils.isValidObj( lastModifiedTime ) )
        {
            displayLastModifiedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( lastModifiedTime );
        }*/
    }

    public String getStatus()
    {
        return this.status;
    }

    public void setStatus( String status )
    {
        this.status = status;
    }

    public Set<CrmCrfAddressDetailsPojo> getCrmCrfAddressDetailses()
    {
        return crmCrfAddressDetailses;
    }

    public Set<CrmPlanDetailsPojo> getCrmCrfPlanDetailses()
    {
        return crmCrfPlanDetailses;
    }

    public void setCrmCrfAddressDetailses( Set<CrmCrfAddressDetailsPojo> inCrmAddressDetailses )
    {
        crmCrfAddressDetailses = inCrmAddressDetailses;
    }

    public void setCrmCrfPlanDetailses( Set<CrmPlanDetailsPojo> inCrmPlanDetailses )
    {
        crmCrfPlanDetailses = inCrmPlanDetailses;
    }

    public String getDisplayCrfDate()
    {
        return displayCrfDate;
    }

    public void setDisplayCrfDate( String inDisplayCrfDate )
    {
        displayCrfDate = inDisplayCrfDate;
    }

    public String getDisplayCustDob()
    {
        return displayCustDob;
    }

    public void setDisplayCustDob( String inDisplayCustDob )
    {
        displayCustDob = inDisplayCustDob;
    }

    public String getDisplayCreatedTime()
    {
        return displayCreatedTime;
    }

    public String getDisplayLastModifiedTime()
    {
        return displayLastModifiedTime;
    }

    public void setDisplayCreatedTime( String inDisplayCreatedTime )
    {
        displayCreatedTime = inDisplayCreatedTime;
    }

    public void setDisplayLastModifiedTime( String inDisplayLastModifiedTime )
    {
        displayLastModifiedTime = inDisplayLastModifiedTime;
    }

    public String getBrand()
    {
        return brand;
    }

    public void setBrand( String inBrand )
    {
        brand = inBrand;
    }

    public String getAadharNo()
    {
        return aadharNo;
    }

    public void setAadharNo( String inAadharNo )
    {
        aadharNo = inAadharNo;
    }
}
