package com.np.tele.crm.pojos;

// default package
// Generated May 7, 2015 1:08:47 PM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

import com.np.tele.crm.constants.IDateConstants;
import com.np.tele.crm.utils.StringUtils;

/**
 * CrmCrfPlanDetailsPojo generated by hbm2java
 */
public class CrmCrfPlanDetailsPojo
    extends CrmPlanDetailsPojo
    implements java.io.Serializable
{
    private long   recordId;
    private long   customerRecordId;
    private String basePlanCode;
    private String addOnPlanCode;
    private String promoCode;
    private String preferredBillLang;
    private String usageType;
    private String billMode;
    private String createdBy;
    private Date   createdTime;
    private String lastModifiedBy;
    private Date   lastModifiedTime;
    private String displayCreatedTime;
    private String displayLastModifiedTime;

    public CrmCrfPlanDetailsPojo()
    {
    }

    public CrmCrfPlanDetailsPojo( Long recordId, String createdBy )
    {
        this.recordId = recordId;
        this.createdBy = createdBy;
    }

    public CrmCrfPlanDetailsPojo( Long recordId,
                                  String basePlanName,
                                  String addOnPlanName,
                                  String promoCode,
                                  String preferredBillLang,
                                  String usageType,
                                  String billMode,
                                  String createdBy,
                                  Date createdTime,
                                  String lastModifiedBy,
                                  Date lastModifiedTime )
    {
        this.recordId = recordId;
        this.basePlanCode = basePlanName;
        this.addOnPlanCode = addOnPlanName;
        this.promoCode = promoCode;
        this.preferredBillLang = preferredBillLang;
        this.usageType = usageType;
        this.billMode = billMode;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
    }

    public long getRecordId()
    {
        return recordId;
    }

    public void setRecordId( long recordId )
    {
        this.recordId = recordId;
    }

    public long getCustomerRecordId()
    {
        return customerRecordId;
    }

    public void setCustomerRecordId( long inCustomerRecordId )
    {
        customerRecordId = inCustomerRecordId;
    }

    public String getBasePlanCode()
    {
        return this.basePlanCode;
    }

    public void setBasePlanCode( String basePlanName )
    {
        this.basePlanCode = basePlanName;
    }

    public String getAddOnPlanCode()
    {
        return this.addOnPlanCode;
    }

    public void setAddOnPlanCode( String addOnPlanName )
    {
        this.addOnPlanCode = addOnPlanName;
    }

    public String getPromoCode()
    {
        return this.promoCode;
    }

    public void setPromoCode( String promoCode )
    {
        this.promoCode = promoCode;
    }

    public String getPreferredBillLang()
    {
        return this.preferredBillLang;
    }

    public void setPreferredBillLang( String preferredBillLang )
    {
        this.preferredBillLang = preferredBillLang;
    }

    public String getUsageType()
    {
        return this.usageType;
    }

    public void setUsageType( String usageType )
    {
        this.usageType = usageType;
    }

    public String getBillMode()
    {
        return this.billMode;
    }

    public void setBillMode( String billMode )
    {
        this.billMode = billMode;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date createdTime )
    {
        this.createdTime = createdTime;
        /*if ( StringUtils.isEmpty( displayCreatedTime ) && StringUtils.isValidObj( createdTime ) )
        {
            displayCreatedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( createdTime );
        }*/
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date lastModifiedTime )
    {
        this.lastModifiedTime = lastModifiedTime;
        /*if ( StringUtils.isEmpty( displayLastModifiedTime ) && StringUtils.isValidObj( lastModifiedTime ) )
        {
            displayLastModifiedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( lastModifiedTime );
        }*/
    }

    public String getDisplayCreatedTime()
    {
        return displayCreatedTime;
    }

    public void setDisplayCreatedTime( String displayCreatedTime )
    {
        this.displayCreatedTime = displayCreatedTime;
    }

    public String getDisplayLastModifiedTime()
    {
        return displayLastModifiedTime;
    }

    public void setDisplayLastModifiedTime( String displayLastModifiedTime )
    {
        this.displayLastModifiedTime = displayLastModifiedTime;
    }
}
