package com.np.tele.crm.pojos;

// default package
// Generated 25 May, 2017 5:03:47 PM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

import javax.xml.bind.annotation.XmlTransient;

/**
 * CrmCustAadharNumber generated by hbm2java
 */
public class CrmCustAadharNumberPojo
    implements java.io.Serializable
{
    private Long   recordId;
    private String mappingId;
    private String aadharNumber;
    private String aadharAdd;
    private String propertyDetails;
    private String instAddress;
    private String createdBy;
    private Date   createdTime;

    public CrmCustAadharNumberPojo()
    {
    }

    public CrmCustAadharNumberPojo( String aadharNumber, String aadharAdd, String mappingId )
    {
        this.aadharNumber = aadharNumber;
        this.aadharAdd = aadharAdd;
        this.mappingId = mappingId;
    }

    @XmlTransient
    public Long getRecordId()
    {
        return this.recordId;
    }

    public void setRecordId( Long recordId )
    {
        this.recordId = recordId;
    }

    public String getAadharNumber()
    {
        return this.aadharNumber;
    }

    public void setAadharNumber( String aadharNumber )
    {
        this.aadharNumber = aadharNumber;
    }

    public String getAadharAdd()
    {
        return this.aadharAdd;
    }

    public void setAadharAdd( String aadharAdd )
    {
        this.aadharAdd = aadharAdd;
    }
    @XmlTransient
    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }
    @XmlTransient
    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date createdTime )
    {
        this.createdTime = createdTime;
    }
    @XmlTransient
    public String getMappingId()
    {
        return mappingId;
    }

    public void setMappingId( String inMappingId )
    {
        mappingId = inMappingId;
    }

    public String getPropertyDetails()
    {
        return propertyDetails;
    }

    public void setPropertyDetails( String inPropertyDetails )
    {
        propertyDetails = inPropertyDetails;
    }

    public String getInstAddress()
    {
        return instAddress;
    }

    public void setInstAddress( String inInstAddress )
    {
        instAddress = inInstAddress;
    }
}
