package com.np.tele.crm.pojos;

// Generated Dec 2, 2013 5:15:16 PM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

/**
 * CrmCmsFilePojo generated by hbm2java
 */
public class CrmCmsFilePojo
    implements java.io.Serializable
{
    private long   cmsFileId;
    private String cmsFileName;
    private String cmsFileType;
    private String failReason;
    private String createdBy;
    private Date   createdTime;
    private String status;

    public CrmCmsFilePojo()
    {
    }

    public CrmCmsFilePojo( Long cmsFileId, String cmsFileName, String cmsFileType, String failReason, String createdBy )
    {
        this.cmsFileId = cmsFileId;
        this.cmsFileName = cmsFileName;
        this.cmsFileType = cmsFileType;
        this.failReason = failReason;
        this.createdBy = createdBy;
    }

    public CrmCmsFilePojo( Long cmsFileId,
                           String cmsFileName,
                           String cmsFileType,
                           String failReason,
                           String createdBy,
                           Date createdTime,
                           String status )
    {
        this.cmsFileId = cmsFileId;
        this.cmsFileName = cmsFileName;
        this.cmsFileType = cmsFileType;
        this.failReason = failReason;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.status = status;
    }

    public long getCmsFileId()
    {
        return cmsFileId;
    }

    public void setCmsFileId( long cmsFileId )
    {
        this.cmsFileId = cmsFileId;
    }

    public String getCmsFileName()
    {
        return this.cmsFileName;
    }

    public void setCmsFileName( String cmsFileName )
    {
        this.cmsFileName = cmsFileName;
    }

    public String getCmsFileType()
    {
        return this.cmsFileType;
    }

    public void setCmsFileType( String cmsFileType )
    {
        this.cmsFileType = cmsFileType;
    }

    public String getFailReason()
    {
        return this.failReason;
    }

    public void setFailReason( String failReason )
    {
        this.failReason = failReason;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date createdTime )
    {
        this.createdTime = createdTime;
    }

    public String getStatus()
    {
        return this.status;
    }

    public void setStatus( String status )
    {
        this.status = status;
    }
}
