package com.np.tele.crm.pojos;

// default package
// Generated Aug 20, 2015 10:22:07 AM by Hibernate Tools 3.4.0.CR1
/**
 * CrmEmailAttachment generated by hbm2java
 */
public class CrmEmailAttachment
    implements java.io.Serializable
{
    private long   recordId;
    private long   alertId;
    private byte[] attachment;
    private String attachmentPath;
    private String fileName;

    public CrmEmailAttachment()
    {
    }

    public CrmEmailAttachment( long recordId, byte[] attachment )
    {
        this.recordId = recordId;
        this.attachment = attachment;
    }

    public CrmEmailAttachment( long recordId, long alertId, byte[] attachment, String attachmentPath )
    {
        this.recordId = recordId;
        this.alertId = alertId;
        this.attachment = attachment;
        this.attachmentPath = attachmentPath;
    }

    public long getRecordId()
    {
        return this.recordId;
    }

    public void setRecordId( long recordId )
    {
        this.recordId = recordId;
    }

    public byte[] getAttachment()
    {
        return attachment;
    }

    public void setAttachment( byte[] attachment )
    {
        this.attachment = attachment;
    }

    public String getAttachmentPath()
    {
        return this.attachmentPath;
    }

    public void setAttachmentPath( String attachmentPath )
    {
        this.attachmentPath = attachmentPath;
    }

    public long getAlertId()
    {
        return alertId;
    }

    public void setAlertId( long alertId )
    {
        this.alertId = alertId;
    }

    public String getFileName()
    {
        return fileName;
    }

    public void setFileName( String fileName )
    {
        this.fileName = fileName;
    }
}
