package com.np.tele.crm.pojos;

import java.util.Date;

import com.np.tele.crm.constants.IDateConstants;
import com.np.tele.crm.utils.StringUtils;

/**
 * CrmInbox generated by hbm2java
 */
public class CrmInboxPojo
    implements java.io.Serializable
{
    private long    inboxId;
    private String  userId;
    private String  requestType;
    private String  mappingId;
    private String  stage;
    private String  createdBy;
    private Date    createdTime;
    private String  lastModifiedBy;
    private Date    lastModifiedTime;
    private String  status;
    private String  displayCreatedTime;
    private String  displayLastModifiedTime;
    private String  partnerType;
    private long    partnerId;
    // Don't make this false.
    private boolean unRead = true;

    public CrmInboxPojo()
    {
    }

    public CrmInboxPojo( Long inboxId, String requestType, String mappingId, String stage, String createdBy )
    {
        this.inboxId = inboxId;
        this.requestType = requestType;
        this.mappingId = mappingId;
        this.stage = stage;
        this.createdBy = createdBy;
    }

    public CrmInboxPojo( Long inboxId,
                         String userId,
                         String requestType,
                         String mappingId,
                         String stage,
                         String createdBy,
                         Date createdTime,
                         String lastModifiedBy,
                         Date lastModifiedTime,
                         String status )
    {
        this.inboxId = inboxId;
        this.userId = userId;
        this.requestType = requestType;
        this.mappingId = mappingId;
        this.stage = stage;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
        this.status = status;
    }

    public long getInboxId()
    {
        return inboxId;
    }

    public void setInboxId( long inboxId )
    {
        this.inboxId = inboxId;
    }

    public long getPartnerId()
    {
        return partnerId;
    }

    public void setPartnerId( long partnerId )
    {
        this.partnerId = partnerId;
    }

    public String getUserId()
    {
        return this.userId;
    }

    public void setUserId( String userId )
    {
        this.userId = userId;
    }

    public String getRequestType()
    {
        return this.requestType;
    }

    public void setRequestType( String requestType )
    {
        this.requestType = requestType;
    }

    public String getMappingId()
    {
        return this.mappingId;
    }

    public void setMappingId( String mappingId )
    {
        this.mappingId = mappingId;
    }

    public String getStage()
    {
        return this.stage;
    }

    public void setStage( String stage )
    {
        this.stage = stage;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date inCreatedTime )
    {
        createdTime = inCreatedTime;
        /* if ( StringUtils.isEmpty( displayCreatedTime ) && StringUtils.isValidObj( createdTime ) )
         {
             displayCreatedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( createdTime );
         }*/
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date inLastModifiedTime )
    {
        lastModifiedTime = inLastModifiedTime;
        /*if ( StringUtils.isEmpty( displayLastModifiedTime ) && StringUtils.isValidObj( lastModifiedTime ) )
        {
            displayLastModifiedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( lastModifiedTime );
        }*/
    }

    public String getStatus()
    {
        return this.status;
    }

    public void setStatus( String status )
    {
        this.status = status;
    }

    public String getDisplayCreatedTime()
    {
        return displayCreatedTime;
    }

    public void setDisplayCreatedTime( String inDisplayCreatedTime )
    {
        displayCreatedTime = inDisplayCreatedTime;
    }

    public String getDisplayLastModifiedTime()
    {
        return displayLastModifiedTime;
    }

    public void setDisplayLastModifiedTime( String inDisplayLastModifiedTime )
    {
        displayLastModifiedTime = inDisplayLastModifiedTime;
    }

    public String getPartnerType()
    {
        return partnerType;
    }

    public void setPartnerType( String inPartnerType )
    {
        partnerType = inPartnerType;
    }

    public boolean isUnRead()
    {
        return unRead;
    }

    public void setUnRead( boolean inUnRead )
    {
        unRead = inUnRead;
    }

    @Override
    public int hashCode()
    {
        final int prime = 31;
        int result = 1;
        result = prime * result + ( ( mappingId == null ) ? 0 : mappingId.hashCode() );
        result = prime * result + ( ( requestType == null ) ? 0 : requestType.hashCode() );
        result = prime * result + ( ( stage == null ) ? 0 : stage.hashCode() );
        result = prime * result + ( ( status == null ) ? 0 : status.hashCode() );
        result = prime * result + ( ( userId == null ) ? 0 : userId.hashCode() );
        return result;
    }

    @Override
    public boolean equals( Object obj )
    {
        if ( this == obj )
            return true;
        if ( obj == null )
            return false;
        if ( getClass() != obj.getClass() )
            return false;
        CrmInboxPojo other = (CrmInboxPojo) obj;
        if ( mappingId == null )
        {
            if ( other.mappingId != null )
                return false;
        }
        else if ( !mappingId.equals( other.mappingId ) )
            return false;
        if ( requestType == null )
        {
            if ( other.requestType != null )
                return false;
        }
        else if ( !requestType.equals( other.requestType ) )
            return false;
        if ( stage == null )
        {
            if ( other.stage != null )
                return false;
        }
        else if ( !stage.equals( other.stage ) )
            return false;
        if ( status == null )
        {
            if ( other.status != null )
                return false;
        }
        else if ( !status.equals( other.status ) )
            return false;
        if ( userId == null )
        {
            if ( other.userId != null )
                return false;
        }
        else if ( !userId.equals( other.userId ) )
            return false;
        return true;
    }

    @Override
    public String toString()
    {
        StringBuilder builder = new StringBuilder();
        builder.append( "CrmInboxPojo [inboxId=" ).append( inboxId ).append( ", userId=" ).append( userId )
                .append( ", requestType=" ).append( requestType ).append( ", mappingId=" ).append( mappingId )
                .append( ", stage=" ).append( stage ).append( ", status=" ).append( status ).append( "]" );
        return builder.toString();
    }
}
