package com.np.tele.crm.pojos;

// Generated 8 May, 2015 3:13:44 PM by Hibernate Tools 4.3.1
import java.util.Date;

/**
 * CrmMassOutageSocietyPojo generated by hbm2java
 */
public class CrmMassOutageSocietyPojo
    implements java.io.Serializable
{
    private static final long serialVersionUID = 6747203584970224692L;
    private long              recordId;
    private long              outageId;
    //    private long              outageLocalityId;
    private long              outageAreaId;
    private long              societyId;
    private String            society;
    private String            resolvedBy;
    private Date              resolvedOn;
    private boolean           enabled;
    private boolean           startPoint;
    private String            outageActivity;

    public CrmMassOutageSocietyPojo()
    {
    }

    public long getRecordId()
    {
        return recordId;
    }

    public void setRecordId( long recordId )
    {
        this.recordId = recordId;
    }

    public long getOutageId()
    {
        return outageId;
    }

    public void setOutageId( long outageId )
    {
        this.outageId = outageId;
    }

    //    public long getOutageLocalityId()
    //    {
    //        return outageLocalityId;
    //    }
    //
    //    public void setOutageLocalityId( long outageLocalityId )
    //    {
    //        this.outageLocalityId = outageLocalityId;
    //    }
    public long getOutageAreaId()
    {
        return outageAreaId;
    }

    public void setOutageAreaId( long outageAreaId )
    {
        this.outageAreaId = outageAreaId;
    }

    public long getSocietyId()
    {
        return societyId;
    }

    public void setSocietyId( long societyId )
    {
        this.societyId = societyId;
    }

    public String getSociety()
    {
        return this.society;
    }

    public void setSociety( String society )
    {
        this.society = society;
    }

    public String getResolvedBy()
    {
        return this.resolvedBy;
    }

    public void setResolvedBy( String resolvedBy )
    {
        this.resolvedBy = resolvedBy;
    }

    public Date getResolvedOn()
    {
        return this.resolvedOn;
    }

    public void setResolvedOn( Date resolvedOn )
    {
        this.resolvedOn = resolvedOn;
    }

    public boolean isEnabled()
    {
        return enabled;
    }

    public void setEnabled( boolean enabled )
    {
        this.enabled = enabled;
    }

    public boolean isStartPoint()
    {
        return startPoint;
    }

    public void setStartPoint( boolean startPoint )
    {
        this.startPoint = startPoint;
    }

    public String getOutageActivity()
    {
        return outageActivity;
    }

    public void setOutageActivity( String outageActivity )
    {
        this.outageActivity = outageActivity;
    }

    @Override
    public int hashCode()
    {
        final int prime = 31;
        int result = 1;
        result = prime * result + (int) ( societyId ^ ( societyId >>> 32 ) );
        return result;
    }

    @Override
    public boolean equals( Object obj )
    {
        if ( this == obj )
            return true;
        if ( obj == null )
            return false;
        if ( getClass() != obj.getClass() )
            return false;
        CrmMassOutageSocietyPojo other = (CrmMassOutageSocietyPojo) obj;
        if ( societyId != other.societyId )
            return false;
        return true;
    }
}
