package com.np.tele.crm.pojos;

// Generated 8 May, 2015 3:13:44 PM by Hibernate Tools 4.3.1
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CrmMassOutageCityPojo generated by hbm2java
 */
public class CrmMassOutageCityPojo
    implements java.io.Serializable
{
    private static final long          serialVersionUID       = 3861359037468520249L;
    private long                       recordId;
    private long                       outageId;
    private long                       outageStateId;
    private long                       cityId;
    private String                     cityName;
    private String                     resolvedBy;
    private Date                       resolvedOn;
    private boolean                    enabled;
    private boolean                    startPoint;
    private Set<CrmMassOutageAreaPojo> crmMassOutageAreaPojos = new HashSet<CrmMassOutageAreaPojo>( 0 );

    public CrmMassOutageCityPojo()
    {
    }

    public long getRecordId()
    {
        return recordId;
    }

    public void setRecordId( long recordId )
    {
        this.recordId = recordId;
    }

    public long getOutageId()
    {
        return outageId;
    }

    public void setOutageId( long outageId )
    {
        this.outageId = outageId;
    }

    public long getOutageStateId()
    {
        return outageStateId;
    }

    public void setOutageStateId( long outageStateId )
    {
        this.outageStateId = outageStateId;
    }

    public long getCityId()
    {
        return cityId;
    }

    public void setCityId( long cityId )
    {
        this.cityId = cityId;
    }

    public String getCityName()
    {
        return this.cityName;
    }

    public void setCityName( String cityName )
    {
        this.cityName = cityName;
    }

    public String getResolvedBy()
    {
        return this.resolvedBy;
    }

    public void setResolvedBy( String resolvedBy )
    {
        this.resolvedBy = resolvedBy;
    }

    public Date getResolvedOn()
    {
        return this.resolvedOn;
    }

    public void setResolvedOn( Date resolvedOn )
    {
        this.resolvedOn = resolvedOn;
    }

    public boolean isEnabled()
    {
        return enabled;
    }

    public void setEnabled( boolean enabled )
    {
        this.enabled = enabled;
    }

    public boolean isStartPoint()
    {
        return startPoint;
    }

    public void setStartPoint( boolean startPoint )
    {
        this.startPoint = startPoint;
    }

    public Set<CrmMassOutageAreaPojo> getCrmMassOutageAreas()
    {
        return this.crmMassOutageAreaPojos;
    }

    public void setCrmMassOutageAreas( Set<CrmMassOutageAreaPojo> crmMassOutageAreaPojos )
    {
        this.crmMassOutageAreaPojos = crmMassOutageAreaPojos;
    }

    @Override
    public int hashCode()
    {
        final int prime = 31;
        int result = 1;
        result = prime * result + (int) ( cityId ^ ( cityId >>> 32 ) );
        return result;
    }

    @Override
    public boolean equals( Object obj )
    {
        if ( this == obj )
            return true;
        if ( obj == null )
            return false;
        if ( getClass() != obj.getClass() )
            return false;
        CrmMassOutageCityPojo other = (CrmMassOutageCityPojo) obj;
        if ( cityId != other.cityId )
            return false;
        return true;
    }
}
