package com.np.tele.crm.pojos;

// Generated 8 May, 2015 3:13:44 PM by Hibernate Tools 4.3.1
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CrmMassOutageLocalityPojo generated by hbm2java
 */
public class CrmMassOutageLocalityPojo
    implements java.io.Serializable
{
    private static final long             serialVersionUID          = 2824520958465095712L;
    private long                          recordId;
    private long                          outageId;
    private long                          outageAreaId;
    private long                          localityId;
    private String                        locality;
    private String                        resolvedBy;
    private Date                          resolvedOn;
    private boolean                       enabled;
    private boolean                       startPoint;
    private Set<CrmMassOutageSocietyPojo> crmMassOutageSocietyPojos = new HashSet<CrmMassOutageSocietyPojo>( 0 );

    public CrmMassOutageLocalityPojo()
    {
    }

    public long getRecordId()
    {
        return recordId;
    }

    public void setRecordId( long recordId )
    {
        this.recordId = recordId;
    }

    public long getOutageId()
    {
        return outageId;
    }

    public void setOutageId( long outageId )
    {
        this.outageId = outageId;
    }

    public long getOutageAreaId()
    {
        return outageAreaId;
    }

    public void setOutageAreaId( long outageAreaId )
    {
        this.outageAreaId = outageAreaId;
    }

    public long getLocalityId()
    {
        return localityId;
    }

    public void setLocalityId( long localityId )
    {
        this.localityId = localityId;
    }

    public String getLocality()
    {
        return this.locality;
    }

    public void setLocality( String locality )
    {
        this.locality = locality;
    }

    public String getResolvedBy()
    {
        return this.resolvedBy;
    }

    public void setResolvedBy( String resolvedBy )
    {
        this.resolvedBy = resolvedBy;
    }

    public Date getResolvedOn()
    {
        return this.resolvedOn;
    }

    public void setResolvedOn( Date resolvedOn )
    {
        this.resolvedOn = resolvedOn;
    }

    public boolean isEnabled()
    {
        return enabled;
    }

    public void setEnabled( boolean enabled )
    {
        this.enabled = enabled;
    }

    public boolean isStartPoint()
    {
        return startPoint;
    }

    public void setStartPoint( boolean startPoint )
    {
        this.startPoint = startPoint;
    }

    public Set<CrmMassOutageSocietyPojo> getCrmMassOutageSocieties()
    {
        return this.crmMassOutageSocietyPojos;
    }

    public void setCrmMassOutageSocieties( Set<CrmMassOutageSocietyPojo> crmMassOutageSocietyPojos )
    {
        this.crmMassOutageSocietyPojos = crmMassOutageSocietyPojos;
    }

    @Override
    public int hashCode()
    {
        final int prime = 31;
        int result = 1;
        result = prime * result + (int) ( localityId ^ ( localityId >>> 32 ) );
        return result;
    }

    @Override
    public boolean equals( Object obj )
    {
        if ( this == obj )
            return true;
        if ( obj == null )
            return false;
        if ( getClass() != obj.getClass() )
            return false;
        CrmMassOutageLocalityPojo other = (CrmMassOutageLocalityPojo) obj;
        if ( localityId != other.localityId )
            return false;
        return true;
    }
}
