package com.np.tele.crm.pojos;

// Generated 8 May, 2015 3:13:44 PM by Hibernate Tools 4.3.1
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CrmMassOutageAreaPojo generated by hbm2java
 */
public class CrmMassOutageAreaPojo
    implements java.io.Serializable
{
    private static final long             serialVersionUID          = -1227369068777786615L;
    private long                          recordId;
    private long                          outageId;
    private long                          outageCityId;
    private long                          areaId;
    private String                        area;
    private String                        resolvedBy;
    private Date                          resolvedOn;
    private boolean                       enabled;
    private boolean                       startPoint;
    //    private Set<CrmMassOutageLocalityPojo> crmMassOutageLocalityPojos = new HashSet<CrmMassOutageLocalityPojo>( 0 );
    private Set<CrmMassOutageSocietyPojo> crmMassOutageSocietyPojos = new HashSet<CrmMassOutageSocietyPojo>( 0 );

    public CrmMassOutageAreaPojo()
    {
    }

    public long getRecordId()
    {
        return recordId;
    }

    public void setRecordId( long recordId )
    {
        this.recordId = recordId;
    }

    //    public Set<CrmMassOutageLocalityPojo> getCrmMassOutageLocalityPojos()
    //    {
    //        return crmMassOutageLocalityPojos;
    //    }
    //
    //    public void setCrmMassOutageLocalityPojos( Set<CrmMassOutageLocalityPojo> crmMassOutageLocalityPojos )
    //    {
    //        this.crmMassOutageLocalityPojos = crmMassOutageLocalityPojos;
    //    }
    public long getOutageId()
    {
        return outageId;
    }

    public void setOutageId( long outageId )
    {
        this.outageId = outageId;
    }

    public long getOutageCityId()
    {
        return outageCityId;
    }

    public void setOutageCityId( long outageCityId )
    {
        this.outageCityId = outageCityId;
    }

    public long getAreaId()
    {
        return areaId;
    }

    public void setAreaId( long areaId )
    {
        this.areaId = areaId;
    }

    public void setAreaId( int areaId )
    {
        this.areaId = areaId;
    }

    public String getArea()
    {
        return this.area;
    }

    public void setArea( String area )
    {
        this.area = area;
    }

    public String getResolvedBy()
    {
        return this.resolvedBy;
    }

    public void setResolvedBy( String resolvedBy )
    {
        this.resolvedBy = resolvedBy;
    }

    public Date getResolvedOn()
    {
        return this.resolvedOn;
    }

    public void setResolvedOn( Date resolvedOn )
    {
        this.resolvedOn = resolvedOn;
    }

    public boolean isEnabled()
    {
        return enabled;
    }

    public void setEnabled( boolean enabled )
    {
        this.enabled = enabled;
    }

    public boolean isStartPoint()
    {
        return startPoint;
    }

    public void setStartPoint( boolean startPoint )
    {
        this.startPoint = startPoint;
    }

    //    public Set<CrmMassOutageLocalityPojo> getCrmMassOutageLocalities()
    //    {
    //        return this.crmMassOutageLocalityPojos;
    //    }
    //
    //    public void setCrmMassOutageLocalities( Set<CrmMassOutageLocalityPojo> crmMassOutageLocalityPojos )
    //    {
    //        this.crmMassOutageLocalityPojos = crmMassOutageLocalityPojos;
    //    }
    public Set<CrmMassOutageSocietyPojo> getCrmMassOutageSocietyPojos()
    {
        return crmMassOutageSocietyPojos;
    }

    public void setCrmMassOutageSocietyPojos( Set<CrmMassOutageSocietyPojo> crmMassOutageSocietyPojos )
    {
        this.crmMassOutageSocietyPojos = crmMassOutageSocietyPojos;
    }

    @Override
    public int hashCode()
    {
        final int prime = 31;
        int result = 1;
        result = prime * result + (int) ( areaId ^ ( areaId >>> 32 ) );
        return result;
    }

    @Override
    public boolean equals( Object obj )
    {
        if ( this == obj )
            return true;
        if ( obj == null )
            return false;
        if ( getClass() != obj.getClass() )
            return false;
        CrmMassOutageAreaPojo other = (CrmMassOutageAreaPojo) obj;
        if ( areaId != other.areaId )
            return false;
        return true;
    }
}
