package com.np.tele.crm.pojos;

// default package
// Generated Jul 22, 2016 11:38:05 AM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

/**
 * CrmNpMobile generated by hbm2java
 */
public class CrmNpMobilePojo
    implements java.io.Serializable
{
    private long    recordId;
    private long    npId;
    private long    mobileNo;
    private String  createdBy;
    private Date    createdTime;
    private String  lastModifiedBy;
    private Date    lastModifiedTime;
    private String  status;
    private boolean editable;
    private String  emailId;
    private Long    eventId;
    private String  genericType;

    public CrmNpMobilePojo()
    {
    }

    public CrmNpMobilePojo( long npId, long mobileNo, String createdBy, Date createdTime, Date lastModifiedTime )
    {
        this.npId = npId;
        this.mobileNo = mobileNo;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.lastModifiedTime = lastModifiedTime;
    }

    public CrmNpMobilePojo( long npId,
                            long mobileNo,
                            String createdBy,
                            Date createdTime,
                            String lastModifiedBy,
                            Date lastModifiedTime,
                            String status )
    {
        this.npId = npId;
        this.mobileNo = mobileNo;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
        this.status = status;
    }

    public long getRecordId()
    {
        return this.recordId;
    }

    public void setRecordId( long recordId )
    {
        this.recordId = recordId;
    }

    public long getNpId()
    {
        return this.npId;
    }

    public void setNpId( long npId )
    {
        this.npId = npId;
    }

    public long getMobileNo()
    {
        return this.mobileNo;
    }

    public void setMobileNo( long mobileNo )
    {
        this.mobileNo = mobileNo;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date createdTime )
    {
        this.createdTime = createdTime;
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date lastModifiedTime )
    {
        this.lastModifiedTime = lastModifiedTime;
    }

    public String getStatus()
    {
        return this.status;
    }

    public void setStatus( String status )
    {
        this.status = status;
    }

    public boolean isEditable()
    {
        return editable;
    }

    public void setEditable( boolean inEditable )
    {
        editable = inEditable;
    }

    public String getEmailId()
    {
        return emailId;
    }

    public void setEmailId( String inEmailId )
    {
        emailId = inEmailId;
    }

    public String getGenericType()
    {
        return genericType;
    }

    public void setGenericType( String inGenericType )
    {
        genericType = inGenericType;
    }

    public Long getEventId()
    {
        return eventId;
    }

    public void setEventId( Long inEventId )
    {
        eventId = inEventId;
    }
}
