package com.np.tele.crm.pojos;

// default package
// Generated Oct 16, 2013 12:03:19 PM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

import com.np.tele.crm.utils.StringUtils;

/**
 * CrmNationalityDetailsPojo generated by hbm2java
 */
public class CrmNationalityDetailsPojo
    implements java.io.Serializable
{
    private long    recordId;
    private long    customerRecordId;
    private String  passportNo;
    private Date    passportValidity;
    private String  visaType;
    private Date    visaValidity;
    private String  localCpFname;
    private String  localCpLname;
    private long    localCpMobileNo;
    private String  localCpAdd;
    private String  localCpLandmark;
    private String  createdBy;
    private Date    createdTime;
    private String  lastModifiedBy;
    private Date    lastModifiedTime;
    private String  displayCreatedTime;
    private String  displayLastModifiedTime;
    private String  displayVisaValidity;
    private String  displayPassportValidity;
    private String  addLine1;
    private String  addLine2;
    private String  addLine3;
    private Integer pincode;
    private String  state;
    private String  city;
    private String  nationality;

    public CrmNationalityDetailsPojo()
    {
    }

    public CrmNationalityDetailsPojo( Long recordId, String createdBy )
    {
        this.recordId = recordId;
        this.createdBy = createdBy;
    }

    public CrmNationalityDetailsPojo( Long recordId,
                                      Long customerRecordId,
                                      String passportNo,
                                      Date passportValidity,
                                      String visaType,
                                      Date visaValidity,
                                      String localCpFname,
                                      String localCpLname,
                                      long localCpMobileNo,
                                      String localCpAdd,
                                      String localCpLandmark,
                                      String createdBy,
                                      Date createdTime,
                                      String lastModifiedBy,
                                      Date lastModifiedTime )
    {
        this.recordId = recordId;
        this.customerRecordId = customerRecordId;
        this.passportNo = passportNo;
        this.passportValidity = passportValidity;
        this.visaType = visaType;
        this.visaValidity = visaValidity;
        this.localCpFname = localCpFname;
        this.localCpLname = localCpLname;
        this.localCpMobileNo = localCpMobileNo;
        this.localCpAdd = localCpAdd;
        this.localCpLandmark = localCpLandmark;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
    }

    public long getRecordId()
    {
        return recordId;
    }

    public void setRecordId( long recordId )
    {
        this.recordId = recordId;
    }

    public long getCustomerRecordId()
    {
        return customerRecordId;
    }

    public void setCustomerRecordId( long customerRecordId )
    {
        this.customerRecordId = customerRecordId;
    }

    public Integer getPincode()
    {
        return pincode;
    }

    public void setPincode( Integer pincode )
    {
        this.pincode = pincode;
    }

    public String getPassportNo()
    {
        return this.passportNo;
    }

    public void setPassportNo( String passportNo )
    {
        this.passportNo = passportNo;
    }

    public Date getPassportValidity()
    {
        return this.passportValidity;
    }

    public void setPassportValidity( Date passportValidity )
    {
        this.passportValidity = passportValidity;
        /* if ( StringUtils.isEmpty( displayPassportValidity ) && StringUtils.isValidObj( passportValidity ) )
         {
             displayPassportValidity = IDateConstants.SDF_DD_MMM_YYYY.format( passportValidity );
         }*/
    }

    public String getVisaType()
    {
        return this.visaType;
    }

    public void setVisaType( String visaType )
    {
        this.visaType = visaType;
    }

    public Date getVisaValidity()
    {
        return this.visaValidity;
    }

    public void setVisaValidity( Date visaValidity )
    {
        this.visaValidity = visaValidity;
        /* if ( StringUtils.isEmpty( displayVisaValidity ) && StringUtils.isValidObj( visaValidity ) )
         {
             displayVisaValidity = IDateConstants.SDF_DD_MMM_YYYY.format( visaValidity );
         }*/
    }

    public String getLocalCpFname()
    {
        return this.localCpFname;
    }

    public void setLocalCpFname( String localCpFname )
    {
        this.localCpFname = StringUtils.upperCase( localCpFname );
    }

    public String getLocalCpLname()
    {
        return this.localCpLname;
    }

    public void setLocalCpLname( String localCpLname )
    {
        this.localCpLname = StringUtils.upperCase( localCpLname );
    }

    public long getLocalCpMobileNo()
    {
        return this.localCpMobileNo;
    }

    public void setLocalCpMobileNo( long localCpMobileNo )
    {
        this.localCpMobileNo = localCpMobileNo;
    }

    public String getLocalCpAdd()
    {
        return this.localCpAdd;
    }

    public void setLocalCpAdd( String localCpAdd )
    {
        this.localCpAdd = StringUtils.upperCase( localCpAdd );
    }

    public String getLocalCpLandmark()
    {
        return this.localCpLandmark;
    }

    public void setLocalCpLandmark( String localCpLandmark )
    {
        this.localCpLandmark = StringUtils.upperCase( localCpLandmark );
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date createdTime )
    {
        this.createdTime = createdTime;
        /* if ( StringUtils.isEmpty( displayCreatedTime ) && StringUtils.isValidObj( createdTime ) )
         {
             displayCreatedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( createdTime );
         }*/
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date lastModifiedTime )
    {
        this.lastModifiedTime = lastModifiedTime;
        /* if ( StringUtils.isEmpty( displayLastModifiedTime ) && StringUtils.isValidObj( lastModifiedTime ) )
         {
             displayLastModifiedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( lastModifiedTime );
         }*/
    }

    public String getDisplayCreatedTime()
    {
        return displayCreatedTime;
    }

    public void setDisplayCreatedTime( String displayCreatedTime )
    {
        this.displayCreatedTime = displayCreatedTime;
    }

    public String getDisplayLastModifiedTime()
    {
        return displayLastModifiedTime;
    }

    public void setDisplayLastModifiedTime( String displayLastModifiedTime )
    {
        this.displayLastModifiedTime = displayLastModifiedTime;
    }

    public String getDisplayPassportValidity()
    {
        return displayPassportValidity;
    }

    public void setDisplayPassportValidity( String displayPassportValidity )
    {
        this.displayPassportValidity = displayPassportValidity;
    }

    public String getDisplayVisaValidity()
    {
        return displayVisaValidity;
    }

    public void setDisplayVisaValidity( String displayVisaValidity )
    {
        this.displayVisaValidity = displayVisaValidity;
    }

    public String getAddLine1()
    {
        return addLine1;
    }

    public void setAddLine1( String inAddLine1 )
    {
        addLine1 = inAddLine1;
    }

    public String getAddLine2()
    {
        return addLine2;
    }

    public void setAddLine2( String inAddLine2 )
    {
        addLine2 = inAddLine2;
    }

    public String getAddLine3()
    {
        return addLine3;
    }

    public void setAddLine3( String inAddLine3 )
    {
        addLine3 = inAddLine3;
    }

    public String getState()
    {
        return state;
    }

    public void setState( String inState )
    {
        state = inState;
    }

    public String getCity()
    {
        return city;
    }

    public void setCity( String inCity )
    {
        city = inCity;
    }

    public String getNationality()
    {
        return nationality;
    }

    public void setNationality( String inNationality )
    {
        nationality = inNationality;
    }
}
