package com.np.tele.crm.pojos;

// Generated 27 Sep, 2013 3:52:26 PM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

/**
 * CrmPartnerMappingPojo generated by hbm2java
 */
public class CrmPartnerMappingPojo
    implements java.io.Serializable
{
    private long        recordId;
    private PartnerPojo partnerByNpId;
    private PartnerPojo partnerBySpId;
    private String      createdBy;
    private Date        createdTime;
    private String      lastModifiedBy;
    private Date        lastModifiedTime;
    private String      status;
    private boolean     editable;
    private String      displayCreatedTime;
    private String      displayLastModifiedTime;
    private String      product;

    public CrmPartnerMappingPojo()
    {
    }

    public CrmPartnerMappingPojo( Long recordId, PartnerPojo partnerByNpId, PartnerPojo partnerBySpId, String createdBy )
    {
        this.recordId = recordId;
        this.partnerByNpId = partnerByNpId;
        this.partnerBySpId = partnerBySpId;
        this.createdBy = createdBy;
    }

    public CrmPartnerMappingPojo( Long recordId,
                                  PartnerPojo partnerByNpId,
                                  PartnerPojo partnerBySpId,
                                  String createdBy,
                                  Date createdTime,
                                  String lastModifiedBy,
                                  Date lastModifiedTime,
                                  String status )
    {
        this.recordId = recordId;
        this.partnerByNpId = partnerByNpId;
        this.partnerBySpId = partnerBySpId;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
        this.status = status;
    }

    public long getRecordId()
    {
        return recordId;
    }

    public void setRecordId( long recordId )
    {
        this.recordId = recordId;
    }

    public PartnerPojo getPartnerByNpId()
    {
        return this.partnerByNpId;
    }

    public void setPartnerByNpId( PartnerPojo partnerByNpId )
    {
        this.partnerByNpId = partnerByNpId;
    }

    public PartnerPojo getPartnerBySpId()
    {
        return this.partnerBySpId;
    }

    public void setPartnerBySpId( PartnerPojo partnerBySpId )
    {
        this.partnerBySpId = partnerBySpId;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date inCreatedTime )
    {
        createdTime = inCreatedTime;
       /* if ( StringUtils.isEmpty( displayCreatedTime ) && StringUtils.isValidObj( createdTime ) )
        {
            displayCreatedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( createdTime );
        }*/
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date inLastModifiedTime )
    {
        lastModifiedTime = inLastModifiedTime;
       /* if ( StringUtils.isEmpty( displayLastModifiedTime ) && StringUtils.isValidObj( lastModifiedTime ) )
        {
            displayLastModifiedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( lastModifiedTime );
        }*/
    }

    public String getStatus()
    {
        return this.status;
    }

    public void setStatus( String status )
    {
        this.status = status;
    }

    public boolean isEditable()
    {
        return editable;
    }

    public void setEditable( boolean inEditable )
    {
        editable = inEditable;
    }

    public String getDisplayCreatedTime()
    {
        return displayCreatedTime;
    }

    public void setDisplayCreatedTime( String inDisplayCreatedTime )
    {
        displayCreatedTime = inDisplayCreatedTime;
    }

    public String getDisplayLastModifiedTime()
    {
        return displayLastModifiedTime;
    }

    public void setDisplayLastModifiedTime( String inDisplayLastModifiedTime )
    {
        displayLastModifiedTime = inDisplayLastModifiedTime;
    }

    public String getProduct()
    {
        return product;
    }

    public void setProduct( String product )
    {
        this.product = product;
    }
}
