package com.np.tele.crm.pojos;

// default package
// Generated Oct 16, 2013 12:03:19 PM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

import javax.xml.bind.annotation.XmlTransient;

/**
 * CrmPlanDetailsPojo generated by hbm2java
 */
public class CrmPlanDetailsPojo
    implements java.io.Serializable
{
    private long                   recordId;
    private CrmCustomerDetailsPojo crmCustomerDetails;
    private String                 basePlanCode;
    private String                 addOnPlanCode;
    private String                 promoCode;
    private String                 preferredBillLang;
    private String                 usageType;
    private String                 billMode;
    private String                 createdBy;
    private Date                   createdTime;
    private String                 lastModifiedBy;
    private Date                   lastModifiedTime;
    private String                 displayCreatedTime;
    private String                 displayLastModifiedTime;

    public CrmPlanDetailsPojo()
    {
    }

    public CrmPlanDetailsPojo( Long recordId, String createdBy )
    {
        this.recordId = recordId;
        this.createdBy = createdBy;
    }

    public CrmPlanDetailsPojo( Long recordId,
                               CrmCustomerDetailsPojo crmCustomerDetailsPojo,
                               String basePlanName,
                               String addOnPlanName,
                               String promoCode,
                               String preferredBillLang,
                               String usageType,
                               String billMode,
                               String createdBy,
                               Date createdTime,
                               String lastModifiedBy,
                               Date lastModifiedTime )
    {
        this.recordId = recordId;
        this.crmCustomerDetails = crmCustomerDetailsPojo;
        this.basePlanCode = basePlanName;
        this.addOnPlanCode = addOnPlanName;
        this.promoCode = promoCode;
        this.preferredBillLang = preferredBillLang;
        this.usageType = usageType;
        this.billMode = billMode;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
    }

    public long getRecordId()
    {
        return recordId;
    }

    public void setRecordId( long recordId )
    {
        this.recordId = recordId;
    }

    @XmlTransient
    public CrmCustomerDetailsPojo getCrmCustomerDetails()
    {
        return this.crmCustomerDetails;
    }

    public void setCrmCustomerDetails( CrmCustomerDetailsPojo crmCustomerDetailsPojo )
    {
        this.crmCustomerDetails = crmCustomerDetailsPojo;
    }

    public String getBasePlanCode()
    {
        return this.basePlanCode;
    }

    public void setBasePlanCode( String basePlanName )
    {
        this.basePlanCode = basePlanName;
    }

    public String getAddOnPlanCode()
    {
        return this.addOnPlanCode;
    }

    public void setAddOnPlanCode( String addOnPlanName )
    {
        this.addOnPlanCode = addOnPlanName;
    }

    public String getPromoCode()
    {
        return this.promoCode;
    }

    public void setPromoCode( String promoCode )
    {
        this.promoCode = promoCode;
    }

    public String getPreferredBillLang()
    {
        return this.preferredBillLang;
    }

    public void setPreferredBillLang( String preferredBillLang )
    {
        this.preferredBillLang = preferredBillLang;
    }

    public String getUsageType()
    {
        return this.usageType;
    }

    public void setUsageType( String usageType )
    {
        this.usageType = usageType;
    }

    public String getBillMode()
    {
        return this.billMode;
    }

    public void setBillMode( String billMode )
    {
        this.billMode = billMode;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date createdTime )
    {
        this.createdTime = createdTime;
        /* if ( StringUtils.isEmpty( displayCreatedTime ) && StringUtils.isValidObj( createdTime ) )
         {
             displayCreatedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( createdTime );
         }*/
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date lastModifiedTime )
    {
        this.lastModifiedTime = lastModifiedTime;
        /*if ( StringUtils.isEmpty( displayLastModifiedTime ) && StringUtils.isValidObj( lastModifiedTime ) )
        {
            displayLastModifiedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( lastModifiedTime );
        }*/
    }

    public String getDisplayCreatedTime()
    {
        return displayCreatedTime;
    }

    public void setDisplayCreatedTime( String displayCreatedTime )
    {
        this.displayCreatedTime = displayCreatedTime;
    }

    public String getDisplayLastModifiedTime()
    {
        return displayLastModifiedTime;
    }

    public void setDisplayLastModifiedTime( String displayLastModifiedTime )
    {
        this.displayLastModifiedTime = displayLastModifiedTime;
    }
}
