package com.np.tele.crm.pojos;

// Generated Dec 2, 2013 5:15:16 PM by Hibernate Tools 3.4.0.CR1
import java.math.BigDecimal;
import java.util.Date;

import javax.xml.bind.annotation.XmlTransient;

import com.np.tele.crm.constants.IDateConstants;
import com.np.tele.crm.utils.StringUtils;

/**
 * CrmPaymentDetails generated by hbm2java
 */
public class CrmPaymentDetailsPojo
    implements java.io.Serializable
{
    private long                   paymentId;
    private long                   customerRecordId;
    private String                 entityType;
    private double                 registrationCharges;
    private double                 activationCharges;
    private double                 securityCharges;
    //    private BigDecimal             otherCharges;
    //    private BigDecimal             cpeCharges;
    //    private BigDecimal             wiFiCharges;
    //    private BigDecimal             wiringCharges;
    private String                 paymentMode;
    private String                 chequeDdNo;
    private String                 bankName;
    private String                 bankBranch;
    private Date                   chequeDate;
    private String                 bankCity;
    private String                 receiptNo;
    private String                 transactionId;
    private String                 createdBy;
    private Date                   createdTime;
    private String                 lastModifiedBy;
    private Date                   lastModifiedTime;
    private Date                   paymentDate;
    private String                 paymentChannel;
    private double                 amount;
    private String                 paymentStatus;
    private String                 realzationStatus;
    private String                 caseStatus;
    private Date                   bouncingDate;
    private String                 bouncingReason;
    private String                 reversalReason;
    private Date                   reversalDate;
    private String                 installationStatus;
    private String                 status;
    private String                 displayChequeDate;
    private CrmCustomerDetailsPojo customerDetailsPojo = null;
    private boolean                editable            = false;
    private String                 customerId          = null;
    private String                 crfId               = null;
    private String                 serviceType         = null;
    private String                 srId                = null;
    private Long                   cmsId;
    private String                 refTransId          = null;
    private String                 bankTransId         = null;
    private String                 pgwTransId          = null;
    private Date                   postingDate;
    private BigDecimal             deposit;

    public BigDecimal getDeposit()
    {
        return deposit;
    }

    public void setDeposit( BigDecimal deposit )
    {
        this.deposit = deposit;
    }

    public CrmPaymentDetailsPojo()
    {
    }

    public CrmPaymentDetailsPojo( Long paymentId, String createdBy )
    {
        this.paymentId = paymentId;
        this.createdBy = createdBy;
    }

    public CrmPaymentDetailsPojo( Long paymentId,
                                  long customerRecordId,
                                  String entityType,
                                  double registrationCharges,
                                  double activationCharges,
                                  double securityCharges,
                                  BigDecimal otherCharges,
                                  BigDecimal cpeCharges,
                                  BigDecimal wiFiCharges,
                                  BigDecimal wiringCharges,
                                  String paymentMode,
                                  String chequeDdNo,
                                  String bankName,
                                  String bankBranch,
                                  Date chequeDate,
                                  String bankCity,
                                  String receiptNo,
                                  String transactionId,
                                  String createdBy,
                                  Date createdTime,
                                  String lastModifiedBy,
                                  Date lastModifiedTime,
                                  Date paymentDate,
                                  String paymentChannel,
                                  double amount,
                                  String paymentStatus,
                                  String realzationStatus,
                                  String caseStatus,
                                  Date bouncingDate,
                                  String bouncingReason,
                                  String reversalReason,
                                  String installationStatus,
                                  String status )
    {
        this.paymentId = paymentId;
        this.customerRecordId = customerRecordId;
        this.entityType = entityType;
        //        this.registrationCharges = registrationCharges;
        this.activationCharges = activationCharges;
        this.securityCharges = securityCharges;
        //        this.otherCharges = otherCharges;
        //        this.cpeCharges = cpeCharges;
        //        this.wiFiCharges = wiFiCharges;
        //        this.wiringCharges = wiringCharges;
        this.paymentMode = paymentMode;
        this.chequeDdNo = chequeDdNo;
        this.bankName = bankName;
        this.bankBranch = bankBranch;
        this.chequeDate = chequeDate;
        this.bankCity = bankCity;
        this.receiptNo = receiptNo;
        this.transactionId = transactionId;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
        this.paymentDate = paymentDate;
        this.paymentChannel = paymentChannel;
        this.amount = amount;
        this.paymentStatus = paymentStatus;
        this.realzationStatus = realzationStatus;
        this.caseStatus = caseStatus;
        this.bouncingDate = bouncingDate;
        this.bouncingReason = bouncingReason;
        this.reversalReason = reversalReason;
        this.installationStatus = installationStatus;
        this.status = status;
    }

    public long getPaymentId()
    {
        return paymentId;
    }

    public void setPaymentId( long paymentId )
    {
        this.paymentId = paymentId;
    }

    public long getCustomerRecordId()
    {
        return customerRecordId;
    }

    public void setCustomerRecordId( long customerRecordId )
    {
        this.customerRecordId = customerRecordId;
    }

    public double getRegistrationCharges()
    {
        return registrationCharges;
    }

    public void setRegistrationCharges( double registrationCharges )
    {
        this.registrationCharges = registrationCharges;
    }

    public double getActivationCharges()
    {
        return activationCharges;
    }

    public void setActivationCharges( double activationCharges )
    {
        this.activationCharges = activationCharges;
    }

    public double getSecurityCharges()
    {
        return securityCharges;
    }

    public void setSecurityCharges( double securityCharges )
    {
        this.securityCharges = securityCharges;
    }

    public double getAmount()
    {
        return amount;
    }

    public void setAmount( double amount )
    {
        this.amount = amount;
    }

    public String getEntityType()
    {
        return this.entityType;
    }

    public void setEntityType( String entityType )
    {
        this.entityType = entityType;
    }

    //    public BigDecimal getRegistrationCharges()
    //    {
    //        return this.registrationCharges;
    //    }
    //
    //    public void setRegistrationCharges( BigDecimal registrationCharges )
    //    {
    //        this.registrationCharges = registrationCharges;
    //    }
    //    public BigDecimal getOtherCharges()
    //    {
    //        return this.otherCharges;
    //    }
    //
    //    public void setOtherCharges( BigDecimal otherCharges )
    //    {
    //        this.otherCharges = otherCharges;
    //    }
    //
    //    public BigDecimal getCpeCharges()
    //    {
    //        return this.cpeCharges;
    //    }
    //
    //    public void setCpeCharges( BigDecimal cpeCharges )
    //    {
    //        this.cpeCharges = cpeCharges;
    //    }
    //
    //    public BigDecimal getWiFiCharges()
    //    {
    //        return this.wiFiCharges;
    //    }
    //
    //    public void setWiFiCharges( BigDecimal wiFiCharges )
    //    {
    //        this.wiFiCharges = wiFiCharges;
    //    }
    //
    //    public BigDecimal getWiringCharges()
    //    {
    //        return this.wiringCharges;
    //    }
    //
    //    public void setWiringCharges( BigDecimal wiringCharges )
    //    {
    //        this.wiringCharges = wiringCharges;
    //    }
    public String getPaymentMode()
    {
        return this.paymentMode;
    }

    public void setPaymentMode( String paymentMode )
    {
        this.paymentMode = paymentMode;
    }

    public String getChequeDdNo()
    {
        return this.chequeDdNo;
    }

    public void setChequeDdNo( String chequeDdNo )
    {
        this.chequeDdNo = chequeDdNo;
    }

    public String getBankName()
    {
        return this.bankName;
    }

    public void setBankName( String bankName )
    {
        this.bankName = bankName;
    }

    public String getBankBranch()
    {
        return this.bankBranch;
    }

    public void setBankBranch( String bankBranch )
    {
        this.bankBranch = bankBranch;
    }

    public Date getChequeDate()
    {
        return this.chequeDate;
    }

    public void setChequeDate( Date chequeDate )
    {
        this.chequeDate = chequeDate;
        if ( StringUtils.isEmpty( displayChequeDate ) && StringUtils.isValidObj( chequeDate ) )
        {
            displayChequeDate = IDateConstants.SDF_DD_MMM_YYYY.format( chequeDate );
        }
    }

    public String getBankCity()
    {
        return this.bankCity;
    }

    public void setBankCity( String bankCity )
    {
        this.bankCity = bankCity;
    }

    public String getReceiptNo()
    {
        return this.receiptNo;
    }

    public void setReceiptNo( String receiptNo )
    {
        this.receiptNo = receiptNo;
    }

    public String getTransactionId()
    {
        return this.transactionId;
    }

    public void setTransactionId( String transactionId )
    {
        this.transactionId = transactionId;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date createdTime )
    {
        this.createdTime = createdTime;
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date lastModifiedTime )
    {
        this.lastModifiedTime = lastModifiedTime;
    }

    public Date getPaymentDate()
    {
        return this.paymentDate;
    }

    public void setPaymentDate( Date paymentDate )
    {
        this.paymentDate = paymentDate;
    }

    public String getPaymentChannel()
    {
        return this.paymentChannel;
    }

    public void setPaymentChannel( String paymentChannel )
    {
        this.paymentChannel = paymentChannel;
    }

    public String getPaymentStatus()
    {
        return this.paymentStatus;
    }

    public void setPaymentStatus( String paymentStatus )
    {
        this.paymentStatus = paymentStatus;
    }

    public String getRealzationStatus()
    {
        return this.realzationStatus;
    }

    public void setRealzationStatus( String realzationStatus )
    {
        this.realzationStatus = realzationStatus;
    }

    public String getCaseStatus()
    {
        return this.caseStatus;
    }

    public void setCaseStatus( String caseStatus )
    {
        this.caseStatus = caseStatus;
    }

    public Date getBouncingDate()
    {
        return this.bouncingDate;
    }

    public void setBouncingDate( Date bouncingDate )
    {
        this.bouncingDate = bouncingDate;
    }

    public String getBouncingReason()
    {
        return this.bouncingReason;
    }

    public void setBouncingReason( String bouncingReason )
    {
        this.bouncingReason = bouncingReason;
    }

    public String getReversalReason()
    {
        return this.reversalReason;
    }

    public void setReversalReason( String reversalReason )
    {
        this.reversalReason = reversalReason;
    }

    public Date getReversalDate()
    {
        return reversalDate;
    }

    public void setReversalDate( Date inReversalDate )
    {
        reversalDate = inReversalDate;
    }

    public String getInstallationStatus()
    {
        return this.installationStatus;
    }

    public void setInstallationStatus( String installationStatus )
    {
        this.installationStatus = installationStatus;
    }

    public String getStatus()
    {
        return this.status;
    }

    public void setStatus( String status )
    {
        this.status = status;
    }

    public String getDisplayChequeDate()
    {
        return displayChequeDate;
    }

    public void setDisplayChequeDate( String inDisplayChequeDate )
    {
        displayChequeDate = inDisplayChequeDate;
    }

    @XmlTransient
    public CrmCustomerDetailsPojo getCustomerDetailsPojo()
    {
        return customerDetailsPojo;
    }

    public void setCustomerDetailsPojo( CrmCustomerDetailsPojo inCustomerDetailsPojo )
    {
        customerDetailsPojo = inCustomerDetailsPojo;
        if ( StringUtils.isValidObj( customerDetailsPojo ) )
        {
            if ( StringUtils.isBlank( customerId ) )
            {
                customerId = customerDetailsPojo.getCustomerId();
            }
            if ( StringUtils.isBlank( crfId ) )
            {
                crfId = customerDetailsPojo.getCrfId();
            }
        }
    }

    public boolean isEditable()
    {
        return editable;
    }

    public void setEditable( boolean inEditable )
    {
        editable = inEditable;
    }

    /**
     * @return the customerId
     */
    public String getCustomerId()
    {
        return customerId;
    }

    /**
     * @param inCustomerId the customerId to set
     */
    public void setCustomerId( String inCustomerId )
    {
        customerId = inCustomerId;
    }

    /**
     * @return the crfId
     */
    public String getCrfId()
    {
        return crfId;
    }

    /**
     * @param inCrfId the crfId to set
     */
    public void setCrfId( String inCrfId )
    {
        crfId = inCrfId;
    }

    /**
     * @return the serviceType
     */
    public String getServiceType()
    {
        return serviceType;
    }

    /**
     * @param inServiceType the serviceType to set
     */
    public void setServiceType( String inServiceType )
    {
        serviceType = inServiceType;
    }

    public String getSrId()
    {
        return srId;
    }

    public void setSrId( String inSrId )
    {
        srId = inSrId;
    }

    public Long getCmsId()
    {
        return cmsId;
    }

    public void setCmsId( Long inCmsId )
    {
        cmsId = inCmsId;
    }

    @XmlTransient
    public String getRefTransId()
    {
        return refTransId;
    }

    public void setRefTransId( String inRefTransId )
    {
        refTransId = inRefTransId;
    }

    public String getBankTransId()
    {
        return bankTransId;
    }

    public void setBankTransId( String inBankTransId )
    {
        bankTransId = inBankTransId;
    }

    public String getPgwTransId()
    {
        return pgwTransId;
    }

    public void setPgwTransId( String inPgwTransId )
    {
        pgwTransId = inPgwTransId;
    }

    public Date getPostingDate()
    {
        return postingDate;
    }

    public void setPostingDate( Date postingDate )
    {
        this.postingDate = postingDate;
    }

    @Override
    public String toString()
    {
        StringBuilder builder = new StringBuilder();
        builder.append( "CrmPaymentDetailsPojo [paymentId=" ).append( paymentId ).append( ", customerRecordId=" )
                .append( customerRecordId ).append( ", entityType=" ).append( entityType )
                .append( ", activationCharges=" ).append( activationCharges ).append( ", securityCharges=" )
                .append( securityCharges ).append( ", paymentMode=" ).append( paymentMode ).append( ", chequeDdNo=" )
                .append( chequeDdNo ).append( ", bankName=" ).append( bankName ).append( ", bankBranch=" )
                .append( bankBranch ).append( ", chequeDate=" ).append( chequeDate ).append( ", bankCity=" )
                .append( bankCity ).append( ", receiptNo=" ).append( receiptNo ).append( ", transactionId=" )
                .append( transactionId ).append( ", createdBy=" ).append( createdBy ).append( ", createdTime=" )
                .append( createdTime ).append( ", lastModifiedBy=" ).append( lastModifiedBy )
                .append( ", lastModifiedTime=" ).append( lastModifiedTime ).append( ", paymentDate=" )
                .append( paymentDate ).append( ", paymentChannel=" ).append( paymentChannel ).append( ", amount=" )
                .append( amount ).append( ", paymentStatus=" ).append( paymentStatus ).append( ", realzationStatus=" )
                .append( realzationStatus ).append( ", caseStatus=" ).append( caseStatus ).append( ", bouncingDate=" )
                .append( bouncingDate ).append( ", bouncingReason=" ).append( bouncingReason )
                .append( ", reversalReason=" ).append( reversalReason ).append( ", reversalDate=" )
                .append( reversalDate ).append( ", installationStatus=" ).append( installationStatus )
                .append( ", status=" ).append( status ).append( ", displayChequeDate=" ).append( displayChequeDate )
                .append( ", customerDetailsPojo=" ).append( customerDetailsPojo ).append( ", editable=" )
                .append( editable ).append( ", customerId=" ).append( customerId ).append( ", crfId=" ).append( crfId )
                .append( ", serviceType=" ).append( serviceType ).append( ", srId=" ).append( srId )
                .append( ", cmsId=" ).append( cmsId ).append( ", refTransId=" ).append( refTransId )
                .append( ", bankTransId=" ).append( bankTransId ).append( ", pgwTransId=" ).append( pgwTransId )
                .append( "]" );
        return builder.toString();
    }
}
