package com.np.tele.crm.pojos;

// default package
// Generated Mar 24, 2015 6:24:56 PM by Hibernate Tools 3.4.0.CR1
import java.io.Serializable;
import java.util.Date;

/**
 * CrmPodDetailsPojo generated by hbm2java
 */
public class CrmPodDetailsPojo
    implements Serializable
{
    private long   podId;
    private String customerId;
    private String receiverName;
    private Date   deliveredDate;
    private String customerRelation;
    private long   contactNumber;
    private String createdBy;
    private Date   createdTime;
    private String lastModifiedBy;
    private Date   lastModifiedTime;
    private String status;
    private String instrumentNumber;
    private String deliveryStatus;
    private String nonDeliveryReason;
    private String processFailureReason;

    public CrmPodDetailsPojo()
    {
    }

    public CrmPodDetailsPojo( Long podId, String status )
    {
        this.podId = podId;
        this.status = status;
    }

    public CrmPodDetailsPojo( Long podId,
                              String customerId,
                              String receiverName,
                              Date deliveredDate,
                              String customerRelation,
                              Long contactNumber,
                              String createdBy,
                              Date createdTime,
                              String lastModifiedBy,
                              Date lastModifiedTime,
                              String status )
    {
        this.podId = podId;
        this.customerId = customerId;
        this.receiverName = receiverName;
        this.deliveredDate = deliveredDate;
        this.customerRelation = customerRelation;
        this.contactNumber = contactNumber;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
        this.status = status;
    }

    public long getPodId()
    {
        return podId;
    }

    public void setPodId( long podId )
    {
        this.podId = podId;
    }

    public String getCustomerId()
    {
        return this.customerId;
    }

    public void setCustomerId( String customerId )
    {
        this.customerId = customerId;
    }

    public String getReceiverName()
    {
        return this.receiverName;
    }

    public void setReceiverName( String receiverName )
    {
        this.receiverName = receiverName;
    }

    public Date getDeliveredDate()
    {
        return this.deliveredDate;
    }

    public void setDeliveredDate( Date deliveredDate )
    {
        this.deliveredDate = deliveredDate;
    }

    public String getCustomerRelation()
    {
        return this.customerRelation;
    }

    public void setCustomerRelation( String customerRelation )
    {
        this.customerRelation = customerRelation;
    }

    public long getContactNumber()
    {
        return this.contactNumber;
    }

    public void setContactNumber( long contactNumber )
    {
        this.contactNumber = contactNumber;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date createdTime )
    {
        this.createdTime = createdTime;
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date lastModifiedTime )
    {
        this.lastModifiedTime = lastModifiedTime;
    }

    public String getStatus()
    {
        return this.status;
    }

    public void setStatus( String status )
    {
        this.status = status;
    }

    public String getInstrumentNumber()
    {
        return instrumentNumber;
    }

    public void setInstrumentNumber( String inInstrumentNumber )
    {
        instrumentNumber = inInstrumentNumber;
    }

    public String getDeliveryStatus()
    {
        return deliveryStatus;
    }

    public void setDeliveryStatus( String inDeliveryStatus )
    {
        deliveryStatus = inDeliveryStatus;
    }

    public String getNonDeliveryReason()
    {
        return nonDeliveryReason;
    }

    public void setNonDeliveryReason( String inNonDeliveryReason )
    {
        nonDeliveryReason = inNonDeliveryReason;
    }

    public String getProcessFailureReason()
    {
        return processFailureReason;
    }

    public void setProcessFailureReason( String inProcessFailureReason )
    {
        processFailureReason = inProcessFailureReason;
    }

    @Override
    public String toString()
    {
        StringBuilder builder = new StringBuilder();
        builder.append( "CrmPodDetailsPojo [podId=" ).append( podId ).append( ", customerId=" ).append( customerId )
                .append( ", receiverName=" ).append( receiverName ).append( ", deliveredDate=" ).append( deliveredDate )
                .append( ", customerRelation=" ).append( customerRelation ).append( ", contactNumber=" )
                .append( contactNumber ).append( ", createdBy=" ).append( createdBy ).append( ", createdTime=" )
                .append( createdTime ).append( ", lastModifiedBy=" ).append( lastModifiedBy )
                .append( ", lastModifiedTime=" ).append( lastModifiedTime ).append( ", status=" ).append( status )
                .append( ", instrumentNumber=" ).append( instrumentNumber ).append( ", deliveryStatus=" )
                .append( deliveryStatus ).append( ", nonDeliveryReason=" ).append( nonDeliveryReason ).append( "]" );
        return builder.toString();
    }
}
