package com.np.tele.crm.pojos;

// default package
// Generated Jun 4, 2015 3:55:18 PM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

/**
 * CrmPaymentCentresPojo generated by hbm2java
 */
public class CrmPaymentCentresPojo
    implements java.io.Serializable
{
    private long   recordId;
    private String vendorName;
    private String outletAddress;
    private String outletCity;
    private String paymentMode;
    private String pincode;
    private String createdBy;
    private Date   createdTime;
    private String status;

    public CrmPaymentCentresPojo()
    {
    }

    public CrmPaymentCentresPojo( Long recordId,
                                  String vendorName,
                                  String outletAddress,
                                  String paymentMode,
                                  String pincode,
                                  String createdBy )
    {
        this.recordId = recordId;
        this.vendorName = vendorName;
        this.outletAddress = outletAddress;
        this.paymentMode = paymentMode;
        this.pincode = pincode;
        this.createdBy = createdBy;
    }

    public CrmPaymentCentresPojo( Long recordId,
                                  String vendorName,
                                  String outletAddress,
                                  String outletCity,
                                  String paymentMode,
                                  String pincode,
                                  String createdBy,
                                  Date createdTime,
                                  String status )
    {
        this.recordId = recordId;
        this.vendorName = vendorName;
        this.outletAddress = outletAddress;
        this.outletCity = outletCity;
        this.paymentMode = paymentMode;
        this.pincode = pincode;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.status = status;
    }

    public long getRecordId()
    {
        return recordId;
    }

    public void setRecordId( long recordId )
    {
        this.recordId = recordId;
    }

    public String getVendorName()
    {
        return this.vendorName;
    }

    public void setVendorName( String vendorName )
    {
        this.vendorName = vendorName;
    }

    public String getOutletAddress()
    {
        return this.outletAddress;
    }

    public void setOutletAddress( String outletAddress )
    {
        this.outletAddress = outletAddress;
    }

    public String getOutletCity()
    {
        return this.outletCity;
    }

    public void setOutletCity( String outletCity )
    {
        this.outletCity = outletCity;
    }

    public String getPaymentMode()
    {
        return this.paymentMode;
    }

    public void setPaymentMode( String paymentMode )
    {
        this.paymentMode = paymentMode;
    }

    public String getPincode()
    {
        return this.pincode;
    }

    public void setPincode( String pincode )
    {
        this.pincode = pincode;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date createdTime )
    {
        this.createdTime = createdTime;
    }

    public String getStatus()
    {
        return this.status;
    }

    public void setStatus( String status )
    {
        this.status = status;
    }

    @Override
    public String toString()
    {
        StringBuilder builder = new StringBuilder();
        builder.append( "CrmPaymentCentresPojo [recordId=" ).append( recordId ).append( ", vendorName=" )
                .append( vendorName ).append( ", outletAddress=" ).append( outletAddress ).append( ", outletCity=" )
                .append( outletCity ).append( ", paymentMode=" ).append( paymentMode ).append( ", pincode=" )
                .append( pincode ).append( ", status=" ).append( status ).append( "]" );
        return builder.toString();
    }
}
