package com.np.tele.crm.pojos;

// default package
// Generated Dec 26, 2014 11:23:52 AM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

/**
 * CrmPgwTransactionsPojo generated by hbm2java
 */
public class CrmPgwTransactionsPojo
    implements java.io.Serializable
{
    private double amount;
    private String customerId;
    private Date   initiationDatetime;
    private String paymentOption;
    private String pgwAuthCode;          //Auth Code
    private Date   pgwAuthDatetime;
    private String pgwAvr;               //TRANSACTION avr
    private String pgwErrorCode;         //Error Number
    private String pgwErrorMsg;          //Error Text/message
    private String pgwName;
    private String pgwPaymentId;
    private String pgwPaymentPage;
    private String pgwPostdate;          //Postdate
    private String pgwReferenceNumber;   //Reference Number also called Seq Number
    private Date   pgwResponseDatetime;
    private String pgwResult;            //Transaction Result
    private String pgwTrackId;
    private String pgwTransactionId;     //Transaction ID
    private Long   recordId;
    private String redirectUrl;
    private String status;
    private String udf1           = "";
    private String udf2           = "";
    private String udf3           = "";
    private String udf4           = "";
    private String udf5           = "";
    private String paymentReciept = null;
    private String billingPaymentStatus;
    private String appReturnUrl   = null;

    public CrmPgwTransactionsPojo()
    {
    }

    public CrmPgwTransactionsPojo( Long recordId, String customerId, String pgwName, String paymentOption, double amount )
    {
        this.recordId = recordId;
        this.customerId = customerId;
        this.pgwName = pgwName;
        this.paymentOption = paymentOption;
        this.amount = amount;
    }

    public CrmPgwTransactionsPojo( Long recordId,
                                   String customerId,
                                   String pgwName,
                                   String paymentOption,
                                   String pgwTrackId,
                                   double amount,
                                   String pgwPaymentId,
                                   String pgwTransactionId,
                                   String pgwReferenceNumber,
                                   String pgwAuthCode,
                                   String pgwAvr,
                                   String pgwErrorCode,
                                   String pgwErrorMsg,
                                   String pgwResult,
                                   String pgwPaymentPage,
                                   String status,
                                   Date initiationDatetime,
                                   Date pgwAuthDatetime,
                                   Date pgwResponseDatetime )
    {
        this.recordId = recordId;
        this.customerId = customerId;
        this.pgwName = pgwName;
        this.paymentOption = paymentOption;
        this.pgwTrackId = pgwTrackId;
        this.amount = amount;
        this.pgwPaymentId = pgwPaymentId;
        this.pgwTransactionId = pgwTransactionId;
        this.pgwReferenceNumber = pgwReferenceNumber;
        this.pgwAuthCode = pgwAuthCode;
        this.pgwAvr = pgwAvr;
        this.pgwErrorCode = pgwErrorCode;
        this.pgwErrorMsg = pgwErrorMsg;
        this.pgwResult = pgwResult;
        this.pgwPaymentPage = pgwPaymentPage;
        this.status = status;
        this.initiationDatetime = initiationDatetime;
        this.pgwAuthDatetime = pgwAuthDatetime;
        this.pgwResponseDatetime = pgwResponseDatetime;
    }

    public double getAmount()
    {
        return amount;
    }

    public void setAmount( double amount )
    {
        this.amount = amount;
    }

    public Long getRecordId()
    {
        return recordId;
    }

    public void setRecordId( Long recordId )
    {
        this.recordId = recordId;
    }

    public String getCustomerId()
    {
        return customerId;
    }

    public void setCustomerId( String inCustomerId )
    {
        customerId = inCustomerId;
    }

    public Date getInitiationDatetime()
    {
        return initiationDatetime;
    }

    public void setInitiationDatetime( Date inInitiationDatetime )
    {
        initiationDatetime = inInitiationDatetime;
    }

    public String getPaymentOption()
    {
        return paymentOption;
    }

    public void setPaymentOption( String inPaymentOption )
    {
        paymentOption = inPaymentOption;
    }

    public String getPgwAuthCode()
    {
        return pgwAuthCode;
    }

    public void setPgwAuthCode( String inPgwAuthCode )
    {
        pgwAuthCode = inPgwAuthCode;
    }

    public Date getPgwAuthDatetime()
    {
        return pgwAuthDatetime;
    }

    public void setPgwAuthDatetime( Date inPgwAuthDatetime )
    {
        pgwAuthDatetime = inPgwAuthDatetime;
    }

    public String getPgwAvr()
    {
        return pgwAvr;
    }

    public void setPgwAvr( String inPgwAvr )
    {
        pgwAvr = inPgwAvr;
    }

    public String getPgwErrorCode()
    {
        return pgwErrorCode;
    }

    public void setPgwErrorCode( String inPgwErrorCode )
    {
        pgwErrorCode = inPgwErrorCode;
    }

    public String getPgwErrorMsg()
    {
        return pgwErrorMsg;
    }

    public void setPgwErrorMsg( String inPgwErrorMsg )
    {
        pgwErrorMsg = inPgwErrorMsg;
    }

    public String getPgwName()
    {
        return pgwName;
    }

    public void setPgwName( String inPgwName )
    {
        pgwName = inPgwName;
    }

    public String getPgwPaymentId()
    {
        return pgwPaymentId;
    }

    public void setPgwPaymentId( String inPgwPaymentId )
    {
        pgwPaymentId = inPgwPaymentId;
    }

    public String getPgwPaymentPage()
    {
        return pgwPaymentPage;
    }

    public void setPgwPaymentPage( String inPgwPaymentPage )
    {
        pgwPaymentPage = inPgwPaymentPage;
    }

    public String getPgwPostdate()
    {
        return pgwPostdate;
    }

    public void setPgwPostdate( String inPgwPostdate )
    {
        pgwPostdate = inPgwPostdate;
    }

    public String getPgwReferenceNumber()
    {
        return pgwReferenceNumber;
    }

    public void setPgwReferenceNumber( String inPgwReferenceNumber )
    {
        pgwReferenceNumber = inPgwReferenceNumber;
    }

    public Date getPgwResponseDatetime()
    {
        return pgwResponseDatetime;
    }

    public void setPgwResponseDatetime( Date inPgwResponseDatetime )
    {
        pgwResponseDatetime = inPgwResponseDatetime;
    }

    public String getPgwResult()
    {
        return pgwResult;
    }

    public void setPgwResult( String inPgwResult )
    {
        pgwResult = inPgwResult;
    }

    public String getPgwTrackId()
    {
        return pgwTrackId;
    }

    public void setPgwTrackId( String inPgwTrackId )
    {
        pgwTrackId = inPgwTrackId;
    }

    public String getPgwTransactionId()
    {
        return pgwTransactionId;
    }

    public void setPgwTransactionId( String inPgwTransactionId )
    {
        pgwTransactionId = inPgwTransactionId;
    }

    public String getRedirectUrl()
    {
        return redirectUrl;
    }

    public void setRedirectUrl( String inRedirectUrl )
    {
        redirectUrl = inRedirectUrl;
    }

    public String getStatus()
    {
        return status;
    }

    public void setStatus( String inStatus )
    {
        status = inStatus;
    }

    public String getUdf1()
    {
        return udf1;
    }

    public void setUdf1( String inUdf1 )
    {
        udf1 = inUdf1;
    }

    public String getUdf2()
    {
        return udf2;
    }

    public void setUdf2( String inUdf2 )
    {
        udf2 = inUdf2;
    }

    public String getUdf3()
    {
        return udf3;
    }

    public void setUdf3( String inUdf3 )
    {
        udf3 = inUdf3;
    }

    public String getUdf4()
    {
        return udf4;
    }

    public void setUdf4( String inUdf4 )
    {
        udf4 = inUdf4;
    }

    public String getUdf5()
    {
        return udf5;
    }

    public void setUdf5( String inUdf5 )
    {
        udf5 = inUdf5;
    }

    public String getPaymentReciept()
    {
        return paymentReciept;
    }

    public void setPaymentReciept( String inPaymentReciept )
    {
        paymentReciept = inPaymentReciept;
    }

    public String getBillingPaymentStatus()
    {
        return billingPaymentStatus;
    }

    public void setBillingPaymentStatus( String inBillingPaymentStatus )
    {
        billingPaymentStatus = inBillingPaymentStatus;
    }

    public String getAppReturnUrl()
    {
        return appReturnUrl;
    }

    public void setAppReturnUrl( String inAppReturnUrl )
    {
        appReturnUrl = inAppReturnUrl;
    }

    @Override
    public String toString()
    {
        return "RecID:: " + getRecordId() + " CustID:: " + getCustomerId() + " TrackID:: " + getPgwTrackId()
                + " InitTime:: " + getInitiationDatetime();
    }
}
