package com.np.tele.crm.pojos;

// Generated 5 Jul, 2013 11:15:37 AM by Hibernate Tools 3.4.0.CR1
import java.util.Date;
import java.util.Set;

import javax.xml.bind.annotation.XmlTransient;

/**
 * CrmParameter generated by hbm2java
 */
public class CrmParameterPojo
    implements java.io.Serializable
{
    private long         parameterId;
    private String       parameterGroup;
    private String       parameterGroupType;
    private String       parameterName;
    private String       parameterType;
    private long         parameterLength;
    private String       createdBy;
    private Date         createdTime;
    private String       lastModifiedBy;
    private Date         lastModifiedTime;
    private String       status;
    private ProjectsPojo projectsPojo;
    private boolean      editable;
    private String       displayCreatedTime;
    private String       displayLastModifiedTime;
    private String       parameterPattern;
    private String       parameterMultiplicity;
    private String       parameterDescription;

    /* private Set    accessGroups = new HashSet( 0 );
     private Set    userRoleses  = new HashSet( 0 );*/
    public CrmParameterPojo()
    {
    }

    public CrmParameterPojo( Long parameterId, String createdBy, String lastModifiedBy, Date lastModifiedTime )
    {
        this.parameterId = parameterId;
        this.createdBy = createdBy;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
    }

    public CrmParameterPojo( Long parameterId,
                             String parameterGroup,
                             String parameterGroupType,
                             String parameterName,
                             String parameterType,
                             Long parameterLength,
                             String createdBy,
                             Date createdTime,
                             String lastModifiedBy,
                             Date lastModifiedTime,
                             String status,
                             Set accessGroups,
                             Set userRoleses )
    {
        this.parameterId = parameterId;
        this.parameterGroup = parameterGroup;
        this.parameterGroupType = parameterGroupType;
        this.parameterName = parameterName;
        this.parameterType = parameterType;
        this.parameterLength = parameterLength;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
        this.status = status;
        /*this.accessGroups = accessGroups;
        this.userRoleses = userRoleses;*/
    }

    @XmlTransient
    public ProjectsPojo getProjectsPojo()
    {
        return projectsPojo;
    }

    public void setProjectsPojo( ProjectsPojo inProjectsPojo )
    {
        projectsPojo = inProjectsPojo;
    }

    public String getParameterGroup()
    {
        return this.parameterGroup;
    }

    public void setParameterGroup( String parameterGroup )
    {
        this.parameterGroup = parameterGroup;
    }

    public String getParameterGroupType()
    {
        return this.parameterGroupType;
    }

    public void setParameterGroupType( String parameterGroupType )
    {
        this.parameterGroupType = parameterGroupType;
    }

    public String getParameterName()
    {
        return this.parameterName;
    }

    public void setParameterName( String parameterName )
    {
        this.parameterName = parameterName;
    }

    public String getParameterType()
    {
        return this.parameterType;
    }

    public void setParameterType( String parameterType )
    {
        this.parameterType = parameterType;
    }

    public long getParameterId()
    {
        return parameterId;
    }

    public void setParameterId( long parameterId )
    {
        this.parameterId = parameterId;
    }

    public long getParameterLength()
    {
        return parameterLength;
    }

    public void setParameterLength( long parameterLength )
    {
        this.parameterLength = parameterLength;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date inCreatedTime )
    {
        createdTime = inCreatedTime;
        /*if ( StringUtils.isEmpty( displayCreatedTime ) && StringUtils.isValidObj( createdTime ) )
        {
            displayCreatedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( createdTime );
        }*/
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date inLastModifiedTime )
    {
        lastModifiedTime = inLastModifiedTime;
      /*  if ( StringUtils.isEmpty( displayLastModifiedTime ) && StringUtils.isValidObj( lastModifiedTime ) )
        {
            displayLastModifiedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( lastModifiedTime );
        }*/
    }

    public String getStatus()
    {
        return this.status;
    }

    public void setStatus( String status )
    {
        this.status = status;
    }

    public boolean isEditable()
    {
        return editable;
    }

    public void setEditable( boolean inEditable )
    {
        editable = inEditable;
    }

    public String getDisplayCreatedTime()
    {
        return displayCreatedTime;
    }

    public void setDisplayCreatedTime( String inDisplayCreatedTime )
    {
        displayCreatedTime = inDisplayCreatedTime;
    }

    public String getDisplayLastModifiedTime()
    {
        return displayLastModifiedTime;
    }

    public void setDisplayLastModifiedTime( String inDisplayLastModifiedTime )
    {
        displayLastModifiedTime = inDisplayLastModifiedTime;
    }

    public String getParameterPattern()
    {
        return parameterPattern;
    }

    public void setParameterPattern( String parameterPattern )
    {
        this.parameterPattern = parameterPattern;
    }

    public String getParameterMultiplicity()
    {
        return parameterMultiplicity;
    }

    public void setParameterMultiplicity( String parameterMultiplicity )
    {
        this.parameterMultiplicity = parameterMultiplicity;
    }

    public String getParameterDescription()
    {
        return parameterDescription;
    }

    public void setParameterDescription( String inParameterDescription )
    {
        parameterDescription = inParameterDescription;
    }

    @Override
    public int hashCode()
    {
        final int prime = 31;
        int result = 1;
        result = prime * result + (int) ( parameterId ^ ( parameterId >>> 32 ) );
        result = prime * result + ( ( parameterName == null ) ? 0 : parameterName.hashCode() );
        return result;
    }

    @Override
    public boolean equals( Object obj )
    {
        if ( this == obj )
            return true;
        if ( obj == null )
            return false;
        if ( getClass() != obj.getClass() )
            return false;
        CrmParameterPojo other = (CrmParameterPojo) obj;
        if ( parameterId != other.parameterId )
            return false;
        if ( parameterName == null )
        {
            if ( other.parameterName != null )
                return false;
        }
        else if ( !parameterName.equals( other.parameterName ) )
            return false;
        return true;
    }

    @Override
    public String toString()
    {
        StringBuilder builder = new StringBuilder();
        builder.append( "CrmParameterPojo [parameterId=" ).append( parameterId ).append( ", parameterGroup=" )
                .append( parameterGroup ).append( ", parameterGroupType=" ).append( parameterGroupType )
                .append( ", parameterName=" ).append( parameterName ).append( ", parameterType=" )
                .append( parameterType ).append( ", parameterLength=" ).append( parameterLength )
                .append( ", createdBy=" ).append( createdBy ).append( ", createdTime=" ).append( createdTime )
                .append( ", lastModifiedBy=" ).append( lastModifiedBy ).append( ", lastModifiedTime=" )
                .append( lastModifiedTime ).append( ", status=" ).append( status ).append( "]" );
        return builder.toString();
    }
    /*
        public Set getAccessGroups()
        {
            return this.accessGroups;
        }

        public void setAccessGroups( Set accessGroups )
        {
            this.accessGroups = accessGroups;
        }

        public Set getUserRoleses()
        {
            return this.userRoleses;
        }

        public void setUserRoleses( Set userRoleses )
        {
            this.userRoleses = userRoleses;
        }*/
}
