package com.np.tele.crm.pojos;

// default package
// Generated Aug 20, 2014 10:26:57 AM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

/**
 * CrmPlanMaster generated by hbm2java
 */
public class CrmPlanMasterPojo
    implements java.io.Serializable
{
    private long    planId;
    private String  planName;
    private String  planCode;
    private String  offerCode;
    private long    primarySpeed;
    private long    secondarySpeed;
    private long    primaryQuota;
    private long    secondaryQuota;
    private Double  rentExclTax;
    private Double  rentInclTax;
    private String  service;
    private String  planUsageType;
    private String  planType;
    private String  planCategory;
    private String  prepaidYn;
    private Date    activationDate;
    private Date    deactivationDate;
    private String  addonAllowedYn;
    private String  boosterAllowedYn;
    private Double  securityDeposit;
    private Double  advTelservPayment;
    private Double  advTelsolnPayment;
    private String  actvAllowedYn;
    private String  migrAllowedYn;
    private String  createdBy;
    private Date    createdTime;
    private String  lastModifiedBy;
    private Date    lastModifiedTime;
    private String  status;
    private boolean editable;
    private byte    quantity;
    private String  brand;
    private String  quotaType;

    public byte getQuantity()
    {
        return quantity;
    }

    public void setQuantity( byte inQuantity )
    {
        quantity = inQuantity;
    }

    public boolean isEditable()
    {
        return editable;
    }

    public void setEditable( boolean editable )
    {
        this.editable = editable;
    }

    public CrmPlanMasterPojo()
    {
    }

    public CrmPlanMasterPojo( Long planId,
                              String planName,
                              String planCode,
                              String offerCode,
                              long primarySpeed,
                              Long primaryQuota,
                              String service,
                              String planUsageType,
                              String planType,
                              String createdBy )
    {
        this.planId = planId;
        this.planName = planName;
        this.planCode = planCode;
        this.offerCode = offerCode;
        this.primarySpeed = primarySpeed;
        this.primaryQuota = primaryQuota;
        this.service = service;
        this.planUsageType = planUsageType;
        this.planType = planType;
        this.createdBy = createdBy;
    }

    public CrmPlanMasterPojo( Long planId,
                              String planName,
                              String planCode,
                              String offerCode,
                              long primarySpeed,
                              Long secondarySpeed,
                              Long primaryQuota,
                              Long secondaryQuota,
                              Double rentExclTax,
                              Double rentInclTax,
                              String service,
                              String planUsageType,
                              String planType,
                              String planCategory,
                              String prepaidYn,
                              Date activationDate,
                              Date deactivationDate,
                              String addonAllowedYn,
                              String boosterAllowedYn,
                              Double securityDeposit,
                              Double advTelservPayment,
                              Double advTelsolnPayment,
                              String actvAllowedYn,
                              String migrAllowedYn,
                              String createdBy,
                              Date createdTime,
                              String lastModifiedBy,
                              Date lastModifiedTime,
                              String status )
    {
        this.planId = planId;
        this.planName = planName;
        this.planCode = planCode;
        this.offerCode = offerCode;
        this.primarySpeed = primarySpeed;
        this.secondarySpeed = secondarySpeed;
        this.primaryQuota = primaryQuota;
        this.secondaryQuota = secondaryQuota;
        this.rentExclTax = rentExclTax;
        this.rentInclTax = rentInclTax;
        this.service = service;
        this.planUsageType = planUsageType;
        this.planType = planType;
        this.planCategory = planCategory;
        this.prepaidYn = prepaidYn;
        this.activationDate = activationDate;
        this.deactivationDate = deactivationDate;
        this.addonAllowedYn = addonAllowedYn;
        this.boosterAllowedYn = boosterAllowedYn;
        this.securityDeposit = securityDeposit;
        this.advTelservPayment = advTelservPayment;
        this.advTelsolnPayment = advTelsolnPayment;
        this.actvAllowedYn = actvAllowedYn;
        this.migrAllowedYn = migrAllowedYn;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
        this.status = status;
    }

    public long getPlanId()
    {
        return planId;
    }

    public void setPlanId( long planId )
    {
        this.planId = planId;
    }

    public long getPrimaryQuota()
    {
        return primaryQuota;
    }

    public void setPrimaryQuota( long primaryQuota )
    {
        this.primaryQuota = primaryQuota;
    }

    public long getSecondaryQuota()
    {
        return secondaryQuota;
    }

    public void setSecondaryQuota( long secondaryQuota )
    {
        this.secondaryQuota = secondaryQuota;
    }

    public Double getRentExclTax()
    {
        return rentExclTax;
    }

    public void setRentExclTax( Double rentExclTax )
    {
        this.rentExclTax = rentExclTax;
    }

    public Double getRentInclTax()
    {
        return rentInclTax;
    }

    public void setRentInclTax( Double rentInclTax )
    {
        this.rentInclTax = rentInclTax;
    }

    public Double getSecurityDeposit()
    {
        return securityDeposit;
    }

    public void setSecurityDeposit( Double securityDeposit )
    {
        this.securityDeposit = securityDeposit;
    }

    public Double getAdvTelservPayment()
    {
        return advTelservPayment;
    }

    public void setAdvTelservPayment( Double advTelservPayment )
    {
        this.advTelservPayment = advTelservPayment;
    }

    public Double getAdvTelsolnPayment()
    {
        return advTelsolnPayment;
    }

    public void setAdvTelsolnPayment( Double advTelsolnPayment )
    {
        this.advTelsolnPayment = advTelsolnPayment;
    }

    public String getPlanName()
    {
        return this.planName;
    }

    public void setPlanName( String planName )
    {
        this.planName = planName;
    }

    public String getPlanCode()
    {
        return this.planCode;
    }

    public void setPlanCode( String planCode )
    {
        this.planCode = planCode;
    }

    public String getOfferCode()
    {
        return this.offerCode;
    }

    public void setOfferCode( String offerCode )
    {
        this.offerCode = offerCode;
    }

    public long getPrimarySpeed()
    {
        return primarySpeed;
    }

    public void setPrimarySpeed( long primarySpeed )
    {
        this.primarySpeed = primarySpeed;
    }

    public long getSecondarySpeed()
    {
        return this.secondarySpeed;
    }

    public void setSecondarySpeed( long secondarySpeed )
    {
        this.secondarySpeed = secondarySpeed;
    }

    public String getService()
    {
        return this.service;
    }

    public void setService( String service )
    {
        this.service = service;
    }

    public String getPlanUsageType()
    {
        return this.planUsageType;
    }

    public void setPlanUsageType( String planUsageType )
    {
        this.planUsageType = planUsageType;
    }

    public String getPlanType()
    {
        return this.planType;
    }

    public void setPlanType( String planType )
    {
        this.planType = planType;
    }

    public String getPlanCategory()
    {
        return this.planCategory;
    }

    public void setPlanCategory( String planCategory )
    {
        this.planCategory = planCategory;
    }

    public String getPrepaidYn()
    {
        return this.prepaidYn;
    }

    public void setPrepaidYn( String prepaidYn )
    {
        this.prepaidYn = prepaidYn;
    }

    public Date getActivationDate()
    {
        return this.activationDate;
    }

    public void setActivationDate( Date activationDate )
    {
        this.activationDate = activationDate;
    }

    public Date getDeactivationDate()
    {
        return this.deactivationDate;
    }

    public void setDeactivationDate( Date deactivationDate )
    {
        this.deactivationDate = deactivationDate;
    }

    public String getAddonAllowedYn()
    {
        return this.addonAllowedYn;
    }

    public void setAddonAllowedYn( String addonAllowedYn )
    {
        this.addonAllowedYn = addonAllowedYn;
    }

    public String getBoosterAllowedYn()
    {
        return this.boosterAllowedYn;
    }

    public void setBoosterAllowedYn( String boosterAllowedYn )
    {
        this.boosterAllowedYn = boosterAllowedYn;
    }

    public String getActvAllowedYn()
    {
        return this.actvAllowedYn;
    }

    public void setActvAllowedYn( String actvAllowedYn )
    {
        this.actvAllowedYn = actvAllowedYn;
    }

    public String getMigrAllowedYn()
    {
        return this.migrAllowedYn;
    }

    public void setMigrAllowedYn( String migrAllowedYn )
    {
        this.migrAllowedYn = migrAllowedYn;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date createdTime )
    {
        this.createdTime = createdTime;
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date lastModifiedTime )
    {
        this.lastModifiedTime = lastModifiedTime;
    }

    public String getStatus()
    {
        return this.status;
    }

    public void setStatus( String status )
    {
        this.status = status;
    }

    public String getBrand()
    {
        return brand;
    }

    public void setBrand( String inBrand )
    {
        brand = inBrand;
    }

    public String getQuotaType()
    {
        return quotaType;
    }

    public void setQuotaType( String quotaType )
    {
        this.quotaType = quotaType;
    }
}
