package com.np.tele.crm.pojos;

// default package
// Generated Sep 19, 2014 11:51:37 AM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

/**
 * CrmQrcWhitelist generated by hbm2java
 */
public class CrmQrcWhitelistPojo
    implements java.io.Serializable
{
    private Long   recordId;
    private String customerId;
    private String whitelistType;
    private long   reason;
    private Date   endDate;
    private String createdBy;
    private Date   createdTime;
    private String lastModifiedBy;
    private Date   lastModifiedTime;

    public CrmQrcWhitelistPojo()
    {
    }

    public CrmQrcWhitelistPojo( Long recordId, String customerId, String whitelistType, int reason, String createdBy )
    {
        this.recordId = recordId;
        this.customerId = customerId;
        this.whitelistType = whitelistType;
        this.reason = reason;
        this.createdBy = createdBy;
    }

    public CrmQrcWhitelistPojo( Long recordId,
                                String customerId,
                                String whitelistType,
                                long reason,
                                Date endDate,
                                String createdBy,
                                Date createdTime,
                                String lastModifiedBy,
                                Date lastModifiedTime )
    {
        this.recordId = recordId;
        this.customerId = customerId;
        this.whitelistType = whitelistType;
        this.reason = reason;
        this.endDate = endDate;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
    }

    public Long getRecordId()
    {
        return recordId;
    }

    public void setRecordId( Long recordId )
    {
        this.recordId = recordId;
    }

    public long getReason()
    {
        return reason;
    }

    public void setReason( long reason )
    {
        this.reason = reason;
    }

    public String getCustomerId()
    {
        return this.customerId;
    }

    public void setCustomerId( String customerId )
    {
        this.customerId = customerId;
    }

    public String getWhitelistType()
    {
        return this.whitelistType;
    }

    public void setWhitelistType( String whitelistType )
    {
        this.whitelistType = whitelistType;
    }

    public Date getEndDate()
    {
        return this.endDate;
    }

    public void setEndDate( Date endDate )
    {
        this.endDate = endDate;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date createdTime )
    {
        this.createdTime = createdTime;
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date lastModifiedTime )
    {
        this.lastModifiedTime = lastModifiedTime;
    }

    @Override
    public String toString()
    {
        StringBuilder builder = new StringBuilder();
        builder.append( "CrmQrcWhitelistPojo [customerId=" ).append( customerId ).append( ", whitelistType=" )
                .append( whitelistType ).append( ", reason=" ).append( reason ).append( ", endDate=" ).append( endDate )
                .append( "]" );
        return builder.toString();
    }
}
