package com.np.tele.crm.pojos;

// default package
// Generated Sep 9, 2014 6:05:03 PM by Hibernate Tools 3.4.0.CR1
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CrmQrcCategoriesPojo generated by hbm2java
 */
public class CrmQrcCategoriesPojo
    implements java.io.Serializable
{
    private long                         qrcCategoryId;
    private String                       qrcCategory;
    private String                       modificationAllowed;
    private String                       createdBy;
    private Date                         createdTime;
    private String                       lastModifiedBy;
    private Date                         lastModifiedTime;
    private String                       status;
    private String                       functionalBin;
    private String                       moduleType;
    // private Set<CrmQrcActionTakenPojo>           crmQrcRcas            = new HashSet<CrmQrcActionTakenPojo>( 0 );
    private Set<CrmQrcSubCategoriesPojo> crmQrcSubCategorieses = new HashSet<CrmQrcSubCategoriesPojo>( 0 );

    //private Set<CrmSrTicketsPojo>        crmSrTicketses        = new HashSet<CrmSrTicketsPojo>( 0 );
    public CrmQrcCategoriesPojo()
    {
    }

    public CrmQrcCategoriesPojo( Long qrcCategoryId, String qrcCategory, String createdBy )
    {
        this.qrcCategoryId = qrcCategoryId;
        this.qrcCategory = qrcCategory;
        this.createdBy = createdBy;
    }

    //    public CrmQrcCategoriesPojo( long qrcCategoryId,
    //                                 String qrcCategory,
    //                                 String modificationAllowed,
    //                                 String createdBy,
    //                                 Date createdTime,
    //                                 String lastModifiedBy,
    //                                 Date lastModifiedTime,
    //                                 String status,
    //                                 Set crmQrcRcas,
    //                                 Set crmQrcSubCategorieses,
    //                                 Set crmSrTicketses )
    //    {
    //        this.qrcCategoryId = qrcCategoryId;
    //        this.qrcCategory = qrcCategory;
    //        this.modificationAllowed = modificationAllowed;
    //        this.createdBy = createdBy;
    //        this.createdTime = createdTime;
    //        this.lastModifiedBy = lastModifiedBy;
    //        this.lastModifiedTime = lastModifiedTime;
    //        this.status = status;
    //        this.crmQrcRcas = crmQrcRcas;
    //        this.crmQrcSubCategorieses = crmQrcSubCategorieses;
    //        this.crmSrTicketses = crmSrTicketses;
    //    }
    public long getQrcCategoryId()
    {
        return qrcCategoryId;
    }

    public void setQrcCategoryId( long qrcCategoryId )
    {
        this.qrcCategoryId = qrcCategoryId;
    }

    public String getQrcCategory()
    {
        return this.qrcCategory;
    }

    public void setQrcCategory( String qrcCategory )
    {
        this.qrcCategory = qrcCategory;
    }

    public String getModificationAllowed()
    {
        return this.modificationAllowed;
    }

    public void setModificationAllowed( String modificationAllowed )
    {
        this.modificationAllowed = modificationAllowed;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date createdTime )
    {
        this.createdTime = createdTime;
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date lastModifiedTime )
    {
        this.lastModifiedTime = lastModifiedTime;
    }

    public String getStatus()
    {
        return this.status;
    }

    public void setStatus( String status )
    {
        this.status = status;
    }

    /* public Set<CrmQrcActionTakenPojo> getCrmQrcRcas()
     {
         return crmQrcRcas;
     }

     public void setCrmQrcRcas( Set<CrmQrcActionTakenPojo> inCrmQrcRcas )
     {
         crmQrcRcas = inCrmQrcRcas;
     }*/
    public Set<CrmQrcSubCategoriesPojo> getCrmQrcSubCategorieses()
    {
        return crmQrcSubCategorieses;
    }

    public void setCrmQrcSubCategorieses( Set<CrmQrcSubCategoriesPojo> inCrmQrcSubCategorieses )
    {
        crmQrcSubCategorieses = inCrmQrcSubCategorieses;
    }

    //    public Set getCrmSrTicketses()
    //    {
    //        return this.crmSrTicketses;
    //    }
    //
    //    public void setCrmSrTicketses( Set crmSrTicketses )
    //    {
    //        this.crmSrTicketses = crmSrTicketses;
    //    }
    public String getFunctionalBin()
    {
        return functionalBin;
    }

    public void setFunctionalBin( String inFunctionalBin )
    {
        functionalBin = inFunctionalBin;
    }

    public String getModuleType()
    {
        return moduleType;
    }

    public void setModuleType( String inModuleType )
    {
        moduleType = inModuleType;
    }
}
