package com.np.tele.crm.pojos;

// default package
// Generated Sep 9, 2014 6:05:03 PM by Hibernate Tools 3.4.0.CR1
import java.util.Date;
import java.util.List;

/**
 * CrmSrTicketsPojo generated by hbm2java
 */
public class CrmSrTicketsPojo
    implements java.io.Serializable
{
    private static final long      serialVersionUID = -8762919352099116676L;
    private long                   ticketId;
    private long                   qrcSubSubCategoryId;
    private long                   qrcSubCategoryId;
    private long                   qrcCategoryId;
    //    private CrmQrcSubSubCategoriesPojo crmQrcSubSubCategoriesPojo;
    //    private CrmQrcSubCategoriesPojo    crmQrcSubCategoriesPojo;
    //    private CrmQrcCategoriesPojo       crmQrcCategoriesPojo;
    private String                 srId;
    private byte                   resolutionType;
    private long                   functionalbinId;
    private String                 moduleType;
    private String                 mappingId;
    private long                   actionTakenId;
    private long                   rootCauseId;
    private String                 createdBy;
    private String                 lastModifiedBy;
    private String                 status;
    private String                 qrcType;
    private String                 qrcSubSubCategory;
    private String                 qrcSubCategory;
    private String                 qrcCategory;
    private long                   callingNo;
    private String                 visitRequired;
    private String                 wrongTagging;
    private String                 resolvedBy;
    private CrmCustomerDetailsPojo customerDetailsPojo;
    private Date                   followupOn;
    private Date                   processingDate;
    private String                 displayFollowupOn;
    private Date                   srResolvedOn;
    private String                 displaySrResolvedOn;
    private Date                   srClosedOn;
    private String                 displaySrClosedOn;
    private Date                   srReopenedOn;
    private String                 displaySrReopenedOn;
    private Date                   createdTime;
    private String                 displayCreatedTime;
    private Date                   lastModifiedTime;
    private String                 displayLastModifiedTime;
    private boolean                unRead;
    private long                   inboxId;
    private boolean                editable;
    private List<RemarksPojo>      remarksPojos;
    private CrmQrcActionTakenPojo  qrcRcaPojo;
    private CrmQrcRootCausePojo    resolutionCodePojo;
    private String                 APITransactionId;
    private String                 previousStage;
    private String                 currentUser;
    private Date                   expectedSLATime;
    private long                   slaTime;
    private String                 actionTaken;
    private String                 rootCause;
    private String                 attributedTo;
    private Date                   slaCalculatedOn;
    private LMSPojo                lmsPojo;
    private String                 flagRemarks;
    private boolean                flagSelected     = true;

    public boolean isFlagSelected()
    {
        return flagSelected;
    }

    public void setFlagSelected( boolean flagSelected )
    {
        this.flagSelected = flagSelected;
    }

    public String getFlagRemarks()
    {
        return flagRemarks;
    }

    public void setFlagRemarks( String flagRemarks )
    {
        this.flagRemarks = flagRemarks;
    }

    public CrmSrTicketsPojo()
    {
    }

    public CrmSrTicketsPojo( long inTicketId,
                             long inQrcSubSubCategoryId,
                             long inQrcSubCategoryId,
                             long inQrcCategoryId,
                             String inSrId,
                             byte inResolutionType,
                             Long inFunctionalbinId,
                             String inModuleType,
                             String inMappingId,
                             Date inFollowupOn,
                             Date inSrResolvedOn,
                             Date inSrClosedOn,
                             Date inSrReopenedOn,
                             Long inRcaId,
                             Long inResolutionCodeId,
                             String inCreatedBy,
                             Date inCreatedTime,
                             String inLastModifiedBy,
                             Date inLastModifiedTime,
                             String inStatus,
                             String inQrcType,
                             String inQrcSubSubCategory,
                             String inQrcSubCategory,
                             String inQrcCategory,
                             Long inCallingNo,
                             String inVisitRequired,
                             String inWrongTagging,
                             String inResolvedBy )
    {
        ticketId = inTicketId;
        qrcSubSubCategoryId = inQrcSubSubCategoryId;
        qrcSubCategoryId = inQrcSubCategoryId;
        qrcCategoryId = inQrcCategoryId;
        srId = inSrId;
        resolutionType = inResolutionType;
        functionalbinId = inFunctionalbinId;
        moduleType = inModuleType;
        mappingId = inMappingId;
        followupOn = inFollowupOn;
        srResolvedOn = inSrResolvedOn;
        srClosedOn = inSrClosedOn;
        srReopenedOn = inSrReopenedOn;
        actionTakenId = inRcaId;
        rootCauseId = inResolutionCodeId;
        createdBy = inCreatedBy;
        createdTime = inCreatedTime;
        lastModifiedBy = inLastModifiedBy;
        lastModifiedTime = inLastModifiedTime;
        status = inStatus;
        qrcType = inQrcType;
        qrcSubSubCategory = inQrcSubSubCategory;
        qrcSubCategory = inQrcSubCategory;
        qrcCategory = inQrcCategory;
        callingNo = inCallingNo;
        visitRequired = inVisitRequired;
        wrongTagging = inWrongTagging;
        resolvedBy = inResolvedBy;
    }

    public CrmQrcActionTakenPojo getQrcRcaPojo()
    {
        return qrcRcaPojo;
    }

    public void setQrcRcaPojo( CrmQrcActionTakenPojo inQrcRcaPojo )
    {
        qrcRcaPojo = inQrcRcaPojo;
    }

    public CrmQrcRootCausePojo getResolutionCodePojo()
    {
        return resolutionCodePojo;
    }

    public void setResolutionCodePojo( CrmQrcRootCausePojo inResolutionCodePojo )
    {
        resolutionCodePojo = inResolutionCodePojo;
    }

    public List<RemarksPojo> getRemarksPojos()
    {
        return remarksPojos;
    }

    public void setRemarksPojos( List<RemarksPojo> inRemarksPojos )
    {
        remarksPojos = inRemarksPojos;
    }

    public long getTicketId()
    {
        return ticketId;
    }

    public void setTicketId( long inTicketId )
    {
        ticketId = inTicketId;
    }

    public String getSrId()
    {
        return srId;
    }

    public void setSrId( String inSrId )
    {
        srId = inSrId;
    }

    public byte getResolutionType()
    {
        return resolutionType;
    }

    public void setResolutionType( byte inResolutionType )
    {
        resolutionType = inResolutionType;
    }

    public String getModuleType()
    {
        return moduleType;
    }

    public void setModuleType( String inModuleType )
    {
        moduleType = inModuleType;
    }

    public String getMappingId()
    {
        return mappingId;
    }

    public void setMappingId( String inMappingId )
    {
        mappingId = inMappingId;
    }

    public Date getFollowupOn()
    {
        return followupOn;
    }

    public void setFollowupOn( Date inFollowupOn )
    {
        followupOn = inFollowupOn;
        /* if ( StringUtils.isEmpty( displayFollowupOn ) && StringUtils.isValidObj( followupOn ) )
         {
             displayFollowupOn = IDateConstants.SDF_DD_MMM_YYYY.format( followupOn );
         }*/
    }

    public Date getProcessingDate()
    {
        return processingDate;
    }

    public void setProcessingDate( Date inProcessingDate )
    {
        processingDate = inProcessingDate;
    }

    public Date getSrResolvedOn()
    {
        return srResolvedOn;
    }

    public void setSrResolvedOn( Date inSrResolvedOn )
    {
        srResolvedOn = inSrResolvedOn;
        /* if ( StringUtils.isEmpty( displaySrResolvedOn ) && StringUtils.isValidObj( srResolvedOn ) )
         {
             displaySrResolvedOn = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( srResolvedOn );
         }*/
    }

    public Date getSrClosedOn()
    {
        return srClosedOn;
    }

    public void setSrClosedOn( Date inSrClosedOn )
    {
        srClosedOn = inSrClosedOn;
        /*if ( StringUtils.isEmpty( displaySrClosedOn ) && StringUtils.isValidObj( srClosedOn ) )
        {
            displaySrClosedOn = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( srClosedOn );
        }*/
    }

    public Date getSrReopenedOn()
    {
        return srReopenedOn;
    }

    public void setSrReopenedOn( Date inSrReopenedOn )
    {
        srReopenedOn = inSrReopenedOn;
        /* if ( StringUtils.isEmpty( displaySrReopenedOn ) && StringUtils.isValidObj( srReopenedOn ) )
         {
             displaySrReopenedOn = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( srReopenedOn );
         }*/
    }

    public String getCreatedBy()
    {
        return createdBy;
    }

    public void setCreatedBy( String inCreatedBy )
    {
        createdBy = inCreatedBy;
    }

    public Date getCreatedTime()
    {
        return createdTime;
    }

    public void setCreatedTime( Date inCreatedTime )
    {
        createdTime = inCreatedTime;
        /*if ( StringUtils.isEmpty( displayCreatedTime ) && StringUtils.isValidObj( createdTime ) )
        {
            displayCreatedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( createdTime );
        }*/
    }

    public String getLastModifiedBy()
    {
        return lastModifiedBy;
    }

    public void setLastModifiedBy( String inLastModifiedBy )
    {
        lastModifiedBy = inLastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return lastModifiedTime;
    }

    public void setLastModifiedTime( Date inLastModifiedTime )
    {
        lastModifiedTime = inLastModifiedTime;
        /* if ( StringUtils.isEmpty( displayLastModifiedTime ) && StringUtils.isValidObj( lastModifiedTime ) )
         {
             displayLastModifiedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( lastModifiedTime );
         }*/
    }

    public String getStatus()
    {
        return status;
    }

    public void setStatus( String inStatus )
    {
        status = inStatus;
    }

    public String getQrcType()
    {
        return qrcType;
    }

    public void setQrcType( String inQrcType )
    {
        qrcType = inQrcType;
    }

    public String getQrcSubSubCategory()
    {
        return qrcSubSubCategory;
    }

    public void setQrcSubSubCategory( String inQrcSubSubCategory )
    {
        qrcSubSubCategory = inQrcSubSubCategory;
    }

    public String getQrcSubCategory()
    {
        return qrcSubCategory;
    }

    public void setQrcSubCategory( String inQrcSubCategory )
    {
        qrcSubCategory = inQrcSubCategory;
    }

    public String getQrcCategory()
    {
        return qrcCategory;
    }

    public void setQrcCategory( String inQrcCategory )
    {
        qrcCategory = inQrcCategory;
    }

    public String getVisitRequired()
    {
        return visitRequired;
    }

    public void setVisitRequired( String inVisitRequired )
    {
        visitRequired = inVisitRequired;
    }

    public String getWrongTagging()
    {
        return wrongTagging;
    }

    public void setWrongTagging( String inWrongTagging )
    {
        wrongTagging = inWrongTagging;
    }

    public String getResolvedBy()
    {
        return resolvedBy;
    }

    public void setResolvedBy( String inResolvedBy )
    {
        resolvedBy = inResolvedBy;
    }

    public CrmCustomerDetailsPojo getCustomerDetailsPojo()
    {
        return customerDetailsPojo;
    }

    public void setCustomerDetailsPojo( CrmCustomerDetailsPojo inCustomerDetailsPojo )
    {
        customerDetailsPojo = inCustomerDetailsPojo;
    }

    public String getDisplayFollowupOn()
    {
        return displayFollowupOn;
    }

    public void setDisplayFollowupOn( String inDisplayFollowupOn )
    {
        displayFollowupOn = inDisplayFollowupOn;
    }

    public String getDisplaySrResolvedOn()
    {
        return displaySrResolvedOn;
    }

    public void setDisplaySrResolvedOn( String inDisplaySrResolvedOn )
    {
        displaySrResolvedOn = inDisplaySrResolvedOn;
    }

    public String getDisplaySrClosedOn()
    {
        return displaySrClosedOn;
    }

    public void setDisplaySrClosedOn( String inDisplaySrClosedOn )
    {
        displaySrClosedOn = inDisplaySrClosedOn;
    }

    public String getDisplaySrReopenedOn()
    {
        return displaySrReopenedOn;
    }

    public void setDisplaySrReopenedOn( String inDisplaySrReopenedOn )
    {
        displaySrReopenedOn = inDisplaySrReopenedOn;
    }

    public String getDisplayCreatedTime()
    {
        return displayCreatedTime;
    }

    public void setDisplayCreatedTime( String inDisplayCreatedTime )
    {
        displayCreatedTime = inDisplayCreatedTime;
    }

    public String getDisplayLastModifiedTime()
    {
        return displayLastModifiedTime;
    }

    public void setDisplayLastModifiedTime( String inDisplayLastModifiedTime )
    {
        displayLastModifiedTime = inDisplayLastModifiedTime;
    }

    public boolean isUnRead()
    {
        return unRead;
    }

    public void setUnRead( boolean inUnRead )
    {
        unRead = inUnRead;
    }

    public long getInboxId()
    {
        return inboxId;
    }

    public void setInboxId( long inInboxId )
    {
        inboxId = inInboxId;
    }

    public boolean isEditable()
    {
        return editable;
    }

    public void setEditable( boolean editable )
    {
        this.editable = editable;
    }

    public String getAPITransactionId()
    {
        return APITransactionId;
    }

    public void setAPITransactionId( String aPITransactionId )
    {
        APITransactionId = aPITransactionId;
    }

    public String getPreviousStage()
    {
        return previousStage;
    }

    public void setPreviousStage( String previousStage )
    {
        this.previousStage = previousStage;
    }

    public String getCurrentUser()
    {
        return currentUser;
    }

    public void setCurrentUser( String currentUser )
    {
        this.currentUser = currentUser;
    }

    public Date getExpectedSLATime()
    {
        return expectedSLATime;
    }

    public String getActionTaken()
    {
        return actionTaken;
    }

    public String getRootCause()
    {
        return rootCause;
    }

    public String getAttributedTo()
    {
        return attributedTo;
    }

    public void setExpectedSLATime( Date inExpectedSLATime )
    {
        expectedSLATime = inExpectedSLATime;
    }

    public void setActionTaken( String inActionTaken )
    {
        actionTaken = inActionTaken;
    }

    public void setRootCause( String inRootCause )
    {
        rootCause = inRootCause;
    }

    public void setAttributedTo( String inAttributedTo )
    {
        attributedTo = inAttributedTo;
    }

    public Date getSlaCalculatedOn()
    {
        return slaCalculatedOn;
    }

    public void setSlaCalculatedOn( Date inSlaCalculatedOn )
    {
        slaCalculatedOn = inSlaCalculatedOn;
    }

    public long getQrcSubSubCategoryId()
    {
        return qrcSubSubCategoryId;
    }

    public void setQrcSubSubCategoryId( long qrcSubSubCategoryId )
    {
        this.qrcSubSubCategoryId = qrcSubSubCategoryId;
    }

    public long getQrcSubCategoryId()
    {
        return qrcSubCategoryId;
    }

    public void setQrcSubCategoryId( long qrcSubCategoryId )
    {
        this.qrcSubCategoryId = qrcSubCategoryId;
    }

    public long getQrcCategoryId()
    {
        return qrcCategoryId;
    }

    public void setQrcCategoryId( long qrcCategoryId )
    {
        this.qrcCategoryId = qrcCategoryId;
    }

    public long getFunctionalbinId()
    {
        return functionalbinId;
    }

    public void setFunctionalbinId( long functionalbinId )
    {
        this.functionalbinId = functionalbinId;
    }

    public long getActionTakenId()
    {
        return actionTakenId;
    }

    public void setActionTakenId( long actionTakenId )
    {
        this.actionTakenId = actionTakenId;
    }

    public long getRootCauseId()
    {
        return rootCauseId;
    }

    public void setRootCauseId( long rootCauseId )
    {
        this.rootCauseId = rootCauseId;
    }

    public long getCallingNo()
    {
        return callingNo;
    }

    public void setCallingNo( long callingNo )
    {
        this.callingNo = callingNo;
    }

    public long getSlaTime()
    {
        return slaTime;
    }

    public void setSlaTime( long slaTime )
    {
        this.slaTime = slaTime;
    }

    public LMSPojo getLmsPojo()
    {
        return lmsPojo;
    }

    public void setLmsPojo( LMSPojo inLmsPojo )
    {
        lmsPojo = inLmsPojo;
    }

    @Override
    public String toString()
    {
        StringBuilder builder = new StringBuilder();
        builder.append( "CrmSrTicketsPojo [qrcSubSubCategoryId=" ).append( qrcSubSubCategoryId )
                .append( ", qrcSubCategoryId=" ).append( qrcSubCategoryId ).append( ", qrcCategoryId=" )
                .append( qrcCategoryId ).append( ", srId=" ).append( srId ).append( ", resolutionType=" )
                .append( resolutionType ).append( ", functionalbinId=" ).append( functionalbinId )
                .append( ", moduleType=" ).append( moduleType ).append( ", mappingId=" ).append( mappingId )
                .append( ", status=" ).append( status ).append( ", qrcType=" ).append( qrcType )
                .append( ", processingDate=" ).append( processingDate ).append( ", APITransactionId=" )
                .append( APITransactionId ).append( "]" );
        return builder.toString();
    }
}
