package com.np.tele.crm.pojos;

// default package
// Generated Mar 13, 2015 1:08:54 PM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

/**
 * CrmShiftingWorkflowPojo generated by hbm2java
 */
public class CrmShiftingWorkflowPojo
    implements java.io.Serializable
{
    private long    shiftingId;
    private String  workflowId;
    private String  workflowStage;
    private String  customerId;
    private String  shiftingType;
    private String  shiftingAddress;
    private long    npId;
    private long    spId;
    private String  createdBy;
    private Date    createdTime;
    private String  lastModifiedBy;
    private Date    lastModifiedTime;
    private String  status;
    private String  previousStage;
    private Long    stateId;
    private Long    cityId;
    private Long    areaId;
    private Long    societyId;
    private String  locality;
    private String  society;
    private String  houseNumber;
    private String  landmark;
    private Integer pincode;
    private String  addressLine1;
    private String  addressLine2;
    private String  addressLine3;
    private String  proprtyType;
    private String  closerReason;
    private String  product;
    private String  previousNetwork;
    private String  currentBin;
    private String  previousBin;
    private Long    previousNpId;
    private String  physicalInstallation;
    private String  customerRefusal;
    private String  cpeAvailable;
    private String  option82;
    private String  currentCPeMacId;
    private String  currentSlaveMacId;
    private String  currentProcessOwner;
    private String  basePlanCode;
    private String  addOnPlanCode;
    private String  serviceChange;
    private String  planChange;
    private String  nassportChange;
    private String  macBind;

    public CrmShiftingWorkflowPojo()
    {
    }

    public CrmShiftingWorkflowPojo( Long shiftingId,
                                    String workflowStage,
                                    String customerId,
                                    String shiftingType,
                                    String shiftingAddress,
                                    String createdBy )
    {
        this.shiftingId = shiftingId;
        this.workflowStage = workflowStage;
        this.customerId = customerId;
        this.shiftingType = shiftingType;
        this.shiftingAddress = shiftingAddress;
        this.createdBy = createdBy;
    }

    public CrmShiftingWorkflowPojo( Long shiftingId,
                                    String workflowId,
                                    String workflowStage,
                                    String customerId,
                                    String shiftingType,
                                    String shiftingAddress,
                                    Long npId,
                                    Long spId,
                                    String createdBy,
                                    Date createdTime,
                                    String lastModifiedBy,
                                    Date lastModifiedTime,
                                    String status )
    {
        this.shiftingId = shiftingId;
        this.workflowId = workflowId;
        this.workflowStage = workflowStage;
        this.customerId = customerId;
        this.shiftingType = shiftingType;
        this.shiftingAddress = shiftingAddress;
        this.npId = npId;
        this.spId = spId;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
        this.status = status;
    }

    public long getShiftingId()
    {
        return shiftingId;
    }

    public void setShiftingId( long shiftingId )
    {
        this.shiftingId = shiftingId;
    }

    public long getNpId()
    {
        return npId;
    }

    public void setNpId( long npId )
    {
        this.npId = npId;
    }

    public long getSpId()
    {
        return spId;
    }

    public void setSpId( long spId )
    {
        this.spId = spId;
    }

    public String getWorkflowId()
    {
        return this.workflowId;
    }

    public void setWorkflowId( String workflowId )
    {
        this.workflowId = workflowId;
    }

    public String getWorkflowStage()
    {
        return this.workflowStage;
    }

    public void setWorkflowStage( String workflowStage )
    {
        this.workflowStage = workflowStage;
    }

    public String getCustomerId()
    {
        return this.customerId;
    }

    public void setCustomerId( String customerId )
    {
        this.customerId = customerId;
    }

    public String getShiftingType()
    {
        return this.shiftingType;
    }

    public void setShiftingType( String shiftingType )
    {
        this.shiftingType = shiftingType;
    }

    public String getShiftingAddress()
    {
        return this.shiftingAddress;
    }

    public void setShiftingAddress( String shiftingAddress )
    {
        this.shiftingAddress = shiftingAddress;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date createdTime )
    {
        this.createdTime = createdTime;
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date lastModifiedTime )
    {
        this.lastModifiedTime = lastModifiedTime;
    }

    public String getStatus()
    {
        return this.status;
    }

    public void setStatus( String status )
    {
        this.status = status;
    }

    public String getPreviousStage()
    {
        return previousStage;
    }

    public void setPreviousStage( String previousStage )
    {
        this.previousStage = previousStage;
    }

    public Long getStateId()
    {
        return stateId;
    }

    public void setStateId( Long stateId )
    {
        this.stateId = stateId;
    }

    public Long getCityId()
    {
        return cityId;
    }

    public void setCityId( Long cityId )
    {
        this.cityId = cityId;
    }

    public Long getAreaId()
    {
        return areaId;
    }

    public void setAreaId( Long areaId )
    {
        this.areaId = areaId;
    }

    public Long getSocietyId()
    {
        return societyId;
    }

    public void setSocietyId( Long societyId )
    {
        this.societyId = societyId;
    }

    public String getLocality()
    {
        return locality;
    }

    public void setLocality( String locality )
    {
        this.locality = locality;
    }

    public String getSociety()
    {
        return society;
    }

    public void setSociety( String society )
    {
        this.society = society;
    }

    public String getHouseNumber()
    {
        return houseNumber;
    }

    public void setHouseNumber( String houseNumber )
    {
        this.houseNumber = houseNumber;
    }

    public String getLandmark()
    {
        return landmark;
    }

    public void setLandmark( String landmark )
    {
        this.landmark = landmark;
    }

    public Integer getPincode()
    {
        return pincode;
    }

    public void setPincode( Integer pincode )
    {
        this.pincode = pincode;
    }

    public String getAddressLine1()
    {
        return addressLine1;
    }

    public void setAddressLine1( String addressLine1 )
    {
        this.addressLine1 = addressLine1;
    }

    public String getAddressLine2()
    {
        return addressLine2;
    }

    public void setAddressLine2( String addressLine2 )
    {
        this.addressLine2 = addressLine2;
    }

    public String getAddressLine3()
    {
        return addressLine3;
    }

    public void setAddressLine3( String addressLine3 )
    {
        this.addressLine3 = addressLine3;
    }

    public String getProprtyType()
    {
        return proprtyType;
    }

    public void setProprtyType( String proprtyType )
    {
        this.proprtyType = proprtyType;
    }

    public String getCloserReason()
    {
        return closerReason;
    }

    public void setCloserReason( String closerReason )
    {
        this.closerReason = closerReason;
    }

    public String getProduct()
    {
        return product;
    }

    public void setProduct( String product )
    {
        this.product = product;
    }

    public String getPreviousNetwork()
    {
        return previousNetwork;
    }

    public void setPreviousNetwork( String inPreviousNetwork )
    {
        previousNetwork = inPreviousNetwork;
    }

    public String getCurrentBin()
    {
        return currentBin;
    }

    public void setCurrentBin( String inCurrentBin )
    {
        currentBin = inCurrentBin;
    }

    public String getPreviousBin()
    {
        return previousBin;
    }

    public void setPreviousBin( String inPreviousBin )
    {
        previousBin = inPreviousBin;
    }

    public Long getPreviousNpId()
    {
        return previousNpId;
    }

    public void setPreviousNpId( Long inPreviousNpId )
    {
        previousNpId = inPreviousNpId;
    }

    public String getPhysicalInstallation()
    {
        return physicalInstallation;
    }

    public void setPhysicalInstallation( String inPhysicalInstallation )
    {
        physicalInstallation = inPhysicalInstallation;
    }

    public String getCustomerRefusal()
    {
        return customerRefusal;
    }

    public void setCustomerRefusal( String inCustomerRefusal )
    {
        customerRefusal = inCustomerRefusal;
    }

    public String getCpeAvailable()
    {
        return cpeAvailable;
    }

    public void setCpeAvailable( String inCpeAvailable )
    {
        cpeAvailable = inCpeAvailable;
    }

    public String getOption82()
    {
        return option82;
    }

    public void setOption82( String inOption82 )
    {
        option82 = inOption82;
    }

    public String getCurrentCPeMacId()
    {
        return currentCPeMacId;
    }

    public void setCurrentCPeMacId( String inCurrentCPeMacId )
    {
        currentCPeMacId = inCurrentCPeMacId;
    }

    public String getCurrentSlaveMacId()
    {
        return currentSlaveMacId;
    }

    public void setCurrentSlaveMacId( String inCurrentSlaveMacId )
    {
        currentSlaveMacId = inCurrentSlaveMacId;
    }

    public String getCurrentProcessOwner()
    {
        return currentProcessOwner;
    }

    public void setCurrentProcessOwner( String inCurrentProcessOwner )
    {
        currentProcessOwner = inCurrentProcessOwner;
    }

    public String getBasePlanCode()
    {
        return basePlanCode;
    }

    public void setBasePlanCode( String inBasePlanCode )
    {
        basePlanCode = inBasePlanCode;
    }

    public String getAddOnPlanCode()
    {
        return addOnPlanCode;
    }

    public void setAddOnPlanCode( String inAddOnPlanCode )
    {
        addOnPlanCode = inAddOnPlanCode;
    }

    public String getNassportChange()
    {
        return nassportChange;
    }

    public void setNassportChange( String inNassportChange )
    {
        nassportChange = inNassportChange;
    }

    public String getMacBind()
    {
        return macBind;
    }

    public void setMacBind( String inMacBind )
    {
        macBind = inMacBind;
    }

    public String getServiceChange()
    {
        return serviceChange;
    }

    public void setServiceChange( String inServiceChange )
    {
        serviceChange = inServiceChange;
    }

    public String getPlanChange()
    {
        return planChange;
    }

    public void setPlanChange( String inPlanChange )
    {
        planChange = inPlanChange;
    }

    @Override
    public String toString()
    {
        return "CrmShiftingWorkflowPojo [shiftingId=" + shiftingId + ", workflowId=" + workflowId + ", workflowStage="
                + workflowStage + ", customerId=" + customerId + ", shiftingType=" + shiftingType
                + ", shiftingAddress=" + shiftingAddress + ", npId=" + npId + ", spId=" + spId + ", createdBy="
                + createdBy + ", createdTime=" + createdTime + ", lastModifiedBy=" + lastModifiedBy
                + ", lastModifiedTime=" + lastModifiedTime + ", status=" + status + ", previousStage=" + previousStage
                + ", stateId=" + stateId + ", cityId=" + cityId + ", areaId=" + areaId + ", societyId=" + societyId
                + ", locality=" + locality + ", society=" + society + ", houseNumber=" + houseNumber + ", landmark="
                + landmark + ", pincode=" + pincode + ", addressLine1=" + addressLine1 + ", addressLine2="
                + addressLine2 + ", addressLine3=" + addressLine3 + ", proprtyType=" + proprtyType + ", closerReason="
                + closerReason + ", product=" + product + ", previousNetwork=" + previousNetwork + ", currentBin="
                + currentBin + ", previousBin=" + previousBin + ", previousNpId=" + previousNpId
                + ", physicalInstallation=" + physicalInstallation + ", customerRefusal=" + customerRefusal
                + ", cpeAvailable=" + cpeAvailable + ", option82=" + option82 + ", currentCPeMacId=" + currentCPeMacId
                + ", currentSlaveMacId=" + currentSlaveMacId + ", currentProcessOwner=" + currentProcessOwner + "]";
    }
}
