package com.np.tele.crm.pojos;

// default package
// Generated Dec 8, 2014 11:26:58 AM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

/**
 * CrmSelfcareCategoriesPojo generated by hbm2java
 */
public class CrmSelfcareCategoriesPojo
    implements java.io.Serializable
{
    private Long   selfcareCategoryId;
    private long   qrcSubSubCategoryId;
    private String subject;
    private String selfcareCategory;
    private String createdBy;
    private Date   createdTime;
    private String status;

    public CrmSelfcareCategoriesPojo()
    {
    }

    public CrmSelfcareCategoriesPojo( Long selfcareCategoryId,
                                      long qrcSubSubCategoryId,
                                      String subject,
                                      String selfcareCategory,
                                      String createdBy )
    {
        this.selfcareCategoryId = selfcareCategoryId;
        this.qrcSubSubCategoryId = qrcSubSubCategoryId;
        this.subject = subject;
        this.selfcareCategory = selfcareCategory;
        this.createdBy = createdBy;
    }

    public CrmSelfcareCategoriesPojo( Long selfcareCategoryId,
                                      long qrcSubSubCategoryId,
                                      String subject,
                                      String selfcareCategory,
                                      String createdBy,
                                      Date createdTime,
                                      String status )
    {
        this.selfcareCategoryId = selfcareCategoryId;
        this.qrcSubSubCategoryId = qrcSubSubCategoryId;
        this.subject = subject;
        this.selfcareCategory = selfcareCategory;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.status = status;
    }

    public Long getSelfcareCategoryId()
    {
        return selfcareCategoryId;
    }

    public void setSelfcareCategoryId( Long selfcareCategoryId )
    {
        this.selfcareCategoryId = selfcareCategoryId;
    }

    public long getQrcSubSubCategoryId()
    {
        return qrcSubSubCategoryId;
    }

    public void setQrcSubSubCategoryId( long qrcSubSubCategoryId )
    {
        this.qrcSubSubCategoryId = qrcSubSubCategoryId;
    }

    public String getSubject()
    {
        return this.subject;
    }

    public void setSubject( String subject )
    {
        this.subject = subject;
    }

    public String getSelfcareCategory()
    {
        return this.selfcareCategory;
    }

    public void setSelfcareCategory( String selfcareCategory )
    {
        this.selfcareCategory = selfcareCategory;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date createdTime )
    {
        this.createdTime = createdTime;
    }

    public String getStatus()
    {
        return this.status;
    }

    public void setStatus( String status )
    {
        this.status = status;
    }
}
