package com.np.tele.crm.pojos;

// default package
// Generated Jun 15, 2015 4:13:54 PM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

/**
 * CrmTicketHistoryPojo generated by hbm2java
 */
public class CrmTicketHistoryPojo
    implements java.io.Serializable
{
    private long   recordId;
    private String ticketId;
    private String action;
    private long   fromBin;
    private long   toBin;
    private Date   oldFollowupOn;
    private Date   newFollowupOn;
    private String actionTaken;
    private String rootCause;
    private String attributedTo;
    private String visitRequired;
    private String wrongTagging;
    private String remarks;
    private String createdBy;
    private Date   createdTime;
    private String fromUser;
    private String toUser;
    private String clientIp;
    private String serverIp;
    private String serviceIp;

    public CrmTicketHistoryPojo()
    {
    }

    public CrmTicketHistoryPojo( long recordId, String ticketId, String action, String createdBy )
    {
        this.recordId = recordId;
        this.ticketId = ticketId;
        this.action = action;
        this.createdBy = createdBy;
    }

    public CrmTicketHistoryPojo( long recordId,
                                 String ticketId,
                                 String action,
                                 Long fromBin,
                                 Long toBin,
                                 Date oldFollowupOn,
                                 Date newFollowupOn,
                                 String actionTaken,
                                 String rootCause,
                                 String attributedTo,
                                 String visitRequired,
                                 String wrongTagging,
                                 String remarks,
                                 String createdBy,
                                 Date createdTime )
    {
        this.recordId = recordId;
        this.ticketId = ticketId;
        this.action = action;
        this.fromBin = fromBin;
        this.toBin = toBin;
        this.oldFollowupOn = oldFollowupOn;
        this.newFollowupOn = newFollowupOn;
        this.actionTaken = actionTaken;
        this.rootCause = rootCause;
        this.attributedTo = attributedTo;
        this.visitRequired = visitRequired;
        this.wrongTagging = wrongTagging;
        this.remarks = remarks;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
    }

    public long getRecordId()
    {
        return this.recordId;
    }

    public void setRecordId( long recordId )
    {
        this.recordId = recordId;
    }

    public String getTicketId()
    {
        return this.ticketId;
    }

    public void setTicketId( String ticketId )
    {
        this.ticketId = ticketId;
    }

    public String getAction()
    {
        return this.action;
    }

    public void setAction( String action )
    {
        this.action = action;
    }

    public long getFromBin()
    {
        return fromBin;
    }

    public void setFromBin( long fromBin )
    {
        this.fromBin = fromBin;
    }

    public long getToBin()
    {
        return toBin;
    }

    public void setToBin( long toBin )
    {
        this.toBin = toBin;
    }

    public Date getOldFollowupOn()
    {
        return this.oldFollowupOn;
    }

    public void setOldFollowupOn( Date oldFollowupOn )
    {
        this.oldFollowupOn = oldFollowupOn;
    }

    public Date getNewFollowupOn()
    {
        return this.newFollowupOn;
    }

    public void setNewFollowupOn( Date newFollowupOn )
    {
        this.newFollowupOn = newFollowupOn;
    }

    public String getActionTaken()
    {
        return this.actionTaken;
    }

    public void setActionTaken( String actionTaken )
    {
        this.actionTaken = actionTaken;
    }

    public String getRootCause()
    {
        return this.rootCause;
    }

    public void setRootCause( String rootCause )
    {
        this.rootCause = rootCause;
    }

    public String getAttributedTo()
    {
        return this.attributedTo;
    }

    public void setAttributedTo( String attributedTo )
    {
        this.attributedTo = attributedTo;
    }

    public String getVisitRequired()
    {
        return this.visitRequired;
    }

    public void setVisitRequired( String visitRequired )
    {
        this.visitRequired = visitRequired;
    }

    public String getWrongTagging()
    {
        return this.wrongTagging;
    }

    public void setWrongTagging( String wrongTagging )
    {
        this.wrongTagging = wrongTagging;
    }

    public String getRemarks()
    {
        return this.remarks;
    }

    public void setRemarks( String remarks )
    {
        this.remarks = remarks;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date createdTime )
    {
        this.createdTime = createdTime;
    }

    public String getFromUser()
    {
        return fromUser;
    }

    public String getToUser()
    {
        return toUser;
    }

    public void setFromUser( String inFromUser )
    {
        fromUser = inFromUser;
    }

    public void setToUser( String inToUser )
    {
        toUser = inToUser;
    }

    public String getClientIp()
    {
        return clientIp;
    }

    public String getServerIp()
    {
        return serverIp;
    }

    public String getServiceIp()
    {
        return serviceIp;
    }

    public void setClientIp( String inClientIp )
    {
        clientIp = inClientIp;
    }

    public void setServerIp( String inServerIp )
    {
        serverIp = inServerIp;
    }

    public void setServiceIp( String inServiceIp )
    {
        serviceIp = inServiceIp;
    }
}
