package com.np.tele.crm.pojos;

// default package
// Generated Mar 4, 2015 3:06:56 PM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

/**
 * CrmUserAssociationPojo generated by hbm2java
 */
public class CrmUserAssociationPojo
    implements java.io.Serializable
{
    private long   associationId;
    private String userId;
    private String associationType;
    private String associatedValue;
    private String createdBy;
    private Date   createdTime;
    private String lastModifiedBy;
    private Date   lastModifiedTime;
    private String status;

    public CrmUserAssociationPojo()
    {
    }

    public CrmUserAssociationPojo( Long associationId,
                                   String userId,
                                   String associationType,
                                   String associatedValue,
                                   String createdBy,
                                   String status )
    {
        this.associationId = associationId;
        this.userId = userId;
        this.associationType = associationType;
        this.associatedValue = associatedValue;
        this.createdBy = createdBy;
        this.status = status;
    }

    public CrmUserAssociationPojo( Long associationId,
                                   String userId,
                                   String associationType,
                                   String associatedValue,
                                   String createdBy,
                                   Date createdTime,
                                   String lastModifiedBy,
                                   Date lastModifiedTime,
                                   String status )
    {
        this.associationId = associationId;
        this.userId = userId;
        this.associationType = associationType;
        this.associatedValue = associatedValue;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
        this.status = status;
    }

    public long getAssociationId()
    {
        return associationId;
    }

    public void setAssociationId( long associationId )
    {
        this.associationId = associationId;
    }

    public String getUserId()
    {
        return this.userId;
    }

    public void setUserId( String userId )
    {
        this.userId = userId;
    }

    public String getAssociationType()
    {
        return this.associationType;
    }

    public void setAssociationType( String associationType )
    {
        this.associationType = associationType;
    }

    public String getAssociatedValue()
    {
        return this.associatedValue;
    }

    public void setAssociatedValue( String associatedValue )
    {
        this.associatedValue = associatedValue;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date createdTime )
    {
        this.createdTime = createdTime;
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date lastModifiedTime )
    {
        this.lastModifiedTime = lastModifiedTime;
    }

    public String getStatus()
    {
        return this.status;
    }

    public void setStatus( String status )
    {
        this.status = status;
    }

    @Override
    public String toString()
    {
        StringBuilder builder = new StringBuilder();
        builder.append( "CrmUserAssociationPojo [associationId=" ).append( associationId ).append( ", userId=" )
                .append( userId ).append( ", associationType=" ).append( associationType )
                .append( ", associatedValue=" ).append( associatedValue ).append( ", createdBy=" ).append( createdBy )
                .append( ", createdTime=" ).append( createdTime ).append( ", lastModifiedBy=" ).append( lastModifiedBy )
                .append( ", lastModifiedTime=" ).append( lastModifiedTime ).append( ", status=" ).append( status )
                .append( "]" );
        return builder.toString();
    }

    @Override
    public int hashCode()
    {
        final int prime = 31;
        int result = 1;
        result = prime * result + ( ( associatedValue == null ) ? 0 : associatedValue.hashCode() );
        result = prime * result + ( ( associationType == null ) ? 0 : associationType.hashCode() );
        result = prime * result + ( ( userId == null ) ? 0 : userId.hashCode() );
        return result;
    }

    @Override
    public boolean equals( Object obj )
    {
        if ( this == obj )
            return true;
        if ( obj == null )
            return false;
        if ( getClass() != obj.getClass() )
            return false;
        CrmUserAssociationPojo other = (CrmUserAssociationPojo) obj;
        if ( associatedValue == null )
        {
            if ( other.associatedValue != null )
                return false;
        }
        else if ( !associatedValue.equals( other.associatedValue ) )
            return false;
        if ( associationType == null )
        {
            if ( other.associationType != null )
                return false;
        }
        else if ( !associationType.equals( other.associationType ) )
            return false;
        if ( userId == null )
        {
            if ( other.userId != null )
                return false;
        }
        else if ( !userId.equals( other.userId ) )
            return false;
        return true;
    }
}
