package com.np.tele.crm.pojos;

// default package
// Generated Sep 30, 2013 12:14:22 PM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

/**
 * CrmUserMappingPojo generated by hbm2java
 */
public class CrmUserMappingPojo
    implements java.io.Serializable
{
    private Long    userMappingId;
    private String  userId;
    private String  mappedUserId;
    private String  mappingType;
    private String  createdBy;
    private Date    createdTime;
    private String  lastModifiedBy;
    private Date    lastModifiedTime;
    private String  status;
    private String  displayCreatedTime;
    private String  displayLastModifiedTime;
    private boolean editable;

    public CrmUserMappingPojo()
    {
    }

    public CrmUserMappingPojo( Long userMappingId,
                               String userId,
                               String mappedUserId,
                               String mappingType,
                               String createdBy )
    {
        this.userMappingId = userMappingId;
        this.userId = userId;
        this.mappedUserId = mappedUserId;
        this.mappingType = mappingType;
        this.createdBy = createdBy;
    }

    public CrmUserMappingPojo( Long userMappingId,
                               String userId,
                               String mappedUserId,
                               String mappingType,
                               String createdBy,
                               Date createdTime,
                               String lastModifiedBy,
                               Date lastModifiedTime,
                               String status )
    {
        this.userMappingId = userMappingId;
        this.userId = userId;
        this.mappedUserId = mappedUserId;
        this.mappingType = mappingType;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
        this.status = status;
    }

    public Long getUserMappingId()
    {
        return userMappingId;
    }

    public void setUserMappingId( Long userMappingId )
    {
        this.userMappingId = userMappingId;
    }

    public String getUserId()
    {
        return this.userId;
    }

    public void setUserId( String userId )
    {
        this.userId = userId;
    }

    public String getMappedUserId()
    {
        return this.mappedUserId;
    }

    public void setMappedUserId( String mappedUserId )
    {
        this.mappedUserId = mappedUserId;
    }

    public String getMappingType()
    {
        return this.mappingType;
    }

    public void setMappingType( String mappingType )
    {
        this.mappingType = mappingType;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date inCreatedTime )
    {
        createdTime = inCreatedTime;
        /*if ( StringUtils.isEmpty( displayCreatedTime ) && StringUtils.isValidObj( createdTime ) )
        {
            displayCreatedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( createdTime );
        }*/
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date inLastModifiedTime )
    {
        lastModifiedTime = inLastModifiedTime;
       /* if ( StringUtils.isEmpty( displayLastModifiedTime ) && StringUtils.isValidObj( lastModifiedTime ) )
        {
            displayLastModifiedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( lastModifiedTime );
        }*/
    }

    public String getStatus()
    {
        return this.status;
    }

    public void setStatus( String status )
    {
        this.status = status;
    }

    public String getDisplayCreatedTime()
    {
        return displayCreatedTime;
    }

    public void setDisplayCreatedTime( String inDisplayCreatedTime )
    {
        displayCreatedTime = inDisplayCreatedTime;
    }

    public String getDisplayLastModifiedTime()
    {
        return displayLastModifiedTime;
    }

    public void setDisplayLastModifiedTime( String inDisplayLastModifiedTime )
    {
        displayLastModifiedTime = inDisplayLastModifiedTime;
    }

    public boolean isEditable()
    {
        return editable;
    }

    public void setEditable( boolean inEditable )
    {
        editable = inEditable;
    }
}
