package com.np.tele.crm.pojos;

// Generated Dec 3, 2015 12:25:04 PM by Hibernate Tools 3.4.0.CR1

/**
 * CrmWorkflowSequence generated by hbm2java
 */
public class CrmWorkflowSequence implements java.io.Serializable {

	private Long id;

	public CrmWorkflowSequence() {
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

}
