package com.np.tele.crm.pojos;

// default package
// Generated 5 Jul, 2013 11:15:37 AM by Hibernate Tools 3.4.0.CR1
import java.io.Serializable;
import java.util.Arrays;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * EmailTemplate generated by hbm2java
 */
public class EmailTemplatePojo
    implements Serializable
{
    private long                emailTemplateId;
    private ProjectsPojo        projects;
    private String              emailTemplateName;
    private byte[]              emailTemplate;
    private String              emailServer;
    private String              emailFrom;
    private String              emailSubject;
    private String              createdBy;
    private Date                createdTime;
    private String              lastModifiedBy;
    private Date                lastModifiedTime;
    private String              status;
    private Set<EmailCcBccPojo> emailCcBccs = new HashSet<EmailCcBccPojo>( 0 );
    private String              displayCreatedTime;
    private String              displayLastModifiedTime;
    private List<String>        attachmentPaths;

    /* private Set      eventTemplateses = new HashSet( 0 );*/
    public EmailTemplatePojo()
    {
    }

    public EmailTemplatePojo( Long emailTemplateId,
                              ProjectsPojo projects,
                              String emailTemplateName,
                              byte[] emailTemplate,
                              String emailServer,
                              String emailFrom,
                              String createdBy,
                              String lastModifiedBy,
                              Date lastModifiedTime )
    {
        this.emailTemplateId = emailTemplateId;
        this.projects = projects;
        this.emailTemplateName = emailTemplateName;
        this.emailTemplate = emailTemplate;
        this.emailServer = emailServer;
        this.emailFrom = emailFrom;
        this.createdBy = createdBy;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
    }

    public EmailTemplatePojo( Long emailTemplateId,
                              ProjectsPojo projects,
                              String emailTemplateName,
                              byte[] emailTemplate,
                              String emailServer,
                              String emailFrom,
                              String emailSubject,
                              String createdBy,
                              Date createdTime,
                              String lastModifiedBy,
                              Date lastModifiedTime,
                              String status,
                              Set emailCcBccs,
                              Set eventTemplateses )
    {
        this.emailTemplateId = emailTemplateId;
        this.projects = projects;
        this.emailTemplateName = emailTemplateName;
        this.emailTemplate = emailTemplate;
        this.emailServer = emailServer;
        this.emailFrom = emailFrom;
        this.emailSubject = emailSubject;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
        this.status = status;
        this.emailCcBccs = emailCcBccs;
        /* this.eventTemplateses = eventTemplateses;*/
    }

    public List<String> getAttachmentPaths()
    {
        return attachmentPaths;
    }

    public void setAttachmentPaths( List<String> inAttachmentPaths )
    {
        attachmentPaths = inAttachmentPaths;
    }

    public long getEmailTemplateId()
    {
        return emailTemplateId;
    }

    public void setEmailTemplateId( long emailTemplateId )
    {
        this.emailTemplateId = emailTemplateId;
    }

    public ProjectsPojo getProjects()
    {
        return projects;
    }

    public void setProjects( ProjectsPojo projects )
    {
        this.projects = projects;
    }

    public String getEmailTemplateName()
    {
        return emailTemplateName;
    }

    public void setEmailTemplateName( String emailTemplateName )
    {
        this.emailTemplateName = emailTemplateName;
    }

    public byte[] getEmailTemplate()
    {
        return emailTemplate;
    }

    public void setEmailTemplate( byte[] emailTemplate )
    {
        this.emailTemplate = emailTemplate;
    }

    public String getEmailServer()
    {
        return emailServer;
    }

    public void setEmailServer( String emailServer )
    {
        this.emailServer = emailServer;
    }

    public String getEmailFrom()
    {
        return emailFrom;
    }

    public void setEmailFrom( String emailFrom )
    {
        this.emailFrom = emailFrom;
    }

    public String getEmailSubject()
    {
        return emailSubject;
    }

    public void setEmailSubject( String emailSubject )
    {
        this.emailSubject = emailSubject;
    }

    public String getCreatedBy()
    {
        return createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return createdTime;
    }

    public void setCreatedTime( Date inCreatedTime )
    {
        createdTime = inCreatedTime;
        /*if ( StringUtils.isEmpty( displayCreatedTime ) && StringUtils.isValidObj( createdTime ) )
        {
            displayCreatedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( createdTime );
        }*/
    }

    public String getLastModifiedBy()
    {
        return lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return lastModifiedTime;
    }

    public void setLastModifiedTime( Date inLastModifiedTime )
    {
        lastModifiedTime = inLastModifiedTime;
       /* if ( StringUtils.isEmpty( displayLastModifiedTime ) && StringUtils.isValidObj( lastModifiedTime ) )
        {
            displayLastModifiedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( lastModifiedTime );
        }*/
    }

    public String getStatus()
    {
        return status;
    }

    public void setStatus( String status )
    {
        this.status = status;
    }

    public Set<EmailCcBccPojo> getEmailCcBccs()
    {
        return emailCcBccs;
    }

    public void setEmailCcBccs( Set<EmailCcBccPojo> emailCcBccs )
    {
        this.emailCcBccs = emailCcBccs;
    }

    public String getDisplayCreatedTime()
    {
        return displayCreatedTime;
    }

    public void setDisplayCreatedTime( String inDisplayCreatedTime )
    {
        displayCreatedTime = inDisplayCreatedTime;
    }

    public String getDisplayLastModifiedTime()
    {
        return displayLastModifiedTime;
    }

    public void setDisplayLastModifiedTime( String inDisplayLastModifiedTime )
    {
        displayLastModifiedTime = inDisplayLastModifiedTime;
    }

    @Override
    public String toString()
    {
        StringBuilder builder = new StringBuilder();
        builder.append( "EmailTemplatePojo [emailTemplateId=" ).append( emailTemplateId ).append( ", projects=" )
                .append( projects ).append( ", emailTemplateName=" ).append( emailTemplateName )
                .append( ", emailTemplate=" ).append( Arrays.toString( emailTemplate ) ).append( ", emailServer=" )
                .append( emailServer ).append( ", emailFrom=" ).append( emailFrom ).append( ", emailSubject=" )
                .append( emailSubject ).append( ", createdBy=" ).append( createdBy ).append( ", createdTime=" )
                .append( createdTime ).append( ", lastModifiedBy=" ).append( lastModifiedBy )
                .append( ", lastModifiedTime=" ).append( lastModifiedTime ).append( ", status=" ).append( status )
                .append( ", emailCcBccs=" ).append( emailCcBccs ).append( "]" );
        return builder.toString();
    }
    /*
        public Set getEmailCcBccs()
        {
            return this.emailCcBccs;
        }

        public void setEmailCcBccs( Set emailCcBccs )
        {
            this.emailCcBccs = emailCcBccs;
        }

        public Set getEventTemplateses()
        {
            return this.eventTemplateses;
        }

        public void setEventTemplateses( Set eventTemplateses )
        {
            this.eventTemplateses = eventTemplateses;
        }*/
}
