package com.np.tele.crm.pojos;

// Generated 5 Jul, 2013 11:15:37 AM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

import javax.xml.bind.annotation.XmlTransient;

import com.np.tele.crm.constants.IDateConstants;
import com.np.tele.crm.utils.StringUtils;

/**
 * EmailCcBcc generated by hbm2java
 */
public class EmailCcBccPojo
    implements java.io.Serializable
{
    private Long              recordId;
    private String            emailId;
    private String            emailType;
    private String            lastModifiedBy;
    private Date              lastModifiedTime;
    private String            status;
    private long              emailTemplateId;
    private EmailTemplatePojo emailTemplatePojo;
    private String            displayLastModifiedTime;

    @XmlTransient
    public EmailTemplatePojo getEmailTemplatePojo()
    {
        return emailTemplatePojo;
    }

    public void setEmailTemplatePojo( EmailTemplatePojo inEmailTemplatePojo )
    {
        emailTemplatePojo = inEmailTemplatePojo;
    }

    public EmailCcBccPojo()
    {
    }

    public EmailCcBccPojo( Long recordId, String emailId, String lastModifiedBy, Date lastModifiedTime )
    {
        this.recordId = recordId;
        this.emailId = emailId;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
    }

    public EmailCcBccPojo( Long recordId,
                           String emailId,
                           String emailType,
                           String lastModifiedBy,
                           Date lastModifiedTime,
                           String status )
    {
        this.recordId = recordId;
        this.emailId = emailId;
        this.emailType = emailType;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
        this.status = status;
    }

    public Long getRecordId()
    {
        return recordId;
    }

    public void setRecordId( Long recordId )
    {
        this.recordId = recordId;
    }

    public String getEmailId()
    {
        return this.emailId;
    }

    public void setEmailId( String emailId )
    {
        this.emailId = emailId;
    }

    public String getEmailType()
    {
        return this.emailType;
    }

    public void setEmailType( String emailType )
    {
        this.emailType = emailType;
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date inLastModifiedTime )
    {
        lastModifiedTime = inLastModifiedTime;
        if ( StringUtils.isEmpty( displayLastModifiedTime ) && StringUtils.isValidObj( lastModifiedTime ) )
        {
            displayLastModifiedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( lastModifiedTime );
        }
    }

    public String getStatus()
    {
        return this.status;
    }

    public void setStatus( String status )
    {
        this.status = status;
    }

    public long getEmailTemplateId()
    {
        return emailTemplateId;
    }

    public void setEmailTemplateId( long inEmailTemplateId )
    {
        emailTemplateId = inEmailTemplateId;
    }

    @Override
    public String toString()
    {
        StringBuilder builder = new StringBuilder();
        builder.append( "EmailCcBccPojo [recordId=" ).append( recordId ).append( ", emailId=" ).append( emailId )
                .append( ", emailType=" ).append( emailType ).append( ", lastModifiedBy=" ).append( lastModifiedBy )
                .append( ", lastModifiedTime=" ).append( lastModifiedTime ).append( ", status=" ).append( status )
                .append( "]" );
        return builder.toString();
    }
}
