package com.np.tele.crm.pojos;

// default package
// Generated 5 Jul, 2013 11:15:37 AM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

/**
 * EventTemplates generated by hbm2java
 */
public class EventTemplatesPojo
    implements java.io.Serializable
{
    private long              eventTemplateId;
    private EmailTemplatePojo emailTemplate;
    private SmsTemplatePojo   smsTemplate;
    private EventsPojo        events;
    private boolean           emailEnabled;
    private boolean           smsEnabled;
    private String            createdBy;
    private Date              createdTime;
    private String            lastModifiedBy;
    private Date              lastModifiedTime;
    private boolean           editable;
    private String            displayCreatedTime;
    private String            displayLastModifiedTime;

    public EventTemplatesPojo()
    {
    }

    public EventTemplatesPojo( Long eventTemplateId,
                               EventsPojo events,
                               String createdBy,
                               String lastModifiedBy,
                               Date lastModifiedTime )
    {
        this.eventTemplateId = eventTemplateId;
        this.events = events;
        this.createdBy = createdBy;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
    }

    public EventTemplatesPojo( Long eventTemplateId,
                               EmailTemplatePojo emailTemplate,
                               SmsTemplatePojo smsTemplate,
                               EventsPojo events,
                               boolean emailEnabled,
                               boolean smsEnabled,
                               String createdBy,
                               Date createdTime,
                               String lastModifiedBy,
                               Date lastModifiedTime )
    {
        this.eventTemplateId = eventTemplateId;
        this.emailTemplate = emailTemplate;
        this.smsTemplate = smsTemplate;
        this.events = events;
        this.emailEnabled = emailEnabled;
        this.smsEnabled = smsEnabled;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
    }

    public long getEventTemplateId()
    {
        return eventTemplateId;
    }

    public void setEventTemplateId( long eventTemplateId )
    {
        this.eventTemplateId = eventTemplateId;
    }

    public EmailTemplatePojo getEmailTemplate()
    {
        return this.emailTemplate;
    }

    public void setEmailTemplate( EmailTemplatePojo emailTemplate )
    {
        this.emailTemplate = emailTemplate;
    }

    public SmsTemplatePojo getSmsTemplate()
    {
        return smsTemplate;
    }

    public void setSmsTemplate( SmsTemplatePojo smsTemplate )
    {
        this.smsTemplate = smsTemplate;
    }

    public EventsPojo getEvents()
    {
        return this.events;
    }

    public void setEvents( EventsPojo events )
    {
        this.events = events;
    }

    public boolean isEmailEnabled()
    {
        return emailEnabled;
    }

    public void setEmailEnabled( boolean inEmailEnabled )
    {
        emailEnabled = inEmailEnabled;
    }

    public boolean isSmsEnabled()
    {
        return smsEnabled;
    }

    public void setSmsEnabled( boolean inSmsEnabled )
    {
        smsEnabled = inSmsEnabled;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date inCreatedTime )
    {
        createdTime = inCreatedTime;
        /*if ( StringUtils.isEmpty( displayCreatedTime ) && StringUtils.isValidObj( createdTime ) )
        {
            displayCreatedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( createdTime );
        }*/
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date inLastModifiedTime )
    {
        lastModifiedTime = inLastModifiedTime;
       /* if ( StringUtils.isEmpty( displayLastModifiedTime ) && StringUtils.isValidObj( lastModifiedTime ) )
        {
            displayLastModifiedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( lastModifiedTime );
        }*/
    }

    public boolean isEditable()
    {
        return editable;
    }

    public void setEditable( boolean inEditable )
    {
        editable = inEditable;
    }

    public String getDisplayCreatedTime()
    {
        return displayCreatedTime;
    }

    public void setDisplayCreatedTime( String inDisplayCreatedTime )
    {
        displayCreatedTime = inDisplayCreatedTime;
    }

    public String getDisplayLastModifiedTime()
    {
        return displayLastModifiedTime;
    }

    public void setDisplayLastModifiedTime( String inDisplayLastModifiedTime )
    {
        displayLastModifiedTime = inDisplayLastModifiedTime;
    }
}
