package com.np.tele.crm.pojos;

// default package
// Generated 5 Jul, 2013 11:15:37 AM by Hibernate Tools 3.4.0.CR1
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Groups generated by hbm2java
 */
public class GroupsPojo
    implements java.io.Serializable
{
    private long                 groupId;
    private String               groupName;
    private String               groupType;
    private String               groupDescription;
    private String               lastModifiedBy;
    private Date                 lastModifiedTime;
    private String               createdBy;
    private Date                 createdTime;
    private String               status;
    private Set<AccessGroupPojo> accessGroups = new HashSet<AccessGroupPojo>( 0 );
    // private Set<UserRolesPojo>   userRoleses  = new HashSet<UserRolesPojo>( 0 );
    private String               displayCreatedTime;
    private String               displayLastModifiedTime;

    //    public Set<UserRolesPojo> getUserRoleses()
    //    {
    //        return userRoleses;
    //    }
    //
    //    public void setUserRoleses( Set<UserRolesPojo> userRoleses )
    //    {
    //        this.userRoleses = userRoleses;
    //    }
    /* private Set    userRoleses  = new HashSet( 0 );*/
    public GroupsPojo()
    {
    }

    public GroupsPojo( Long groupId, String lastModifiedBy, Date lastModifiedTime, String createdBy )
    {
        this.groupId = groupId;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
        this.createdBy = createdBy;
    }

    public GroupsPojo( Long groupId,
                       String groupName,
                       String groupType,
                       String groupDescription,
                       String lastModifiedBy,
                       Date lastModifiedTime,
                       String createdBy,
                       Date createdTime,
                       String status,
                       Set<AccessGroupPojo> accessGroups,
                       Set userRoleses )
    {
        this.groupId = groupId;
        this.groupName = groupName;
        this.groupType = groupType;
        this.groupDescription = groupDescription;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.status = status;
        this.accessGroups = accessGroups;
        //        this.userRoleses = userRoleses;
    }

    public long getGroupId()
    {
        return groupId;
    }

    public void setGroupId( long groupId )
    {
        this.groupId = groupId;
    }

    public String getGroupName()
    {
        return this.groupName;
    }

    public void setGroupName( String groupName )
    {
        this.groupName = groupName;
    }

    public String getGroupType()
    {
        return this.groupType;
    }

    public void setGroupType( String groupType )
    {
        this.groupType = groupType;
    }

    public String getGroupDescription()
    {
        return this.groupDescription;
    }

    public void setGroupDescription( String groupDescription )
    {
        this.groupDescription = groupDescription;
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date inLastModifiedTime )
    {
        lastModifiedTime = inLastModifiedTime;
       /* if ( StringUtils.isEmpty( displayLastModifiedTime ) && StringUtils.isValidObj( lastModifiedTime ) )
        {
            displayLastModifiedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( lastModifiedTime );
        }*/
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date inCreatedTime )
    {
        createdTime = inCreatedTime;
       /* if ( StringUtils.isEmpty( displayCreatedTime ) && StringUtils.isValidObj( createdTime ) )
        {
            displayCreatedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( createdTime );
        }*/
    }

    public String getStatus()
    {
        return this.status;
    }

    public void setStatus( String status )
    {
        this.status = status;
    }

    public Set<AccessGroupPojo> getAccessGroups()
    {
        return accessGroups;
    }

    public void setAccessGroups( Set<AccessGroupPojo> accessGroups )
    {
        this.accessGroups = accessGroups;
    }

    public String getDisplayCreatedTime()
    {
        return displayCreatedTime;
    }

    public void setDisplayCreatedTime( String inDisplayCreatedTime )
    {
        displayCreatedTime = inDisplayCreatedTime;
    }

    public String getDisplayLastModifiedTime()
    {
        return displayLastModifiedTime;
    }

    public void setDisplayLastModifiedTime( String inDisplayLastModifiedTime )
    {
        displayLastModifiedTime = inDisplayLastModifiedTime;
    }

    @Override
    public String toString()
    {
        StringBuilder builder = new StringBuilder();
        builder.append( "GroupsPojo [groupId=" ).append( groupId ).append( ", groupName=" ).append( groupName )
                .append( ", groupType=" ).append( groupType ).append( ", status=" ).append( status )
                .append( ", accessGroups=" ).append( accessGroups ).append( "]" );
        return builder.toString();
    }
}
