package com.np.tele.crm.pojos;

import java.util.Date;

/**
 * LmsCrfMapping generated by hbm2java
 */
public class LmsCrfMappingPojo
    implements java.io.Serializable
{
    private Long   recordId;
    private long   lmsId;
    private String crfValue;
    private String createdBy;
    private Date   createdTime;

    public LmsCrfMappingPojo()
    {
    }

    public LmsCrfMappingPojo( Long recordId, long lmsId, String crfValue, String createdBy )
    {
        this.recordId = recordId;
        this.lmsId = lmsId;
        this.crfValue = crfValue;
        this.createdBy = createdBy;
    }

    public LmsCrfMappingPojo( Long recordId, long lmsId, String crfValue, String createdBy, Date createdTime )
    {
        this.recordId = recordId;
        this.lmsId = lmsId;
        this.crfValue = crfValue;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
    }

    public Long getRecordId()
    {
        return recordId;
    }

    public void setRecordId( Long recordId )
    {
        this.recordId = recordId;
    }

    public long getLmsId()
    {
        return lmsId;
    }

    public void setLmsId( long lmsId )
    {
        this.lmsId = lmsId;
    }

    public String getCrfValue()
    {
        return this.crfValue;
    }

    public void setCrfValue( String crfValue )
    {
        this.crfValue = crfValue;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date createdTime )
    {
        this.createdTime = createdTime;
    }
}
