package com.np.tele.crm.pojos;

import java.util.Date;

import com.np.tele.crm.constants.IDateConstants;
import com.np.tele.crm.utils.StringUtils;

/**
 * Lead generated by hbm2java
 */
public class LMSPojo
    implements java.io.Serializable
{
    private static final long serialVersionUID = 836229904102238906L;
    private long              lmsId;
    private String            leadId;
    private String            customerName;
    private long              ctiNumber;
    private long              contactNumber;
    private String            state;
    private String            city;
    private String            area;
    private String            locality;
    private String            houseNumber;
    private String            landmark;
    private String            feasibility;
    private String            product;
    private String            lmsStage;
    private String            leadSource;
    private String            referralSource;
    private String            createdBy;
    private Date              createdTime;
    private String            lastModifiedBy;
    private Date              lastModifiedTime;
    private String            status;
    private Integer           pincode;
    private String            emailId;
    private String            displayCreatedTime;
    private String            displayLastModifiedTime;
    private long              partnerId;
    private boolean           unRead;
    private long              inboxId;
    private String            previousStage;
    private String            currentUser;
    private String            remarks;

    public LMSPojo()
    {
    }

    public LMSPojo( String leadId, String lmsStage, String leadSource, String createdBy )
    {
        this.leadId = leadId;
        this.lmsStage = lmsStage;
        this.leadSource = leadSource;
        this.createdBy = createdBy;
    }

    public LMSPojo( String leadId,
                    String customerName,
                    long ctiNumber,
                    long contactNumber,
                    String state,
                    String city,
                    String area,
                    String locality,
                    String houseNumber,
                    String landmark,
                    String feasibility,
                    String product,
                    String lmsStage,
                    String leadSource,
                    String referralSource,
                    String createdBy,
                    Date createdTime,
                    String lastModifiedBy,
                    Date lastModifiedTime,
                    String status )
    {
        this.leadId = leadId;
        this.customerName = customerName;
        this.ctiNumber = ctiNumber;
        this.contactNumber = contactNumber;
        this.state = state;
        this.city = city;
        this.area = area;
        this.locality = locality;
        this.houseNumber = houseNumber;
        this.landmark = landmark;
        this.feasibility = feasibility;
        this.product = product;
        this.lmsStage = lmsStage;
        this.leadSource = leadSource;
        this.referralSource = referralSource;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
        this.status = status;
    }

    public String getLeadId()
    {
        return leadId;
    }

    public void setLeadId( String leadId )
    {
        this.leadId = leadId;
    }

    public String getCustomerName()
    {
        return this.customerName;
    }

    public void setCustomerName( String customerName )
    {
        this.customerName = StringUtils.upperCase( customerName );
    }

    public long getCtiNumber()
    {
        return this.ctiNumber;
    }

    public void setCtiNumber( long ctiNumber )
    {
        this.ctiNumber = ctiNumber;
    }

    public long getContactNumber()
    {
        return this.contactNumber;
    }

    public void setContactNumber( long contactNumber )
    {
        this.contactNumber = contactNumber;
    }

    public String getState()
    {
        return this.state;
    }

    public void setState( String state )
    {
        this.state = state;
    }

    public String getCity()
    {
        return this.city;
    }

    public void setCity( String city )
    {
        this.city = city;
    }

    public String getArea()
    {
        return this.area;
    }

    public void setArea( String area )
    {
        this.area = StringUtils.upperCase( area );
    }

    public String getLocality()
    {
        return this.locality;
    }

    public void setLocality( String locality )
    {
        this.locality = StringUtils.upperCase( locality );
    }

    public String getHouseNumber()
    {
        return this.houseNumber;
    }

    public void setHouseNumber( String houseNumber )
    {
        this.houseNumber = StringUtils.upperCase( houseNumber );
    }

    public String getLandmark()
    {
        return this.landmark;
    }

    public void setLandmark( String landmark )
    {
        this.landmark = StringUtils.upperCase( landmark );
    }

    public String getFeasibility()
    {
        return this.feasibility;
    }

    public void setFeasibility( String feasibility )
    {
        this.feasibility = feasibility;
    }

    public String getProduct()
    {
        return this.product;
    }

    public void setProduct( String product )
    {
        this.product = product;
    }

    public String getLmsStage()
    {
        return this.lmsStage;
    }

    public void setLmsStage( String lmsStage )
    {
        this.lmsStage = lmsStage;
    }

    public String getLeadSource()
    {
        return this.leadSource;
    }

    public void setLeadSource( String leadSource )
    {
        this.leadSource = leadSource;
    }

    public String getReferralSource()
    {
        return this.referralSource;
    }

    public void setReferralSource( String referralSource )
    {
        this.referralSource = referralSource;
    }

    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date inCreatedTime )
    {
        createdTime = inCreatedTime;
       /* if ( StringUtils.isEmpty( displayCreatedTime ) && StringUtils.isValidObj( createdTime ) )
        {
            displayCreatedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( createdTime );
        }*/
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date inLastModifiedTime )
    {
        lastModifiedTime = inLastModifiedTime;
        /*if ( StringUtils.isEmpty( displayLastModifiedTime ) && StringUtils.isValidObj( lastModifiedTime ) )
        {
            displayLastModifiedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( lastModifiedTime );
        }*/
    }

    public String getStatus()
    {
        return this.status;
    }

    public void setStatus( String status )
    {
        this.status = status;
    }

    public String getEmailId()
    {
        return emailId;
    }

    public void setEmailId( String emailId )
    {
        this.emailId = emailId;
    }

    public String getDisplayCreatedTime()
    {
        return displayCreatedTime;
    }

    public void setDisplayCreatedTime( String inDisplayCreatedTime )
    {
        displayCreatedTime = inDisplayCreatedTime;
    }

    public String getDisplayLastModifiedTime()
    {
        return displayLastModifiedTime;
    }

    public void setDisplayLastModifiedTime( String inDisplayLastModifiedTime )
    {
        displayLastModifiedTime = inDisplayLastModifiedTime;
    }

    public Integer getPincode()
    {
        return pincode;
    }

    public void setPincode( Integer pincode )
    {
        this.pincode = pincode;
    }

    public long getLmsId()
    {
        return lmsId;
    }

    public void setLmsId( long lmsId )
    {
        this.lmsId = lmsId;
    }

    public long getPartnerId()
    {
        return partnerId;
    }

    public void setPartnerId( long partnerId )
    {
        this.partnerId = partnerId;
    }

    public boolean isUnRead()
    {
        return unRead;
    }

    public void setUnRead( boolean inUnRead )
    {
        unRead = inUnRead;
    }

    public long getInboxId()
    {
        return inboxId;
    }

    public void setInboxId( long inInboxId )
    {
        inboxId = inInboxId;
    }

    public String getPreviousStage()
    {
        return previousStage;
    }

    public void setPreviousStage( String previousStage )
    {
        this.previousStage = previousStage;
    }

    public String getCurrentUser()
    {
        return currentUser;
    }

    public void setCurrentUser( String currentUser )
    {
        this.currentUser = currentUser;
    }

    public String getRemarks()
    {
        return remarks;
    }

    public void setRemarks( String inRemarks )
    {
        remarks = inRemarks;
    }

    @Override
    public String toString()
    {
        return "LMSPojo [lmsId=" + lmsId + ", leadId=" + leadId + ", customerName=" + customerName + ", ctiNumber="
                + ctiNumber + ", contactNumber=" + contactNumber + ", state=" + state + ", city=" + city + ", area="
                + area + ", locality=" + locality + ", houseNumber=" + houseNumber + ", landmark=" + landmark
                + ", feasibility=" + feasibility + ", product=" + product + ", lmsStage=" + lmsStage + ", leadSource="
                + leadSource + ", referralSource=" + referralSource + ", createdBy=" + createdBy + ", createdTime="
                + createdTime + ", lastModifiedBy=" + lastModifiedBy + ", lastModifiedTime=" + lastModifiedTime
                + ", status=" + status + ", pincode=" + pincode + ", emailId=" + emailId + ", displayCreatedTime="
                + displayCreatedTime + ", displayLastModifiedTime=" + displayLastModifiedTime + ", partnerId="
                + partnerId + ", unRead=" + unRead + ", inboxId=" + inboxId + ", previousStage=" + previousStage
                + ", currentUser=" + currentUser + ", remarks=" + remarks + "]";
    }
    
}
