package com.np.tele.crm.pojos;

// default package
// Generated 28 Aug, 2013 11:28:13 AM by Hibernate Tools 3.4.0.CR1
import java.util.Date;

/**
 * SocietyNetworkPartnerPojo generated by hbm2java
 */
public class SocietyNetworkPartnerPojo
    implements java.io.Serializable
{
    private Long   id;
    //private SocietyPojo societyPojo;
    // private PartnerPojo partner;
    private String createdBy;
    private Date   createdTime;
    private String lastModifiedBy;
    private Date   lastModifiedTime;
    private String status;
    private long   societyId;
    private String productName;
    private String displayCreatedTime;
    private String displayLastModifiedTime;
    private long   partnerId;
    private long   rfsDus;

    public SocietyNetworkPartnerPojo()
    {
    }

    public SocietyNetworkPartnerPojo( Long id, SocietyPojo societyPojo, PartnerPojo partner, String createdBy )
    {
        this.id = id;
        //this.societyPojo = societyPojo;
        //this.partner = partner;
        this.createdBy = createdBy;
    }

    public SocietyNetworkPartnerPojo( Long id,
                                      SocietyPojo societyPojo,
                                      PartnerPojo partner,
                                      String createdBy,
                                      Date createdTime,
                                      String lastModifiedBy,
                                      Date lastModifiedTime,
                                      String status )
    {
        this.id = id;
        // this.societyPojo = societyPojo;
        //this.partner = partner;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedTime = lastModifiedTime;
        this.status = status;
    }

    public String getProductName()
    {
        return productName;
    }

    public void setProductName( String productName )
    {
        this.productName = productName;
    }

    /* public SocietyPojo getSociety()
     {
         return this.societyPojo;
     }

     public void setSociety( SocietyPojo societyPojo )
     {
         this.societyPojo = societyPojo;
     }*/
    /*    public PartnerPojo getPartner()
        {
            return this.partner;
        }
        public void setPartner( PartnerPojo partner )
        {
            this.partner = partner;
        }*/
    public String getCreatedBy()
    {
        return this.createdBy;
    }

    public void setCreatedBy( String createdBy )
    {
        this.createdBy = createdBy;
    }

    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    public void setCreatedTime( Date inCreatedTime )
    {
        createdTime = inCreatedTime;
//        if ( StringUtils.isEmpty( displayCreatedTime ) && StringUtils.isValidObj( createdTime ) )
//        {
//            displayCreatedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( createdTime );
//        }
    }

    public String getLastModifiedBy()
    {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy( String lastModifiedBy )
    {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedTime()
    {
        return this.lastModifiedTime;
    }

    public void setLastModifiedTime( Date inLastModifiedTime )
    {
        lastModifiedTime = inLastModifiedTime;
        /*if ( StringUtils.isEmpty( displayLastModifiedTime ) && StringUtils.isValidObj( lastModifiedTime ) )
        {
            displayLastModifiedTime = IDateConstants.SDF_DD_MMM_YYYY_HH_MM_SS.format( lastModifiedTime );
        }*/
    }

    public String getStatus()
    {
        return this.status;
    }

    public void setStatus( String status )
    {
        this.status = status;
    }

    public String getDisplayCreatedTime()
    {
        return displayCreatedTime;
    }

    public void setDisplayCreatedTime( String inDisplayCreatedTime )
    {
        displayCreatedTime = inDisplayCreatedTime;
    }

    public String getDisplayLastModifiedTime()
    {
        return displayLastModifiedTime;
    }

    public void setDisplayLastModifiedTime( String inDisplayLastModifiedTime )
    {
        displayLastModifiedTime = inDisplayLastModifiedTime;
    }

    public Long getId()
    {
        return id;
    }

    public void setId( Long id )
    {
        this.id = id;
    }

    public long getSocietyId()
    {
        return societyId;
    }

    public void setSocietyId( long societyId )
    {
        this.societyId = societyId;
    }

    public long getPartnerId()
    {
        return partnerId;
    }

    public void setPartnerId( long partnerId )
    {
        this.partnerId = partnerId;
    }

    public long getRfsDus()
    {
        return rfsDus;
    }

    public void setRfsDus( long rfsDus )
    {
        this.rfsDus = rfsDus;
    }
}
