package com.np.tele.crm.constants;

public enum CRMEvents {
    CREATE_USER(1, "CREATE_USER"), 
    UPDATE_USER(2, "UPDATE_USER"), 
    RESET_PASSWORD(3, "RESET_PASSWORD"), 
    CHANGE_PASSWORD(4, "CHANGE_PASSWORD"), 
    CHANGE_STATUS(5, "CHANGE_STATUS"),     
    CREATE_ROLE_GROUP(7, "CREATE_ROLE_GROUP"), 
    UPDATE_ROLE_GROUP(8, "UPDATE_ROLE_GROUP"), 
    CREATE_PARAMETER_GROUP(9,"CREATE_PARAMETER_GROUP"), 
    UPDATE_PARAMETER_GROUP(10, "UPDATE_PARAMETER_GROUP"), 
    CREATE_PARTNER(11,"CREATE_PARTNER"), 
    UPDATE_PARTNER(12, "UPDATE_PARTNER"), 
    UPDATE_OPTION82(13, "UPDATE_OPTION82"), 
    CREATE_EVENT_TEMPLATE(14, "CREATE_EVENT_TEMPLATE"), 
    UPDATE_EVENT_TEMPLATE(14, "UPDATE_EVENT_TEMPLATE"),
    //Lead Events
    CREATE_LEAD(6, "CREATE_LEAD", "Lead Generated"), 
    CLOSE_LEAD_NON_FEASIBLE(6, "CL_LD_NF"), 
    SAVE_LEAD(15, "SAVE_LEAD", "Lead Saved"), 
    CLOSE_LEAD(16, "CLOSE_LEAD", "Lead Closed"),
    FORWARD_LEAD(17, "FORWARD_LEAD", "Lead Forwarded"),
    MATURE_LEAD(18, "MATURE_LEAD", "Lead Matured"),
    LEAD_INTIMATION_AM(18,"LEAD_INTIMATION_AM","Lead Intimation to AM"),
    BACKROUTE_LEAD(19, "BACKROUTE_LEAD","Lead Back Routed"),
    PAYMENT_RECIEVED(19, "PAYMENT_RECIEVED"),
    UPDATE_NASPORTID(13, "UPDATE_NASPORTID"),
    OPEN_SR_COMPLAINT(21, "OPEN_SR_COMPLAINT"),
    OPEN_SR_REQUEST(21, "OPEN_SR_REQUEST"),
    RESOVLE_SERVICE_REQUEST(22, "RESOVLE_SERVICE_REQUEST"),
    CLOSE_SERVICE_REQUEST(23, "CLOSE_SERVICE_REQUEST"),
    REOPEN_SERVICE_REQUEST(24, "REOPEN_SERVICE_REQUEST"),
    SEND_LEGAL_MAIL(25,"SEND_LEGAL_MAIL"),
    CHEQUE_BOUNCE(26,"NRL"),
    RESET_WIFI_SECURITY_KEY(96,"RESET_WIFI_SECURITY_KEY"),
    RESET_WIFI_SECURITY_KEY_WITH_SMS(97,"RESET_WIFI_SECURITY_KEY_WITH_SMS"),
    // CSP Related Internal Events
    INVENTORY_SHORTAGE(41,"INVENTORY_SHORTAGE"),
    // - Customer Related Events
    //CRF_SUBMIT_FT(50, "CRF_SUBMIT_FT"),
    FORWARD_CRF(30, "FORWARD_CRF","CAF Forwarded"),
    BIND_MAC_ID(31,"BIND_MAC_ID","MAC Address Binded"),
    BIND_MAC_ID_EOC(31,"BIND_MAC_ID_EOC"),
    MY_ACCOUNT_CREATION(51,"MY_ACCOUNT_CREATION"),
    REGISTERED_EMAIL_VERIFICATION(26,"REGISTERED_EMAIL_VERIFICATION","Email Verification Link"),
    RESET_MY_ACCOUNT_PASSWORD(27,"RESET_MY_ACCOUNT_PASSWORD"),
    //CRF ON-Board Event
    WLCM_BB_PR_VRFD(52,"WLCM_BB_PR_VRFD"),
    WLCM_BB_PR_NVRFD(53,"WLCM_BB_PR_NVRFD"),
    WLCM_BB_PO_VRFD(54,"WLCM_BB_PO_VRFD"),
    WLCM_BB_PO_NVRFD(55,"WLCM_BB_PO_NVRFD"),
    WLCM_EOC_PR_VRFD(56,"WLCM_EOC_PR_VRFD"),
    WLCM_EOC_PR_NVRFD(57,"WLCM_EOC_PR_NVRFD"),
    WLCM_EOC_PO_VRFD(58,"WLCM_EOC_PO_VRFD"),
    WLCM_EOC_PO_NVRFD(59,"WLCM_EOC_PO_NVRFD"),
    WLCM_RF_PO_VRFD(60,"WLCM_RF_PO_VRFD"),
    WLCM_RF_PO_NVRFD(61,"WLCM_RF_PO_NVRFD"),
    //Finance Related Events
    UPDATE_PAYMENT_STATUS(71,"UPDATE_PAYMENT_STATUS"),
    UPDATE_REALISATION_STATUS(72,"UPDATE_REALISATION_STATUS"),
    POST_PAYMENT(73,"POST_PAYMENT"),
    POST_REVERSAL(74,"POST_REVERSAL"),
    BILLPAYMENT_SUCCESS(75,"BP_SU"),
    SEND_UNBILLED_USAGE(76,"SEND_UNBILLED_USAGE"),
    SEND_BILLED_USAGE(76,"SEND_BILLED_USAGE"),
    SEND_EBILL(76,"SEND_EBILL"),
    BILLPAYMENT_ATTEMPT(77,"BP_AT"),
    BILLPAYMENT_FAILURE(78,"BP_FL"),
    CMS_UPLOAD_STATUS(79,"CMS_UPLOAD_STATUS"),
    TICKET_IUD(80,"TICKET_IUD"),
    SLA_TKT(81,"SLA_TKT"),
    SLA_INA(82,"SLA_INA"),
    SLA_LMS(83,"SLA_LMS"),
    BIND_MAC_ID_INITIA(84,"BIND_MAC_ID_INITIA"),
    BIND_MAC_ID_EOC_INITIA(85,"BIND_MAC_ID_EOC_INITIA"),
    OP_TKT_REQ_INITIA(86,"OP_TKT_REQ_INITIA"),
    OP_TKT_CMP_INITIA(87,"OP_TKT_CMP_INITIA"),
    RES_TKT_INITIA(88,"RES_TKT_INITIA"),
    RO_TKT_INITIA(89,"RO_TKT_INITIA"),
    WLCM_EOC_PR_VRFD_INITIA(90,"WLCM_EOC_PR_VRFD_INITIA"),
    SEND_UNBILLED_USAGE_INITIA(91,"SEND_UNBILLED_USAGE_INITIA"),
    SEND_BILLED_USAGE_INITIA(92,"SEND_BILLED_USAGE_INITIA"),
    TICKET_IUD_INITIA(93,"TICKET_IUD_INITIA"),
    NRL_INITIA(94,"NRL_INITIA"),
    ASSIGN_EOC_SERVICE(95,"ASSIGN_EOC_SERVICE"),
    DECLARED_MASS_OUTAGE(96,"DECLARED_MASS_OUTAGE"),
    ADD_MASSOUTAGE(97,"ADD_MASS_OUTAGE"),
    RESOLVED_MASSOUTAGE(98,"RESOLVE_MASS_OUTAGE"),
    FT_APPROVAL(99,"FT_APPROVAL")
    ;
    
    private long   eventID;
    private String eventName;
    private String eventDescription;

    private CRMEvents( long inEventID, String inEventName )
    {
        this.eventID = inEventID;
        this.eventName = inEventName;
    }
    private CRMEvents( long inEventID, String inEventName, String inEventDescription )
    {
        this.eventID = inEventID;
        this.eventName = inEventName;
        this.eventDescription = inEventDescription;
    }

    public long getEventID()
    {
        return eventID;
    }

    public String getEventName()
    {
        return eventName;
    }
    public String getEventDescription()
    {
        return eventDescription;
    }
    
}
