package com.np.tele.crm.constants;

public enum CRMParameter {
    EMAIL_ALERT("email"),                                                               
    SMS_ALERT("sms"), 
    EMAIL("EMAIL"), 
    SMS("SMS"), 
    NEXTRA("N"), 
    PARTNER("P"), 
    CRM_LOGIN("user.login"), 
    PARTNER_POJO("partnerpojo"), 
    CHANGE_STATUS("changeStatus"), 
    FORGET_PASSWORD("forgetPassword"), 
    CRM_ROLES("crmroles"), 
    ROLES_GROUP("R"), 
    PARAMETER_GROUP("P"), 
    CC("CC"), 
    BCC("BCC"), 
    CRM_PARAMETER("crmparameter"), 
    INTERNAL("I"), 
    EXTERNAL("E"), 
    CRM_ACTIVE_ROLE_GROUP("crmactiverolegroup"), 
    CRM_ACTIVE_PARAMETER_GROUP("crmactiveparametergroup"), 
    RESET_PASSWORD("resetpassword"), 
    ALERT("ALERT"), 
    VALDATION("VALDATION"), 
    TEMPLATE("TEMPLATE"), 
    USER("USER"), 
    ACCESS("ACCESS"), 
    COUNTRY("country"), 
    STATE("state"), 
    CITY("city"), 
    AREA("area"), 
    LOCALITY("locality"), 
    SOCIETY("society"), 
    USER_ACCESS("USER_ACCESS"), 
    GISMASTER("gismaster"), 
    USEREMAILID("USEREMAILID"), 
    USERMOBILENO("USERMOBILENO"), 
    YES("Y"), 
    NO("N"), 
    USERCURRENTPASSWORD("USERCURRENTPASSWORD"), 
    MYACCOUNTPASSWORD("MYACCOUNTPASSWORD"),
    VERIFY_ACCOUNT("varifyaccount"), 
    ACTIVATION_LINK("activationlink"), 
    BROWN("Brown"), 
    GREEN("Green"), 
    ALERTS_MASTER("alertmaster"), 
    VALIDATION_MASTER("validationmaster"), 
    MASTER("MASTER"), 
    PENDING_ALERTS("pendingalerts"), 
    FILEERRORHEADER("Fail Reason"), 
    PRODUCT("Product"),
    OLTTYPE("OltType"),
    FIELDTYPE("FieldType"), 
    PARTNER_TYPE("PartnerType"), 
    OPTION82("OPTION82"), 
    GIS("GIS"), 
    GISFILE_UPLOAD("GIS_UPLOAD"), 
    LMS("LMS"), 
    LEADEMAILID("LEADEMAILID"), 
    LEADCONTACTNUMBER("LEADCONTACTNUMBER"), 
    LEADCTINUMBER("LEADCTINUMBER"), 
    PERSONAL("Personal"), 
    GROUP("Group"), 
    LEADCLOSEREASON("CloseReason"), 
    APPOINTMENT_TIME("appointmentTime"), 
    MODE_OF_APPOINTMENT("modeOfAppointment"), 
    CRM_RCA_REASON("CrmRcaReason"), 
    CATEGORY("category"), 
    SUB_CATEGORY("subCategory"), 
    SUB_SUB_CATEGORY("subSubCategory"), 
    LMS_REFERRAL_SOURCE("lmsReferralSource"), 
    REFERRAL("Referral"), 
    LMS_CLOSE_REASON("lmsCloseReasion"), 
    REASON("REASON"), 
    PARTNEREMAILID("PARTNEREMAILID"), 
    CUSTOMER_EMAIL("CUSTOMER_EMAIL"), 
    CUSTOMER_RMN("CUSTOMER_RMN"),
    PARTNERMOBILENUMBER("PARTNERMOBILENUMBER"), 
    CONNECTION_TYPE("ConnectionType"), 
    VISA_TYPE("VisaType"), 
    DAY_OF_INSTALLATION("DayOfInstallation"), 
    CPE_STATUS("CPEStatus"), 
    BILLING_PREFERENCES("BillingPreferences"), 
    PAYMENT_MODE("PaymentMode"),
    DOCUMENTS("Documents"), 
    ADDRESS_PROOF("AddressProof"), 
    COMMON_PROOF("commonProof"), 
    NETWORK_CONNECTIVITY_INFO("networkConnectivityInfo"),
    INA("I&A"),
    INA_REFUSEL_REASON("I&ARefuselReason"),
    PAYMENT("paymnent"),
    REVERSAL("reversal"), 
    CMSFILE("cmsfile"), 
    CMSRECORDS("cmsrecords"),  
    PAYMENT_CHANNEL("PaymentChannel"),
    MATERIAL_DETAILS("MaterialDetials"),
    CUSTOMER_FEEDBACK("CustomerFeedback"),
    CHEQUE_REJECTION_REASON("paymentRejectionReason"),
    REALIZATION_STATUS_LIST("RealizationStatus"),
    PAYMENT_RECIEVED_STATUS_LIST("PaymentStatus"),
    PAYMENT_CASE_STATUS_LIST("CaseStatus"),
    INSTALLATION_STATUS_LIST("InstallationStatus"),
    ENTITY_TYPE_LIST("EntityType"),
    UPFRONT_PAYMENT("UpfrontPayment"),
    UPFRONT_POPUP_DETAIL("UpfrontPopUpDetail"),
    UPFRONTFILE("Upfront"),
    QRCCATEGORY("QrcCategory"),
    QRCSUBCATEGORY("QrcSubCategory"),
    QRCSUBSUBCATEGORY("QrcSubSubCategory"),
    EVENTS("Events"),
    SERVICE_REQUEST("SR"),
    SERVICE_TYPE("ServiceType"),
    PLAN_DETAILS_MASTER("planDetailsMaster"),
    CUSTOMER_INTERACTION("customerInteraction"),
    WHITELIST("whiteList"), 
    BULK_WHITELIST("bulkWhitelist"),
    BARRING_UNBARRING("BarringUnbarring"),
    DEPENDENT_FUNCTION_BINS("DependentFunctionBins"),
    INBOX("Inbox"),
    QRC_RCA_LIST("qrcRcaList"),
    QRC_RCA_REASONS("qrcRcaReasons"),
    SEND_LEGAL_MAIL("SendLegalMail"),
    DISTRIBUTOR_INVENTORY_LIST("DistributorInventoryList"), 
    INVENTORYEMAIL("INVENTORYEMAIL"),
    INVENTORYSMS("INVENTORYSMS"),
    MODIFY_ADDRESS("modifyAddress"),
    WAIVER("waiver"),
    MASS_OUTAGE("massOutage"),
    DEVICE_AND_NETWORK_DETAILS("DeviceAndNetworkDetails"),
    CRM_PARTNER_NETWORK_CONFIG("CrmPartnerNetworkConfig"),
    QRC_RCA_CONFIGURATIONS("QrcRcaConfigurations"),
    CRM_MAC_CHANGE("CrmMacChange"),
    CRM_OPTION82_CHANGE("CrmOption82Change"),
    CRM_CPE_CHANGE("CrmCPEChange"), 
    QRC_RESOLUTION_CODE("QrcResolutionCode"),
    POOLNAME("Poolname"),
    QRC_ATTRIBUTED_TO("QrcAttributedTo"),
    QRC_FB_MAPPINGS("qrcFBMappings"),
    QRC("QRC"),
    ACCESSORIES("accessories"),
    STATIC_IP("staticIP"),
    WIRING("wiring"),
    STATIC_IP_CHARGES("staticIPCharges"),
    CUST_ADDITIONAL_DETAILS("cust.additional.details"),
    PLAN_MIGRATION("PlanMigration"),
    SELFCARE_CATEGORY("selfcare.category"),
    SELFCARE_SERVICE_REQUEST("selfcare.service.request"),
//    TICKET_OTHER_DETAILS("ticket.other.details"),
    BOOSTER_USAGE_PAID("Usage Booster Paid"),
    BOOSTER_USAGE_FOC("Usage Booster FOC"),
    BOOSTER_SPEED_PAID("Speed Booster Paid"),
    BOOSTER_SPEED_FOC("Speed Booster FOC"),
    PLAN_BOOSTER("planBooster"),
    VAS("vas"),
    VAS_ACTIVATION_PAID("VAS Activate Paid"),
    VAS_ACTIVATION_FOC("VAS Activate FOC"),
    VAS_DEACTIVATION_PAID("VAS Deactivate Paid"),
    VAS_DEACTIVATION_FOC("VAS Deactivate FOC"), 
    PLAN_REACTIVATION("Plan Reactivation"),
    PAYMENT_GATEWAY("PaymentGateway"), 
    CUSTOMER_ID("CUSTOMERID"),
    PLAN_MIGRATION_POLICY("Plan Migration Policy"), 
    USAGE_DETAILS("usage details"),
    SEND_USAGE_DETAILS("send usage details"), PLAN_RENEWAL("Plan Renewal"),
    INITIATE("Initiate"),
    IFR_STAGE("IFR"),
    NETWORK_PARTNER("NP"),
    IFR_ADD_CHANGE("IFRAD"),
    POD_FILE_UPLOAD("POD"),
    REFUND("Refund"),
    SHIFTING_TYPE("ShiftingType"),
    ADDON_PLAN_MIGRATION_POLICY("addOnPlanMigrationPolicy"),
    SLA_ALERT("AL"),
    SLA_FORWARD("FW"),
    AUDIT_LOG("AuditLog"),
    SLA_LOG("SlaLog"),
    REMARKS("REMARKS"),
    RECIPIENTS("RECIPIENTS"),
    CURRENT_BIN("CURRENT_BIN"),
    CURRENT_OWNER("CURRENT_OWNER"),
    AREA_NAME("AREA_NAME"),
    SERVICE_NAME("SERVICE_NAME"),
    LEAD_ID("LEAD_ID"),
    CRFID("CRFID"),
    BIN_ASSIGN_TIME("BIN_ASSIGN_TIME"),
    TICKETID("TICKETID"),
    QRC_SUB_CATEGORY("QRC_SUB_CATEGORY"),
    QRC_SUB_SUB_CATEGORY("QRC_SUB_SUB_CATEGORY"),
    MOUNT_BOOSTER("MountBooster"),
    VALIDITY_EXTENSION("ValidityExtension"),
    FT_STAGE("FT"),
    FT_LEVEL1("FTL1"),
    FT_NETWORK_STAGE("FTL2"),
    CSD_OUTCALL_LEVEL2("CSDL2"),
    GIS_DETAILS("GISD"),
    IFR_EOC_LEVEL1("IFREOCL1"),
    CSD_OUTCALL_LEVEL3("CSDL3"),
    NOC_LEVEL1("NOCL1"),
    IFR_EOC_LEVEL2("IFREOCL2"),
    GIS_DETAILS_BY_ID("GISID"),
    BIND_MAC("MACBIND"),

    ;
    
    String parameter = null;

    private CRMParameter( String parameter )
    {
        this.parameter = parameter;
    }

    public String getParameter()
    {
        return parameter;
    }
}
