package com.np.tele.crm.constants;


public enum CRMServiceCode {
    //  Codes for User Management 002 - 020
    CRM001("CRM001", "Success"),
    CRM002("CRM002", "User ID or Password Not Found In Database"),
    CRM003("CRM003", "New Password Can Not be Same As Last password or Last Three Password "),
    CRM004("CRM004", "New Password or Old Password or User Name Can Not be Blank "),
    CRM005("CRM005", "Data Should be in Correct Format or Please provide mandatory fields"),
    CRM006("CRM006", "User already exist in database"),
    CRM007("CRM007", "Operation Is Not Correct"),
    CRM008("CRM008", "User Has Been Locked Please try after some time"),
    CRM009("CRM009", "User Has Been Expired"),
    CRM010("CRM010", "User Has Been Deleted"),
    CRM011("CRM011", "User Has Been Deactivate"),
    CRM012("CRM012", "New User"),
    CRM013("CRM013", "Find Null in Required Pojo"),
    CRM014("CRM014", "Record ID Not Found In Database"),
    CRM015("CRM015", "User Already Deleted, Can Not be Active"),
    CRM016("CRM016", "User Not In Active OR New OR Inactive State, Can Not be Lock"),
    CRM017("CRM017", "User Not in Lock State, Can Not be Expire"),
    CRM018("CRM018", "User Not in Expire State,  Can Not be Archive"),
    CRM019("CRM019", "Please Provide Correct Status of User"),
    CRM020("CRM020", "User ID or Email Id Not Match In Database"),
    //  Codes for Alerts Services 021 - 040
    CRM021("CRM021", "SMS Template not found in database."),
    CRM022("CRM022", "SMS Tempalte Not Left Blank."),
    CRM023("CRM023", "SMS Tempalte Name Not Left Blank."),
    CRM024("CRM024", "SMS Tempalte Created By Not Left Blank."),
    CRM025("CRM025", "SMS Type Not Left Blank."),
    CRM026("CRM026", "SMS Gateway Not Left Blank."),
    CRM027("CRM027", "Email Template not founnd in database."),
    CRM028("CRM028", "Email Tempalte Not Left Blank."),
    CRM029("CRM029", "Email Tempalte Name Not Left Blank."),
    CRM030("CRM030", "Email Tempalte Created By Not Left Blank."),
    CRM031("CRM031", "Email From Not Left Blank."),
    CRM032("CRM032", "Email Server Not Left Blank."),
    CRM033("CRM033", "Invalid Cc and Bcc."),
    CRM034("CRM034", "Email Tempalte can not Left Blank."),

    //CRM Master Data Code 041-060
    CRM041("CRM041","Please Provide Correct Pojo Name"),
    CRM042("CRM042","No Data Found"),
    CRM043("CRM043","Group Name Already Exist"),
    CRM044("CRM044","Project Name Not Left Blank"),
    CRM045("CRM045","Project Description Not Left Blank"),
    CRM046("CRM046","Project Type Not Left Blank"),
    CRM047("CRM047","Project Name Not Found in Database"),
    CRM051("CRM051","Group In Deleted State, Can Not Reactivate"),
    CRM052("CRM052","Group Not In Active State, Can Not Be Inactive"),
    CRM053("CRM053","Group Alredy Deleted"),
    CRM054("CRM054","Project Name Already Exist"),
    CRM055("CRM055","Parameters Name should be different."),
    CRM056("CRM056","Empty Parameters are not allow."),
    CRM057("CRM057","Parameters not found."),
    CRM058("CRM058","Found UserRoles Pojo Null"),
    CRM059("CRM059","From Date and To Date both are mandatory"),
    CRM060("CRM060","Partner Name Already Exist"),
    CRM061("CRM061","Partner Name Not Left Blank"),
    CRM062("CRM062","Partner's Chief Exceutive Name Not Left Blank"),
    CRM063("CRM063","Designation Name Not Left Blank"),
    CRM064("CRM064","Please Select the Type OF Bussiness"),
    CRM065("CRM065","Please Select the Type OF Partner"),
    CRM066("CRM066","Contact Person Name Not Left Blank"),
    CRM067("CRM067","Please Select the Department"),
    CRM068("CRM068","OLT Type can not be blank"),
    CRM069("CRM069","Business Type and Partner Type not selected"),
    CRM070("CRM070","Category Value Already Exist"),
    CRM071("CRM071","Some Cash Receipts were already exists."),
    //CRM072("CRM072","Plan Name is Already Exist"),
    // getting code 101-120 for user management
    CRM101("CRM101","Please Provide User ID"),
    CRM102("CRM102","Wrong old password"),
    CRM103("CRM103","Account verification link is broken."),
    CRM104("CRM104","User account not verified."),
    CRM105("CRM105","User Not in Pending State,  Can Not be Activate."),
    CRM106("CRM106","User already lock"),
    CRM107("CRM107","Account deactivate ,UserID or Email Id not found in database. "),
    CRM108("CRM108","New user, Account activation pending."),
    CRM109("CRM109","Please Provide Area"),
    CRM110("CRM110","Unable to find user"),
    CRM111("CRM111","Password reset successfully, but unable to send mail."),
    //for gis master data(151-200)
    CRM151("CRM151","Same Country Name Already Exist"),
    CRM152("CRM152","Same State Name Already Exist"),
    CRM153("CRM153","Same City Name Already Exist"),
    CRM154("CRM154","Same Area Name Already Exist"),
    CRM155("CRM155","Same Locality Name Already Exist"),
    CRM156("CRM156","Find CountryPojo Null"),
    CRM157("CRM157","Find StatePojo Null"),
    CRM158("CRM158","Find CityPojo Null"),
    CRM159("CRM159","Find AreaPojo Null"),
    CRM160("CRM160","Find LocalityPojo Null"),
    CRM161("CRM161","Society already exist."),
    CRM162("CRM162","Society already exist Updated with latest details."),
    

    //CRM Service Code For LMS (201-220)
    CRM201("CRM201","No User Present In DataBase For Forwarding Stage"),
    CRM202("CRM202","No User Present In DataBase For Particular User"),
    CRM203("CRM203","Lead details not valid, User is not privileged to view lead."),
    CRM204("CRM204","Lead ID doesn't exist."),

    // CRM CAP Service Code For I&A
    CRM301("CRM301","CAF Id Not Found In DataBase"),
    CRM302("CRM302","CAF Id Present In LMS Table"),
    CRM303("CRM303","CAF Id Present In Customer Details Table"),
    CRM304("CRM304","CAF Id Present In Customer Details Table AND Punched By another User. Can't Display."),
    CRM305("CRM305","Same Created User Active. User Can Modify the CAF."),
    CRM306("CRM306","User Can Only View the CAF. Not Created By Same User."),
    CRM307("CRM307","Duplicate Entry for CAF Id."),
    CRM308("CRM308","Already Exist."),
    CRM309("CRM309","Customer details not found."),
    CRM310("CRM310","Customer details not found In LMS For Product RF"),
    CRM311("CRM311","CAF not in Initiate or FT Reject Stage"),
    CRM312("CRM312","CAF not punched, User is not privileged to punch CAF."),
    CRM313("CRM313","Customer Activated succesfully"),
    CRM314("CRM314","Please enter Hexadecimal string for CPE Mac ID like 23aF.D3de.A12f"),
    CRM315("CRM315","ISR details not found, Please fill ISR details before submission."),
    CRM316("CRM316","Customer is not yet activated, Please activate customer by binding CPE Mac Address"),
    CRM317("CRM317","ISR date not found, Please provide ISR date before submission."),
    CRM318("CRM318","No customer present in system for this society"),
    CRM319("CRM319","Provided IP is already activated for other customer."),
    CRM320("CRM320","Customer is already activated, MAC change processed."),
    CRM321("CRM321","CAF ID already Linked with other CAF."),
    CRM322("CRM322","Customer is not Active."),
    CRM323("CRM323","Unable to modify Customer's Brand."),
    CRM324("CRM324","MAC Address is not still bind."),
    CRM325("CRM325","Customer is already on board/Canceled. Please go to Inbox."),
    CRM326("CRM326","Token is not valid."),
    CRM327("CRM327","Token has been expired."),
    CRM328("CRM328","Your email id is already verified."),
    // CODE For QRC
    CRM401("CRM401","NO Mapping Bin Found For Particular Category"),
    CRM402("CRM402","Provided Ticket ID doesn't exist, please provide valid open Ticket ID"),
    CRM403("CRM403","Can't bar the services, as customer is in barring exception list."),
    CRM404("CRM404","Ticket already exist for customer"),
    CRM405("CRM405","Same problem had been resolved, same Ticket ID re-opened"),
    CRM406("CRM406","Same problem had been resolved, recently. Wait to close the previous issue."),
    CRM407("CRM407","No mass outage entry found"),
    CRM408("CRM408","Customer doesn't exist"),
    CRM409("CRM409","Invalid QRC Category."),
    CRM410("CRM410","Invalid service name."),
    CRM411("CRM411","Invalid RCA value."),
    CRM412("CRM412","Invalid status."),
    CRM413("CRM413","Invalid QRC sub-sub-category."),
    CRM414("CRM414","Invalid from bin."),
    CRM415("CRM415","Invalid to bin."),
    CRM416("CRM416","Duplicate QRC RCA Configuration."),
    CRM417("CRM417","Duplicate QRC Bin Mapping Configuration."),
    CRM418("CRM418","Invalid Sub Sub Category Name."),
    CRM419("CRM419","Invalid Qrc Type."),
    CRM420("CRM420","Invalid Resolution Code ."),
    CRM421("CRM421","Invalid Functional Bin."),
    CRM422("CRM422","Invalid Static Ip"),
    CRM423("CRM423","Invalid Amount"),
    CRM424("CRM424","Either Customer details or Instrument Number not found."),
    CRM426("CRM426","Addon Plan does not exists."),

    // CODE for QRC Mass Outage
    CRM451("CRM451","Selected Network Partner already exists in more than one outages."),
    CRM452("CRM452","Outage ETR Time should be greater than Outage Start Time."),
    CRM453("CRM453","Outage has been resolved already."),

   // CRM424("CRM424","Invalid Count"),
    CRM425("CRM425","Bin Mapping can't be create for self Bin"),
    CRM427("CRM427","Customer wallet balance is less than selected plan rental charges"),
    CRM428("CRM428","To reactivate the customer, Customer's outstanding should be less than or equal to zero"),
    CRM429("CRM429","For Same Plan, migration is not allowed."),
    CRM430("CRM430","Customer wallet Balance is less than shifting charges"),
    CRM431("CRM431","Can't post waiver request because only 2 Goodwill waiver allowed in a period of last six month."),
    CRM432("CRM432","Waiver is already posted against selected bill number."),
    CRM433("CRM433","Ticket ID limit exhausted for customer."),
    CRM434("CRM434","Bill Cycle change request is already in process."),
    CRM435("CRM435","Refund request is already posted."),
    CRM436("CRM436","Shifting request is already initiated."),
    CRM437("CRM437","New and Old both CPE status are same."),
    CRM438("CRM438","Refund can be initiated only for canceled/ PDC customers. "),
    CRM439("CRM439","Provided Ticket ID doesn't exist, please provide valid Ticket ID"),
    CRM440("CRM440","Wallet balance for the customer is Rs. X.X and differential amount required for selected plan is Rs Y.Y. Please ask customer to pay the differential amount to proceed further."),
    
    // Code for Billing API
    CRM500("CRM500","Unable to process your request, Billing API not working."),
    CRM501("CRM501","Unable to create customer in billing."),
    CRM502("CRM502","Unable to update customer in billing."),
    CRM503("CRM503","Unable to retrieve inventory from billing."),
    CRM504("CRM504","Unable to activate customer in billing."),
    CRM505("CRM505","Unable to post payment in billing."),
    CRM506("CRM506","Unable to post reversal in billing."),
    CRM507("CRM507","Unable to post charge in billing."),
    CRM508("CRM508","Unable to update customer status in billing."),
    CRM509("CRM509","Unable to update customer installation address in billing."),
    CRM510("CRM510","Unable to update customer billing address in billing."),
    CRM511("CRM511","Unable to update device details in billing"),
    CRM512("CRM512","Unable to post waiver in billing"),

    CRM513("CRM513","Unable to add plan in billing"),
    CRM514("CRM514","Unable to migrate plan in billing"),
    CRM515("CRM515","Unable to remove plan from billing"),
    CRM516("CRM516","Unable to Activate/Deactivate VAS in billing"),
    CRM517("CRM517","Unable to retrieve Customer Usage Details from billing"),
    CRM518("CRM518","Unable to cancel plan migration in billing."),
    CRM519("CRM519","Unable to renew plan in billing."),

    CRM520("CRM520","Unable to update barring exception in billing."),
    CRM521("CRM521","Unable to update unbarring exception in billing."),
    CRM522("CRM522","Unable to retrieve invoice details from billing."),

    CRM523("CRM523","Unable to Mount booster plan in billing."),
    CRM524("CRM524","Unable to change bill cycle in billing."),
    CRM525("CRM525","Unable to extend validity period in billing."),
    CRM526("CRM526","Unable to change business partner in billing."),
    CRM527("CRM527","Unable to terminate refund in billing."),
    CRM528("CRM528","Unable to process your request because expire date missing from billing."),
    CRM529("CRM529","Unable to process your request - no usage found for the customer."),
    // Code for External Trigger API
    CRM600("CRM600","Invalid credential, Unable to authenticate."),
    CRM601("CRM601","Action date Unavailable/Invalid, Please provide the same."),
    CRM602("CRM602","External Transaction Id Unavailable/Invalid, Please provide the same."),
    CRM603("CRM603","Customer ID Unavailable/Invalid, Please provide the same."),
    CRM604("CRM604","Payment date Unavailable/Invalid, Please provide the same."),
    CRM605("CRM605","Receipt No. Unavailable/Invalid, Please provide the same."),
    CRM606("CRM606","Amount Unavailable/Invalid, Please provide the same."),
    CRM607("CRM607","QRC Event Unavailable/Invalid, Please provide the same."),
    CRM608("CRM608","Reason Unavailable/Invalid, Please provide the same."),
    CRM609("CRM609","Remarks Unavailable/Invalid, Please provide the same."),
    CRM610("CRM610","Status Unavailable/Invalid, Please provide the same."),
    CRM611("CRM611","Receipt No. is already in use, Duplicate Receipt No. not allowed."),
    CRM612("CRM612","Payments can be captured only for prepaid customers."),
    CRM613("CRM613","Ticket with same QRC Event is already exist."),
    CRM614("CRM614","'Customer ID' or 'RMN' Unavailable/Invalid, Please provide the same."),
    CRM615("CRM615","Payment Transaction Id Unavailable/Invalid, Please provide the same."),
    CRM616("CRM616","Unable to process payment, Please try later."),
    CRM617("CRM617","Activation Pending,Safe Custody,Permanent Disconnected for customer, Unable to process your request."),
    CRM618("CRM618","Payment Transaction ID is already in use, Duplicate Transaction ID not allowed."),
    CRM619("CRM619","Still billing has not updated the plan."),


    // Code for Finance
    CRM701("CRM701","CAF not submitted to Fulfillment Team."),
    CRM702("CRM702","Reversal for same customer can not be processed."),
    CRM703("CRM703","Cash Receipt is not in proper format."),
    CRM704("CRM704","Refund Details not present/request status proceessed in CRM for this customer."),
    CRM706("CRM706","Payment posted successfully but Unable to update customer status in billing."),


    // Code for Selfcare
    CRM801("CRM801","Customer has multiple accounts."),
    CRM802("CRM802","Wrong old password."),
    CRM803("CRM803","New Password or Old Password Can Not be Blank."),
    CRM804("CRM804","No account associated. Please contact Customer Care."),
    CRM805("CRM805","Customer ID and Registered Mobile Number can not be blank."),
    CRM806("CRM806","Please provide either 'Customer ID' or 'RMN' or 'Email'."),
    CRM807("CRM807","Re-type password dosen't match"),
    CRM808("CRM808","Your Password has been updated successfully. "),
    CRM809("CRM809","Please enter valid 'RMN' or 'Customer ID'."),
    CRM810("CRM810","Customer Status is PD."),
    CRM811("CRM811","Please provide valid Pincode."),
    // Payment Gateway
    CRM901("CRM901","Error from gateway."),
    CRM902("CRM902","Response Hash mismatch."),
    CRM903("CRM903","Payment gateway not configured."),
    
    //E-CAF customer's details
    CRM851("CRM851","Please provide valid connection type."),
    CRM852("CRM852","Please provide customer's first name."),
    CRM853("CRM853","Please provide customer's last name."),
    CRM854("CRM854","Customer Mobile No. Unavailable/Invalid, Please provide the same."),
    CRM855("CRM855","Please provide Email-ID in valid format."),
    CRM856("CRM856","Please provide father/husband's first name."),    
    CRM857("CRM857","Please provide father/husband's last name."),
    CRM858("CRM858","Please provide valid customer gender."),
    CRM859("CRM859","Please provide customer nationality."),
    CRM860("CRM860","Please provide customer's date of birth."),
    CRM861("CRM861","Please provide 10 digit alphanumeric PAN or GIR number."),
    CRM862("CRM862","Please provide valid product."),
    CRM863("CRM863","CAF date should be within past 90 days to today, Please provide the same."),
    CRM864("CRM864","Please provide valid sales representative code."),
    CRM865("CRM865","Please provide valid business partner code."),
    CRM866("CRM866","Please provide valid service type."),
    CRM879("CRM879","CAF Number should be numeric and 8 character long."),
   
    //E-CAF Plan
    CRM867("CRM867","Please provide valid base plan name."),
    CRM868("CRM868","Please provide valid add-On plan"),
    CRM869("CRM869","Please provide usage type of service."),
    CRM871("CRM871","Plan is not allowed for activation."),
    CRM872("CRM872","Either address proof or Id proof is not valid."),
    
    //E-CAF Payment
    CRM870("CRM870", "User Id can not left blank."),
    CRM873("CRM873","Amount Unavailable/Invalid, Please provide the same."),    
    CRM874("CRM874","Please provide paymentMode."),
    CRM890("CRM890","Activation Charges Unavailable/Invalid, Please provide the same."), 
    CRM891("CRM891","Security Charges Unavailable/Invalid, Please provide the same."), 
    // E-CAF Aadhar Details
    CRM875("CRM875","Please provide 12 digit Aadhar No."),
    CRM876("CRM876","Please provide aadhar address."),
    CRM877("CRM877","Please provide property details."),
    CRM878("CRM878","Please provide inst. address."),
    //E-CAF Cheque Payment
    CRM880("CRM880","Please provide valid cheque number."),
    CRM881("CRM881","Please provide valid bank branch name."),
    CRM882("CRM882","Please provide valid bank name."),
    CRM883("CRM883","Please provide valid city name."),
    CRM884("CRM884","Please provide valid cheque date."),
    CRM885("CRM885","Document Type not selected for file name."),
    CRM886("CRM886","File name has no valid extension."),
    CRM887("CRM887","SR Code is not found."),
    CRM888("CRM888","BP Code is not found."),
    CRM889("CRM889","Payment Mode Unavailable/Invalid, Please provide the same."),   
    // Common Code
    CRM990("CRM990","Duplicate Values are not allowed."),
    CRM991("CRM991","Please select at least one option."),
    CRM992("CRM992","Request Data Missing for the DAO."),
    CRM993("CRM993","Please Select At least one checkbox."),
    CRM994("CRM994","Service Name Not Correct."),
    CRM995("CRM995","Please modify the values before submitting."),
    CRM996("CRM996","Record Not Found."),
    CRM997("CRM997","Invalid Request, Required details are not present."),
    CRM998("CRM998","Service Unavailable."),
    CRM999("CRM999","Unable to process your request, Please try later."),
    CRM300("CRM300","Unable to process your request, API not working."),
    CRM1000("CRM1000","Customer not in Mass Outage");
    
    

    String statusCode = null;
    String statusDesc = null;

    private CRMServiceCode( String statusCode, String statusDesc )
    {
        this.statusCode = statusCode;
        this.statusDesc = statusDesc;
    }

    public String getStatusCode()
    {
        return statusCode;
    }

    public String getStatusDesc()
    {
        return statusDesc;
    }
}
