
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.AddChargeResult;
import org.datacontract.schemas._2004._07.AddPlan;
import org.datacontract.schemas._2004._07.AddPlanResult;
import org.datacontract.schemas._2004._07.ApiRequest;
import org.datacontract.schemas._2004._07.ApiResponse;
import org.datacontract.schemas._2004._07.BillDetail;
import org.datacontract.schemas._2004._07.BillDetails;
import org.datacontract.schemas._2004._07.CancelAddPostpaidPlanResult;
import org.datacontract.schemas._2004._07.CancelPlanMigrationResult;
import org.datacontract.schemas._2004._07.ChangeAddress;
import org.datacontract.schemas._2004._07.ChangeBillCycleResult;
import org.datacontract.schemas._2004._07.ChangeBusinessPartnerResult;
import org.datacontract.schemas._2004._07.ChangeDeviceDetail;
import org.datacontract.schemas._2004._07.CheckPlanFeasibilityResult;
import org.datacontract.schemas._2004._07.ClsAddCharge;
import org.datacontract.schemas._2004._07.ClsCustomerBaringExceptionList;
import org.datacontract.schemas._2004._07.ClsCustomerNotificationExceptionList;
import org.datacontract.schemas._2004._07.ClsCustomerSpeedExceptionList;
import org.datacontract.schemas._2004._07.ClsCustomerUnbaringExceptionList;
import org.datacontract.schemas._2004._07.ClsDisableWalledGarden;
import org.datacontract.schemas._2004._07.ClsP2PReBarring;
import org.datacontract.schemas._2004._07.ClsTerminationRefund;
import org.datacontract.schemas._2004._07.CreateCustomerResult;
import org.datacontract.schemas._2004._07.Customer;
import org.datacontract.schemas._2004._07.CustomerActivation;
import org.datacontract.schemas._2004._07.CustomerActivationResult;
import org.datacontract.schemas._2004._07.CustomerBaringExceptionListResult;
import org.datacontract.schemas._2004._07.CustomerCancelPayment;
import org.datacontract.schemas._2004._07.CustomerDetail;
import org.datacontract.schemas._2004._07.CustomerDiscountDetails;
import org.datacontract.schemas._2004._07.CustomerNotificationExceptionListResult;
import org.datacontract.schemas._2004._07.CustomerPostPayment;
import org.datacontract.schemas._2004._07.CustomerPostPaymentResult;
import org.datacontract.schemas._2004._07.CustomerSpeedExceptionListResult;
import org.datacontract.schemas._2004._07.CustomerUnbaringExceptionListResult;
import org.datacontract.schemas._2004._07.CustomerUpdate;
import org.datacontract.schemas._2004._07.CustomerUsageDetail;
import org.datacontract.schemas._2004._07.DeviceDetailResult;
import org.datacontract.schemas._2004._07.DisableWalledGardenResult;
import org.datacontract.schemas._2004._07.InstantOfferAllocation;
import org.datacontract.schemas._2004._07.InventoryItemToLCOResult;
import org.datacontract.schemas._2004._07.LastPaymentResult;
import org.datacontract.schemas._2004._07.OfferAllocation;
import org.datacontract.schemas._2004._07.P2PReBarringResult;
import org.datacontract.schemas._2004._07.PaymentAdjustment;
import org.datacontract.schemas._2004._07.PaymentAdjustmentResult;
import org.datacontract.schemas._2004._07.RefferalDetailsResult;
import org.datacontract.schemas._2004._07.TerminationRefundResult;
import org.datacontract.schemas._2004._07.UserSessionResult;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ICustomer", targetNamespace = "h8SSRMS")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.ObjectFactory.class,
    h8ssrms.ObjectFactory.class
})
public interface ICustomer {


    /**
     * 
     * @param changePlan
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.AddPlanResult
     */
    @WebMethod(operationName = "AddPlan", action = "h8SSRMS/ICustomer/AddPlan")
    @WebResult(name = "AddPlanResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "AddPlan", targetNamespace = "h8SSRMS", className = "h8ssrms.AddPlan")
    @ResponseWrapper(localName = "AddPlanResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.AddPlanResponse")
    public AddPlanResult addPlan(
        @WebParam(name = "changePlan", targetNamespace = "h8SSRMS")
        AddPlan changePlan,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param request
     * @param ac
     * @return
     *     returns org.datacontract.schemas._2004._07.AddChargeResult
     */
    @WebMethod(operationName = "AddCharge", action = "h8SSRMS/ICustomer/AddCharge")
    @WebResult(name = "AddChargeResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "AddCharge", targetNamespace = "h8SSRMS", className = "h8ssrms.AddCharge")
    @ResponseWrapper(localName = "AddChargeResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.AddChargeResponse")
    public AddChargeResult addCharge(
        @WebParam(name = "ac", targetNamespace = "h8SSRMS")
        ClsAddCharge ac,
        @WebParam(name = "request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param cbel
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.CustomerBaringExceptionListResult
     */
    @WebMethod(operationName = "CustomerBaringExceptionList", action = "h8SSRMS/ICustomer/CustomerBaringExceptionList")
    @WebResult(name = "CustomerBaringExceptionListResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "CustomerBaringExceptionList", targetNamespace = "h8SSRMS", className = "h8ssrms.CustomerBaringExceptionList")
    @ResponseWrapper(localName = "CustomerBaringExceptionListResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.CustomerBaringExceptionListResponse")
    public CustomerBaringExceptionListResult customerBaringExceptionList(
        @WebParam(name = "CBEL", targetNamespace = "h8SSRMS")
        ClsCustomerBaringExceptionList cbel,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param request
     * @param cuel
     * @return
     *     returns org.datacontract.schemas._2004._07.CustomerUnbaringExceptionListResult
     */
    @WebMethod(operationName = "CustomerUnbaringExceptionList", action = "h8SSRMS/ICustomer/CustomerUnbaringExceptionList")
    @WebResult(name = "CustomerUnbaringExceptionListResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "CustomerUnbaringExceptionList", targetNamespace = "h8SSRMS", className = "h8ssrms.CustomerUnbaringExceptionList")
    @ResponseWrapper(localName = "CustomerUnbaringExceptionListResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.CustomerUnbaringExceptionListResponse")
    public CustomerUnbaringExceptionListResult customerUnbaringExceptionList(
        @WebParam(name = "CUEL", targetNamespace = "h8SSRMS")
        ClsCustomerUnbaringExceptionList cuel,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param cbel
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.CustomerSpeedExceptionListResult
     */
    @WebMethod(operationName = "CustomerSpeedExceptionList", action = "h8SSRMS/ICustomer/CustomerSpeedExceptionList")
    @WebResult(name = "CustomerSpeedExceptionListResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "CustomerSpeedExceptionList", targetNamespace = "h8SSRMS", className = "h8ssrms.CustomerSpeedExceptionList")
    @ResponseWrapper(localName = "CustomerSpeedExceptionListResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.CustomerSpeedExceptionListResponse")
    public CustomerSpeedExceptionListResult customerSpeedExceptionList(
        @WebParam(name = "CBEL", targetNamespace = "h8SSRMS")
        ClsCustomerSpeedExceptionList cbel,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param cbel
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.P2PReBarringResult
     */
    @WebMethod(operationName = "P2PReBarring", action = "h8SSRMS/ICustomer/P2PReBarring")
    @WebResult(name = "P2PReBarringResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "P2PReBarring", targetNamespace = "h8SSRMS", className = "h8ssrms.P2PReBarring")
    @ResponseWrapper(localName = "P2PReBarringResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.P2PReBarringResponse")
    public P2PReBarringResult p2PReBarring(
        @WebParam(name = "CBEL", targetNamespace = "h8SSRMS")
        ClsP2PReBarring cbel,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param cbel
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.TerminationRefundResult
     */
    @WebMethod(operationName = "TerminationRefund", action = "h8SSRMS/ICustomer/TerminationRefund")
    @WebResult(name = "TerminationRefundResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "TerminationRefund", targetNamespace = "h8SSRMS", className = "h8ssrms.TerminationRefund")
    @ResponseWrapper(localName = "TerminationRefundResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.TerminationRefundResponse")
    public TerminationRefundResult terminationRefund(
        @WebParam(name = "CBEL", targetNamespace = "h8SSRMS")
        ClsTerminationRefund cbel,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param cbel
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.DisableWalledGardenResult
     */
    @WebMethod(operationName = "DisableWalledGarden", action = "h8SSRMS/ICustomer/DisableWalledGarden")
    @WebResult(name = "DisableWalledGardenResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "DisableWalledGarden", targetNamespace = "h8SSRMS", className = "h8ssrms.DisableWalledGarden")
    @ResponseWrapper(localName = "DisableWalledGardenResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.DisableWalledGardenResponse")
    public DisableWalledGardenResult disableWalledGarden(
        @WebParam(name = "CBEL", targetNamespace = "h8SSRMS")
        ClsDisableWalledGarden cbel,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param cbel
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.CustomerNotificationExceptionListResult
     */
    @WebMethod(operationName = "CustomerNotificationExceptionList", action = "h8SSRMS/ICustomer/CustomerNotificationExceptionList")
    @WebResult(name = "CustomerNotificationExceptionListResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "CustomerNotificationExceptionList", targetNamespace = "h8SSRMS", className = "h8ssrms.CustomerNotificationExceptionList")
    @ResponseWrapper(localName = "CustomerNotificationExceptionListResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.CustomerNotificationExceptionListResponse")
    public CustomerNotificationExceptionListResult customerNotificationExceptionList(
        @WebParam(name = "CBEL", targetNamespace = "h8SSRMS")
        ClsCustomerNotificationExceptionList cbel,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param modelNo
     * @param request
     * @param lco
     * @return
     *     returns org.datacontract.schemas._2004._07.InventoryItemToLCOResult
     */
    @WebMethod(operationName = "GetDistributorInventoryList", action = "h8SSRMS/ICustomer/GetDistributorInventoryList")
    @WebResult(name = "GetDistributorInventoryListResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "GetDistributorInventoryList", targetNamespace = "h8SSRMS", className = "h8ssrms.GetDistributorInventoryList")
    @ResponseWrapper(localName = "GetDistributorInventoryListResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.GetDistributorInventoryListResponse")
    public InventoryItemToLCOResult getDistributorInventoryList(
        @WebParam(name = "ModelNo", targetNamespace = "h8SSRMS")
        String modelNo,
        @WebParam(name = "LCO", targetNamespace = "h8SSRMS")
        String lco,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param request
     * @param planCode
     * @param customerNo
     * @return
     *     returns org.datacontract.schemas._2004._07.CheckPlanFeasibilityResult
     */
    @WebMethod(operationName = "CheckFeasibility", action = "h8SSRMS/ICustomer/CheckFeasibility")
    @WebResult(name = "CheckFeasibilityResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "CheckFeasibility", targetNamespace = "h8SSRMS", className = "h8ssrms.CheckFeasibility")
    @ResponseWrapper(localName = "CheckFeasibilityResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.CheckFeasibilityResponse")
    public CheckPlanFeasibilityResult checkFeasibility(
        @WebParam(name = "customerNo", targetNamespace = "h8SSRMS")
        Long customerNo,
        @WebParam(name = "planCode", targetNamespace = "h8SSRMS")
        String planCode,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param request
     * @param offer
     * @return
     *     returns org.datacontract.schemas._2004._07.ApiResponse
     */
    @WebMethod(operationName = "ChangeOffer", action = "h8SSRMS/ICustomer/ChangeOffer")
    @WebResult(name = "ChangeOfferResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "ChangeOffer", targetNamespace = "h8SSRMS", className = "h8ssrms.ChangeOffer")
    @ResponseWrapper(localName = "ChangeOfferResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.ChangeOfferResponse")
    public ApiResponse changeOffer(
        @WebParam(name = "offer", targetNamespace = "h8SSRMS")
        OfferAllocation offer,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param request
     * @param offer
     * @return
     *     returns org.datacontract.schemas._2004._07.ApiResponse
     */
    @WebMethod(operationName = "InstantOfferRenew", action = "h8SSRMS/ICustomer/InstantOfferRenew")
    @WebResult(name = "InstantOfferRenewResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "InstantOfferRenew", targetNamespace = "h8SSRMS", className = "h8ssrms.InstantOfferRenew")
    @ResponseWrapper(localName = "InstantOfferRenewResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.InstantOfferRenewResponse")
    public ApiResponse instantOfferRenew(
        @WebParam(name = "offer", targetNamespace = "h8SSRMS")
        InstantOfferAllocation offer,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param request
     * @param offer
     * @return
     *     returns org.datacontract.schemas._2004._07.ApiResponse
     */
    @WebMethod(operationName = "InstantPrepaidOfferRenew", action = "h8SSRMS/ICustomer/InstantPrepaidOfferRenew")
    @WebResult(name = "InstantPrepaidOfferRenewResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "InstantPrepaidOfferRenew", targetNamespace = "h8SSRMS", className = "h8ssrms.InstantPrepaidOfferRenew")
    @ResponseWrapper(localName = "InstantPrepaidOfferRenewResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.InstantPrepaidOfferRenewResponse")
    public ApiResponse instantPrepaidOfferRenew(
        @WebParam(name = "offer", targetNamespace = "h8SSRMS")
        InstantOfferAllocation offer,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param remark
     * @param statusName
     * @param request
     * @param customerNo
     * @return
     *     returns org.datacontract.schemas._2004._07.ApiResponse
     */
    @WebMethod(operationName = "ChangeStatus", action = "h8SSRMS/ICustomer/ChangeStatus")
    @WebResult(name = "ChangeStatusResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "ChangeStatus", targetNamespace = "h8SSRMS", className = "h8ssrms.ChangeStatus")
    @ResponseWrapper(localName = "ChangeStatusResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.ChangeStatusResponse")
    public ApiResponse changeStatus(
        @WebParam(name = "customerNo", targetNamespace = "h8SSRMS")
        Long customerNo,
        @WebParam(name = "remark", targetNamespace = "h8SSRMS")
        String remark,
        @WebParam(name = "statusName", targetNamespace = "h8SSRMS")
        String statusName,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param request
     * @param changedevice
     * @return
     *     returns org.datacontract.schemas._2004._07.ApiResponse
     */
    @WebMethod(operationName = "ChangeDeviceDetail", action = "h8SSRMS/ICustomer/ChangeDeviceDetail")
    @WebResult(name = "ChangeDeviceDetailResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "ChangeDeviceDetail", targetNamespace = "h8SSRMS", className = "h8ssrms.ChangeDeviceDetail")
    @ResponseWrapper(localName = "ChangeDeviceDetailResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.ChangeDeviceDetailResponse")
    public ApiResponse changeDeviceDetail(
        @WebParam(name = "changedevice", targetNamespace = "h8SSRMS")
        ChangeDeviceDetail changedevice,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param adjustment
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.PaymentAdjustmentResult
     */
    @WebMethod(operationName = "PaymentAdjustment", action = "h8SSRMS/ICustomer/PaymentAdjustment")
    @WebResult(name = "PaymentAdjustmentResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "PaymentAdjustment", targetNamespace = "h8SSRMS", className = "h8ssrms.PaymentAdjustment")
    @ResponseWrapper(localName = "PaymentAdjustmentResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.PaymentAdjustmentResponse")
    public PaymentAdjustmentResult paymentAdjustment(
        @WebParam(name = "Adjustment", targetNamespace = "h8SSRMS")
        PaymentAdjustment adjustment,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param expiryDate
     * @param request
     * @param customerNo
     * @return
     *     returns org.datacontract.schemas._2004._07.ApiResponse
     */
    @WebMethod(operationName = "AllowGracePeriod", action = "h8SSRMS/ICustomer/AllowGracePeriod")
    @WebResult(name = "AllowGracePeriodResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "AllowGracePeriod", targetNamespace = "h8SSRMS", className = "h8ssrms.AllowGracePeriod")
    @ResponseWrapper(localName = "AllowGracePeriodResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.AllowGracePeriodResponse")
    public ApiResponse allowGracePeriod(
        @WebParam(name = "customerNo", targetNamespace = "h8SSRMS")
        Long customerNo,
        @WebParam(name = "expiryDate", targetNamespace = "h8SSRMS")
        XMLGregorianCalendar expiryDate,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param request
     * @param customerNo
     * @return
     *     returns org.datacontract.schemas._2004._07.DeviceDetailResult
     */
    @WebMethod(operationName = "GetDeviceDetail", action = "h8SSRMS/ICustomer/GetDeviceDetail")
    @WebResult(name = "GetDeviceDetailResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "GetDeviceDetail", targetNamespace = "h8SSRMS", className = "h8ssrms.GetDeviceDetail")
    @ResponseWrapper(localName = "GetDeviceDetailResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.GetDeviceDetailResponse")
    public DeviceDetailResult getDeviceDetail(
        @WebParam(name = "customerNo", targetNamespace = "h8SSRMS")
        Long customerNo,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param custpay
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.CustomerPostPaymentResult
     */
    @WebMethod(operationName = "PostPayment", action = "h8SSRMS/ICustomer/PostPayment")
    @WebResult(name = "PostPaymentResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "PostPayment", targetNamespace = "h8SSRMS", className = "h8ssrms.PostPayment")
    @ResponseWrapper(localName = "PostPaymentResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.PostPaymentResponse")
    public CustomerPostPaymentResult postPayment(
        @WebParam(name = "custpay", targetNamespace = "h8SSRMS")
        CustomerPostPayment custpay,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param payment
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.ApiResponse
     */
    @WebMethod(operationName = "CancelPayment", action = "h8SSRMS/ICustomer/CancelPayment")
    @WebResult(name = "CancelPaymentResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "CancelPayment", targetNamespace = "h8SSRMS", className = "h8ssrms.CancelPayment")
    @ResponseWrapper(localName = "CancelPaymentResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.CancelPaymentResponse")
    public ApiResponse cancelPayment(
        @WebParam(name = "Payment", targetNamespace = "h8SSRMS")
        CustomerCancelPayment payment,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param custBillAdd
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.ApiResponse
     */
    @WebMethod(operationName = "ChangeAddress", action = "h8SSRMS/ICustomer/ChangeAddress")
    @WebResult(name = "ChangeAddressResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "ChangeAddress", targetNamespace = "h8SSRMS", className = "h8ssrms.ChangeAddress")
    @ResponseWrapper(localName = "ChangeAddressResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.ChangeAddressResponse")
    public ApiResponse changeAddress(
        @WebParam(name = "custBillAdd", targetNamespace = "h8SSRMS")
        ChangeAddress custBillAdd,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param request
     * @param acc
     * @return
     *     returns org.datacontract.schemas._2004._07.CreateCustomerResult
     */
    @WebMethod(operationName = "CreateCustomer", action = "h8SSRMS/ICustomer/CreateCustomer")
    @WebResult(name = "CreateCustomerResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "CreateCustomer", targetNamespace = "h8SSRMS", className = "h8ssrms.CreateCustomer")
    @ResponseWrapper(localName = "CreateCustomerResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.CreateCustomerResponse")
    public CreateCustomerResult createCustomer(
        @WebParam(name = "acc", targetNamespace = "h8SSRMS")
        Customer acc,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param crfNo
     * @param emailId
     * @param rmn
     * @param rtn
     * @param request
     * @param customerNo
     * @return
     *     returns org.datacontract.schemas._2004._07.CustomerDetail
     */
    @WebMethod(operationName = "GetCustomerDetail", action = "h8SSRMS/ICustomer/GetCustomerDetail")
    @WebResult(name = "GetCustomerDetailResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "GetCustomerDetail", targetNamespace = "h8SSRMS", className = "h8ssrms.GetCustomerDetail")
    @ResponseWrapper(localName = "GetCustomerDetailResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.GetCustomerDetailResponse")
    public CustomerDetail getCustomerDetail(
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request,
        @WebParam(name = "customerNo", targetNamespace = "h8SSRMS")
        Long customerNo,
        @WebParam(name = "CRFNo", targetNamespace = "h8SSRMS")
        String crfNo,
        @WebParam(name = "RMN", targetNamespace = "h8SSRMS")
        String rmn,
        @WebParam(name = "RTN", targetNamespace = "h8SSRMS")
        String rtn,
        @WebParam(name = "EmailId", targetNamespace = "h8SSRMS")
        String emailId);

    /**
     * 
     * @param billNumber
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.BillDetail
     */
    @WebMethod(operationName = "GetBillDetail", action = "h8SSRMS/ICustomer/GetBillDetail")
    @WebResult(name = "GetBillDetailResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "GetBillDetail", targetNamespace = "h8SSRMS", className = "h8ssrms.GetBillDetail")
    @ResponseWrapper(localName = "GetBillDetailResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.GetBillDetailResponse")
    public BillDetail getBillDetail(
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request,
        @WebParam(name = "billNumber", targetNamespace = "h8SSRMS")
        String billNumber);

    /**
     * 
     * @param request
     * @param customerNo
     * @return
     *     returns org.datacontract.schemas._2004._07.RefferalDetailsResult
     */
    @WebMethod(operationName = "GetRefferalPoints", action = "h8SSRMS/ICustomer/GetRefferalPoints")
    @WebResult(name = "GetRefferalPointsResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "GetRefferalPoints", targetNamespace = "h8SSRMS", className = "h8ssrms.GetRefferalPoints")
    @ResponseWrapper(localName = "GetRefferalPointsResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.GetRefferalPointsResponse")
    public RefferalDetailsResult getRefferalPoints(
        @WebParam(name = "CustomerNo", targetNamespace = "h8SSRMS")
        Long customerNo,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param request
     * @param acc
     * @return
     *     returns org.datacontract.schemas._2004._07.ApiResponse
     */
    @WebMethod(operationName = "UpdateCustomer", action = "h8SSRMS/ICustomer/UpdateCustomer")
    @WebResult(name = "UpdateCustomerResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "UpdateCustomer", targetNamespace = "h8SSRMS", className = "h8ssrms.UpdateCustomer")
    @ResponseWrapper(localName = "UpdateCustomerResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.UpdateCustomerResponse")
    public ApiResponse updateCustomer(
        @WebParam(name = "acc", targetNamespace = "h8SSRMS")
        CustomerUpdate acc,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param request
     * @param custact
     * @return
     *     returns org.datacontract.schemas._2004._07.CustomerActivationResult
     */
    @WebMethod(operationName = "CustomerActivation", action = "h8SSRMS/ICustomer/CustomerActivation")
    @WebResult(name = "CustomerActivationResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "CustomerActivation", targetNamespace = "h8SSRMS", className = "h8ssrms.CustomerActivation")
    @ResponseWrapper(localName = "CustomerActivationResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.CustomerActivationResponse")
    public CustomerActivationResult customerActivation(
        @WebParam(name = "custact", targetNamespace = "h8SSRMS")
        CustomerActivation custact,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param request
     * @param customerNo
     * @return
     *     returns org.datacontract.schemas._2004._07.LastPaymentResult
     */
    @WebMethod(operationName = "GetLastPayment", action = "h8SSRMS/ICustomer/GetLastPayment")
    @WebResult(name = "GetLastPaymentResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "GetLastPayment", targetNamespace = "h8SSRMS", className = "h8ssrms.GetLastPayment")
    @ResponseWrapper(localName = "GetLastPaymentResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.GetLastPaymentResponse")
    public LastPaymentResult getLastPayment(
        @WebParam(name = "customerNo", targetNamespace = "h8SSRMS")
        Long customerNo,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param request
     * @param apiTransID
     * @return
     *     returns org.datacontract.schemas._2004._07.CancelPlanMigrationResult
     */
    @WebMethod(operationName = "CancelPlanOfferMigration", action = "h8SSRMS/ICustomer/CancelPlanOfferMigration")
    @WebResult(name = "CancelPlanOfferMigrationResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "CancelPlanOfferMigration", targetNamespace = "h8SSRMS", className = "h8ssrms.CancelPlanOfferMigration")
    @ResponseWrapper(localName = "CancelPlanOfferMigrationResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.CancelPlanOfferMigrationResponse")
    public CancelPlanMigrationResult cancelPlanOfferMigration(
        @WebParam(name = "ApiTransID", targetNamespace = "h8SSRMS")
        Long apiTransID,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param request
     * @param customerNo
     * @return
     *     returns org.datacontract.schemas._2004._07.CustomerDiscountDetails
     */
    @WebMethod(operationName = "GetDiscountDetails", action = "h8SSRMS/ICustomer/GetDiscountDetails")
    @WebResult(name = "GetDiscountDetailsResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "GetDiscountDetails", targetNamespace = "h8SSRMS", className = "h8ssrms.GetDiscountDetails")
    @ResponseWrapper(localName = "GetDiscountDetailsResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.GetDiscountDetailsResponse")
    public CustomerDiscountDetails getDiscountDetails(
        @WebParam(name = "customerNo", targetNamespace = "h8SSRMS")
        Long customerNo,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param request
     * @param customerNo
     * @return
     *     returns org.datacontract.schemas._2004._07.UserSessionResult
     */
    @WebMethod(operationName = "GetUserSessionOfDay", action = "h8SSRMS/ICustomer/GetUserSessionOfDay")
    @WebResult(name = "GetUserSessionOfDayResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "GetUserSessionOfDay", targetNamespace = "h8SSRMS", className = "h8ssrms.GetUserSessionOfDay")
    @ResponseWrapper(localName = "GetUserSessionOfDayResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.GetUserSessionOfDayResponse")
    public UserSessionResult getUserSessionOfDay(
        @WebParam(name = "customerNo", targetNamespace = "h8SSRMS")
        Long customerNo,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param request
     * @param customerNo
     * @return
     *     returns org.datacontract.schemas._2004._07.UserSessionResult
     */
    @WebMethod(operationName = "GetUserSessionOfWeek", action = "h8SSRMS/ICustomer/GetUserSessionOfWeek")
    @WebResult(name = "GetUserSessionOfWeekResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "GetUserSessionOfWeek", targetNamespace = "h8SSRMS", className = "h8ssrms.GetUserSessionOfWeek")
    @ResponseWrapper(localName = "GetUserSessionOfWeekResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.GetUserSessionOfWeekResponse")
    public UserSessionResult getUserSessionOfWeek(
        @WebParam(name = "customerNo", targetNamespace = "h8SSRMS")
        Long customerNo,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param request
     * @param customerNo
     * @return
     *     returns org.datacontract.schemas._2004._07.UserSessionResult
     */
    @WebMethod(operationName = "GetUserSessionOfMonth", action = "h8SSRMS/ICustomer/GetUserSessionOfMonth")
    @WebResult(name = "GetUserSessionOfMonthResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "GetUserSessionOfMonth", targetNamespace = "h8SSRMS", className = "h8ssrms.GetUserSessionOfMonth")
    @ResponseWrapper(localName = "GetUserSessionOfMonthResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.GetUserSessionOfMonthResponse")
    public UserSessionResult getUserSessionOfMonth(
        @WebParam(name = "customerNo", targetNamespace = "h8SSRMS")
        Long customerNo,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param startDate
     * @param request
     * @param customerNumber
     * @param endDate
     * @return
     *     returns org.datacontract.schemas._2004._07.BillDetails
     */
    @WebMethod(action = "h8SSRMS/ICustomer/getBillingDetails")
    @WebResult(name = "getBillingDetailsResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "getBillingDetails", targetNamespace = "h8SSRMS", className = "h8ssrms.GetBillingDetails")
    @ResponseWrapper(localName = "getBillingDetailsResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.GetBillingDetailsResponse")
    public BillDetails getBillingDetails(
        @WebParam(name = "customerNumber", targetNamespace = "h8SSRMS")
        Long customerNumber,
        @WebParam(name = "startDate", targetNamespace = "h8SSRMS")
        XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "h8SSRMS")
        XMLGregorianCalendar endDate,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param crfNo
     * @param emailId
     * @param rmn
     * @param rtn
     * @param request
     * @param customerNo
     * @return
     *     returns org.datacontract.schemas._2004._07.CustomerUsageDetail
     */
    @WebMethod(operationName = "GetCustomerUsageDetail", action = "h8SSRMS/ICustomer/GetCustomerUsageDetail")
    @WebResult(name = "GetCustomerUsageDetailResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "GetCustomerUsageDetail", targetNamespace = "h8SSRMS", className = "h8ssrms.GetCustomerUsageDetail")
    @ResponseWrapper(localName = "GetCustomerUsageDetailResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.GetCustomerUsageDetailResponse")
    public CustomerUsageDetail getCustomerUsageDetail(
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request,
        @WebParam(name = "customerNo", targetNamespace = "h8SSRMS")
        Long customerNo,
        @WebParam(name = "CRFNo", targetNamespace = "h8SSRMS")
        String crfNo,
        @WebParam(name = "RMN", targetNamespace = "h8SSRMS")
        String rmn,
        @WebParam(name = "RTN", targetNamespace = "h8SSRMS")
        String rtn,
        @WebParam(name = "EmailId", targetNamespace = "h8SSRMS")
        String emailId);

    /**
     * 
     * @param isImmediate
     * @param request
     * @param planCode
     * @param customerNo
     * @return
     *     returns org.datacontract.schemas._2004._07.CancelAddPostpaidPlanResult
     */
    @WebMethod(operationName = "CancelAdditionalPlan", action = "h8SSRMS/ICustomer/CancelAdditionalPlan")
    @WebResult(name = "CancelAdditionalPlanResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "CancelAdditionalPlan", targetNamespace = "h8SSRMS", className = "h8ssrms.CancelAdditionalPlan")
    @ResponseWrapper(localName = "CancelAdditionalPlanResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.CancelAdditionalPlanResponse")
    public CancelAddPostpaidPlanResult cancelAdditionalPlan(
        @WebParam(name = "CustomerNo", targetNamespace = "h8SSRMS")
        Long customerNo,
        @WebParam(name = "PlanCode", targetNamespace = "h8SSRMS")
        String planCode,
        @WebParam(name = "IsImmediate", targetNamespace = "h8SSRMS")
        Boolean isImmediate,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param status
     * @param billCycleName
     * @param request
     * @param customerNo
     * @return
     *     returns org.datacontract.schemas._2004._07.ChangeBillCycleResult
     */
    @WebMethod(operationName = "ChangeBillCycle", action = "h8SSRMS/ICustomer/ChangeBillCycle")
    @WebResult(name = "ChangeBillCycleResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "ChangeBillCycle", targetNamespace = "h8SSRMS", className = "h8ssrms.ChangeBillCycle")
    @ResponseWrapper(localName = "ChangeBillCycleResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.ChangeBillCycleResponse")
    public ChangeBillCycleResult changeBillCycle(
        @WebParam(name = "CustomerNo", targetNamespace = "h8SSRMS")
        Long customerNo,
        @WebParam(name = "BillCycleName", targetNamespace = "h8SSRMS")
        String billCycleName,
        @WebParam(name = "Status", targetNamespace = "h8SSRMS")
        String status,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

    /**
     * 
     * @param oldBusinessPartner
     * @param newBusinessPartner
     * @param request
     * @param customerNo
     * @return
     *     returns org.datacontract.schemas._2004._07.ChangeBusinessPartnerResult
     */
    @WebMethod(operationName = "ChangeBusinessPartner", action = "h8SSRMS/ICustomer/ChangeBusinessPartner")
    @WebResult(name = "ChangeBusinessPartnerResult", targetNamespace = "h8SSRMS")
    @RequestWrapper(localName = "ChangeBusinessPartner", targetNamespace = "h8SSRMS", className = "h8ssrms.ChangeBusinessPartner")
    @ResponseWrapper(localName = "ChangeBusinessPartnerResponse", targetNamespace = "h8SSRMS", className = "h8ssrms.ChangeBusinessPartnerResponse")
    public ChangeBusinessPartnerResult changeBusinessPartner(
        @WebParam(name = "CustomerNo", targetNamespace = "h8SSRMS")
        Long customerNo,
        @WebParam(name = "OldBusinessPartner", targetNamespace = "h8SSRMS")
        String oldBusinessPartner,
        @WebParam(name = "NewBusinessPartner", targetNamespace = "h8SSRMS")
        String newBusinessPartner,
        @WebParam(name = "Request", targetNamespace = "h8SSRMS")
        ApiRequest request);

}
